<script type="text/javascript">
    function usernameAvailability(usernameInput) {

        console.log('username::');
        console.log(usernameInput);
        jQuery.ajax({
            method: "POST",
            url: '/services/validate/validate/validate',
            showLoader: true,
            data: {
                username: usernameInput
            },
            success: function(result) {
                jQuery('#usernameStatus').html(result);
                // jQuery('#subform').prop('disabled', 0);
            }
        });
    }

    require([
        'jquery'
    ], function($) {

        $(document).on('input', '#username', function(e) {

            let usernameInput = $('#username').val();
            let msg;
            if (usernameInput.length == 0) {
                msg = "<span style='color:beige'>Enter a registered CNIC#</span>";
                btnStatus = 'true';
                console.log(btnStatus);
                // $('#subform').prop('disabled', 1);
            } else if (!(/^[0-9\|s]*$/).test(usernameInput)) {
                msg = "<span style='color:beige'>username can't contain spaces,alphabets and special characters</span>";
                btnStatus = 'true';
                console.log(btnStatus);
                //$('#subform').prop('disabled', 1);
            } else if (usernameInput.length != 0 && (usernameInput.length < 13 || usernameInput.length > 13)) {
                msg = "<span style='color:beige'>CNIC # must be 13 characters long</span>";
                btnStatus = 'true';
                console.log(btnStatus);
                //$('#subform').prop('disabled', 1);
            } else {
                usernameAvailability(usernameInput);
                btnStatus = 'false';
                console.log(btnStatus);

            }
            $('#usernameStatus').html(msg);
        });
    });
</script>

<div class="footer-top custom-footer-topp" style="padding-top:50px; padding-bottom:65px; background-color:#0000008f;">
    <div class="container">
        <div class="">
            <div class=" footer-top-center">
                <div class="footer-links-wrap">
                    <div class="footer-container content-toggle row">
                        <div class="h4 title col-md-4 col-5">
                            
                        </div>
                        <div class="footer-form col-md-4 col-12">
                            <div class="main-newsletter">
                                <div class="main-newsletter-inner">
                                    <div class="subscribe">
                                        <div class="block-content">
                                            <div class="input-box">
                                                <input type="text" style="border-radius:5px;" minlength="13" maxlength="13" placeholder="Enter Your Registered CNIC#" id="username">
                                                <div id="usernameStatus"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>