<!DOCTYPE html>

<html>

<head>

<meta charset="ISO-8859-1">

<title>Magento Failure </title>

</head>

 

	 <div>
<img alt="imarkplace"
  

	 	

	 	sfgsdfgsdfgsdfgsdfg

	 	

		 

	 </div>

	 <div style="position:absolute;left:33%;top:20%;z-index: 1;">

			<img src="https://lh3.googleusercontent.com/-FrLWgcLxUIg/W5j8jOG8RsI/AAAAAAAAC5I/zFUVeqTRNIAllYcUIqEW2ud8FDi2P0nAgCL0BGAYYCw/h556/2018-09-12.png"

				alt="Jazz Cash" style="border:00px solid red;" width="250px"

			/>

		</div>

	 

	 

	 

	 

</body>

</html>

