<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_B2BMarketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
/** @var $block \Webkul\Marketplace\Block\Page\Header */
$quickOrderBlock =  $block->getLayout()->createBlock(
    \Webkul\B2BMarketplace\Block\Supplier\Profile\QuickOrder::class
);
$helper = $quickOrderBlock->helper(\Webkul\Marketplace\Helper\Data::class);

$data = $helper->getSeller();
$shopUrl = '';
if (array_key_exists("shop_url", $data)) {
    $shopUrl = $data['shop_url'];
}
$profileUrl = $helper->getRewriteUrl('marketplace/seller/profile/shop/'.$shopUrl);
?>
<?php switch ($block->getShowPart()):
    case 'logo':
        ?>
        <a
            href="<?= /* @noEscape */ $block->getBaseUrl() ?>"
            class="wk-mp-logo">
            <span class="wk-mp-logo-img-wrapper">
                <img class="wk-mp-logo-img" 
                src="<?= /* @noEscape */ $block->getSellerDashboardLogoSrc()?>" 
                alt="<?= /* @noEscape */ $block->escapeHtml(__('Seller Panel')) ?>"/>
            </span>
        </a>
        <?php
              break;
    case 'user':
        ?>
        <?php
        $logo = $block->getSellerLogo();
        $logo = $helper->getMediaUrl().'avatar/'.$logo;
        ?>
        <div class="wk-mp-user wk-mp__action-dropdown-wrap">
            <a
                href="#"
                onlick="return false;"
                class="wk-mp__action-dropdown"
                title="<?= /* @noEscape */ $block->escapeHtml(__('My Account')) ?>"
                data-mage-init='{"dropdown":{}}'
                data-toggle="dropdown">
                <span class="wk-mp-seller-header-logo-wrapper">
                    <img class="wk-mp-seller-header-logo" 
                    src="<?= /* @noEscape */ $logo?>" 
                    alt="<?= /* @noEscape */ $block->escapeHtml(__('Seller Panel')) ?>"/>
                </span>
                <span class="wk-mp__action-dropdown-text">
                    <span class="wk-mp-user-account-text">
                        <span class="wk-mp-user-account-text-wrapper">
                            <?= /* @noEscape */ $block->escapeHtml($block->getSellerShopName()); ?>
                        </span>
                    </span>
                </span>
            </a>
            <ul class="wk-mp__action-dropdown-menu">
                <li class="wk-mp-dropdown-menu-settings">
                    <a
                        href="<?= /* @noEscape */ $block->getUrl('marketplace/account/editprofile') ?>"
                        <?= /* @noEscape */ $block->getUiId('user', 'account', 'settings')?>
                        title="<?= /* @noEscape */ $block->escapeHtml(__('Account Setting')) ?>">
                        <?= /* @noEscape */ __('Account Setting') ?>
                    </a>
                </li>
                <li class="wk-mp-dropdown-menu-buyer">
                    <a
                        href="<?= /* @noEscape */ $profileUrl; ?>"
                        title="<?= /* @noEscape */ $block->escapeHtml(__('View Profile')); ?>"
                        target="_blank" rel="noopener" class="store-front">
                        <?= /* @noEscape */ __('View Profile'); ?>
                    </a>
                </li>
                <li class="wk-mp-dropdown-menu-logout">
                    <a
                        href="<?= /* @noEscape */ $block->getUrl('customer/account/logout') ?>"
                        class="wk-mp-account-logout"
                        title="<?= /* @noEscape */ $block->escapeHtml(__('Logout')) ?>">
                        <?= /* @noEscape */ __('Logout') ?>
                    </a>
                </li>
            </ul>
        </div>
        <?php
              break;
    case 'seller.notifications':
        ?>
        <?php $totalCount = $block->getAllNotificationCount(); ?>
        <div class="wk-mp-notification wk-mp__action-dropdown-wrap">
            <a 
                onlick="return false;"
                href="#" 
                class="wk-mp__action-dropdown"
            <?php if ($totalCount): ?> data-mage-init='{"dropdown":{}}' <?php endif; ?> >
                <span class="wk-mp-notification-icon"></span>
            <?php if ($totalCount): ?>
                    <?php if ($totalCount > 5): ?>
                        <span class="wk-mp-notification-count">5+</span>
                    <?php else: ?>
                        <span class="wk-mp-notification-count">
                            <?= /* @noEscape */ $totalCount; ?>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>
            </a>
        <?php if ($totalCount): ?>
                <ul class="wk-mp__action-dropdown-menu">
                    <?php foreach ($block->getAllNotification() as $notification) { ?>
                        <?= /* @noEscape */ $block->getNotificationInfo($notification);?>
                        <?php
                    } ?>
                    <li>
                        <small>
                            <a href="<?= /* @noEscape */ $block->getUrl('marketplace/account/notification')?>">
                                <?= /* @noEscape */ __("View All")?>
                            </a>
                        </small>
                    </li>
                </ul>
            <?php endif; ?>
        </div>
        <?php
              break;
    case 'seller.home':
        ?>
        <div class="wk-mp-home wk-mp__action-dropdown-wrap">
            <a 
                href="<?= /* @noEscape */ $block->getUrl('')?>" 
                class="wk-mp__action-dropdown">
            </a>
        </div>
        <?php
              break;
    case 'other':
        ?>
        <?= /* @noEscape */ $block->getChildHtml(); ?>
        <?php
              break; ?>
<?php endswitch; ?>
