<?php

/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<form class="form quickrfq" action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>" id="quickrfq_form" enctype="multipart/form-data" method="post" onsubmit="return myFunction2()" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>


    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Al Meezan Registration Form') ?></span></legend><br />
        <div class="field name">
            <div class="control">
                <input id="company" value="" class="input-text" type="text" placeholder="9851" disabled />
            </div>
        </div>
        <div class="field contact_name required">
            <!--<label class="label" for="contact_name"><span><?php /* @escapeNotVerified */ //echo __('Full Name AS Per CNIC') 
                                                                ?></span></label>-->
            <div class="control">
                <input name="contact_name" id="contact_name" title="<?php /* @escapeNotVerified */ echo __('Full Name AS Per CNIC') ?>" placeholder="Full Name AS Per CNIC" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}" />
            </div>
        </div>
        <div class="field phone">
            <!--<label class="label" for="phone"><span><?php /* @escapeNotVerified */ //echo __('Mobile Number') 
                                                        ?></span></label>-->
            <div class="control">
                <input name="phone" data-inputmask="'mask': '0399-99999999'" maxlength="12" id="phone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="" class="input-text" placeholder="Mobile" type="text" data-validate="{required:true}" />
            </div>
        </div>
        <!-- <div class="field name required">
                <label class="label" for="company"><?php //echo __('Company Name:') 
                                                    ?></label>
                <div class="control">
                        <input name="company" id="company" value="" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
	    </div> -->

        <div class="field email required">
            <!--<label class="label" for="email"><span><?php /* @escapeNotVerified */ //echo __('Email') 
                                                        ?></span></label> -->
            <div class="control">
                <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" placeholder="Email" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}" />
            </div>
        </div>

        <div class="field project_title required">
            <!-- <label class="label" for="project_title"><span><?php /* @escapeNotVerified */ //echo __('Project Title') 
                                                                ?></span></label> -->
            <div class="control">
                <input name="project_title" data-inputmask="'mask': '99999-9999999-9'" id="project_title" title="<?php /* @escapeNotVerified */ echo __('CNIC Number') ?>" value="" class="input-text" type="text" placeholder="CNIC" />
            </div>
        </div>
        <!--<div class="field date">
            <label class="label" for="date"><span><?php /* @escapeNotVerified */ //echo __('Quote Needed By') 
                                                    ?></span></label>
            <div class="control">
                <input name="date" id="date" title="<?php /* @escapeNotVerified */ //echo __('Quote Needed By') 
                                                    ?>" value="" class="hasDatepicker" type="text" />
                
            </div>
        </div>-->

        <?php //$_date = $block->getLayout()->createBlock('FME\Quickrfq\Block\Widget\DateQuote') 
        ?>
        <?php //if ($_date->isEnabled()): 
        ?>
        <?php //echo $_date->toHtml() 
        ?>
        <?php //endif 
        ?>

        <!--<div class="field budget">
			    <label for="budget"><?php //echo __('Project Budget Status') 
                                    ?></label>
			    <div class="input-box">
			       <input name="budget" value="Approved" checked="checked" type="radio"><?php //echo __('Approved') 
                                                                                        ?>
			       <input name="budget" value="Approval Pending" type="radio"><?php //echo __('Approval Pending') 
                                                                                ?>
			       <input name="budget" value="Open" type="radio"><?php //echo __('Open') 
                                                                    ?>
			       <input name="budget" value="No Approval" type="radio"><?php //echo __('No Approval') 
                                                                            ?>
			    </div>
        </div>
        -->
        <!--
        <div class="field overview required">
            <label class="label" for="overview"><span><?php /* @escapeNotVerified */ //echo __('Brief Overview') 
                                                        ?></span></label>
            <div class="control">
                <textarea name="overview" id="overview" title="<?php /* @escapeNotVerified */ //echo __('Brief Overview') 
                                                                ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div> -->


        <!--
        <div class="field prd">
			    <label for="prd"><?php //echo __('Upload Document:') 
                                    ?></label>
			    <div class="input-box">
				<input type="file" id="prd" name="prd">
				<br>
				  <p> <?php //echo __("You can upload files with these file extensions only (%1)", $block->getAllowedFileExtensions()) 
                        ?> </p>
			    </div>
        </div>
        -->
        <div class="field">
            <?php if ($block->isCaptchaEnable()) : ?>
                <div class="g-recaptcha" name="recaptcha" id="recaptcha" data-sitekey="<?php echo $block->getPublicKey(); ?>"></div>
                <div>
                    <p style="
                        cursor: auto;
                        /* text-decoration: underline; */
                        color: #9b9b9b;
                        padding-left: 235px;
                        font-family: Roboto,helvetica,arial,sans-serif;
                        font-size: 8px;
                        font-weight: 400;
                        margin-top: -35px;">
                    </p>
                </div>
                <br>
            <?php endif; ?>
        </div>
        <?php echo $block->getChildHtml('form.additional.info'); ?>

	<p></p>
            <label class="label" for="company"><?php echo __('<p>In the Next Section:</p>Don\'t forget to select the option "TEAM MEMBER OF ALMEEZAN" and paste the <b>Sales Code (9851)</b> in the designated field name "Where do you hear about us?". If you don\'t follow these instructions, your entry won\'t be considered valid.'); //echo __('Please select the "TEAM MEMBER OF ALMEEZAN" option and input the sales code in the designated form field <b>"Where do you hear about us?"</b> as showing in the above screenshot. If you don\'t follow these instructions, your entry won\'t be considered valid.') ?></label>
            
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                <span><?php /* @escapeNotVerified */ echo __('Next') ?></span>
            </button>
        </div>
         <p></p>
    </div>
</form>

<script type="text/javascript">
//    $(":input").inputmask();
  //  alert();
    function myFunction2() {
        var exists = document.getElementById("g-recaptcha-response");

        if (exists == null) {

        } else {

            var check = document.getElementById("g-recaptcha-response").value;
            // alert(check);
            if (check == '' || check == null) {
                document.getElementById("recaptcha").style.border = "1px solid #ea0e0e";
                return false;
            } else {
                document.getElementById("recaptcha").style.border = "none";
                return true;
            }
        }


    }
</script>


<style type="text/css">
    #recaptcha {
        display: inline-block;
        position: relative;


    }
</style>
