<?php
/**
* Copyright © 2015 Magento. All rights reserved.
* See COPYING.txt for license details.
*/

// @codingStandardsIgnoreFile

?>

<legend class = 'legend'>
    <h2 style="text-align:center">
        <span>
            
                <?php /* @escapeNotVerified */ echo __( 'Health Takaful Form' ) ?>
            
        </span>
    </h2>
</legend><br />
<form class = 'form quickrfq pasha'
action = "<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
id = 'quickrfq_form'
enctype = 'multipart/form-data'
method = 'post'
onsubmit = 'return myFunction2()'
data-hasrequired = "<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
data-mage-init = '{"validation":{}}'>
<div class="container">
<div class='row'>
<div class="col-12 col-md-6 col-lg-6 col-xl-6 col-sm-6">
<fieldset class = 'fieldset'>

    
    <div class = 'field name required'>
<label class = 'label' for = 'company'><?php echo __( 'Company Name:' ) ?></label>
<div class = 'control'>
<input name = 'company' id = 'company' value = '' class = 'input-text' type = 'text' data-validate = '{required:true}'/>
</div>
</div>
<div class = 'field contact_name required'>
<label class = 'label' for = 'contact_name'><span><?php /* @escapeNotVerified */ echo __( 'Contact Name' ) ?></span></label>
<div class = 'control'>
<input name = 'contact_name' id = 'contact_name' title = "<?php /* @escapeNotVerified */ echo __('Contact Name') ?>" value = "<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class = 'input-text' type = 'text' data-validate = '{required:true}'/>
</div>
</div>
</fieldset>
</div>

<div class="col-12 col-md-6 col-lg-6 col-xl-6 col-sm-6">
<fieldset class = 'fieldset'>

<div class = 'field email required'>
<label class = 'label' for = 'email'><span><?php /* @escapeNotVerified */ echo __( 'Email' ) ?></span></label>
<div class = 'control'>
<input name = 'email' id = 'email' title = "<?php /* @escapeNotVerified */ echo __('Email') ?>" value = "<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class = 'input-text' type = 'email' data-validate = "{required:true, 'validate-email':true}"/>
</div>
</div>
<div class = 'field phone'>
<label class = 'label' for = 'phone'><span><?php /* @escapeNotVerified */ echo __( 'Phone Number' ) ?></span></label>
<div class = 'control'>
<input name = 'phone' id = 'phone' title = "<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value = '' class = 'input-text' type = 'text' />
</div>
</div>
</fieldset>
</div>

<div class="col-12 col-md-12 col-lg-12 col-xl-12 col-sm-12">
<fieldset>
<div class = 'field project_title'>
<label class = 'label' for = 'project_title'><span><?php /* @escapeNotVerified */ echo __( 'Designation' ) ?></span></label>
<div class = 'control'>
<input name = 'project_title' id = 'project_title' title = "<?php /* @escapeNotVerified */ echo __('Designation') ?>" value = '' class = 'input-text' type = 'text' />
</div>
</div>
<!--<div class = 'field date'>
<label class = 'label' for = 'date'><span><?php /* @escapeNotVerified */ //echo __( 'Quote Needed By' ) ?></span></label>
<div class = 'control'>
<input name = 'date' id = 'date' title = "<?php /* @escapeNotVerified */ //echo __('Quote Needed By') ?>" value = '' class = 'hasDatepicker' type = 'text' />

</div>
</div>-->

<?php //$_date = $block->getLayout()->createBlock( 'FME\Takaful\Block\Widget\DateQuote' ) ?>
<?php //if ( $_date->isEnabled() ): ?>
<?php //echo $_date->toHtml() ?>
<?php //endif ?>

<div class = 'field budget'>
<label for = 'budget'><?php echo __( 'Already Insured*' ) ?></label>
<div class = 'input-box'>
<!-- <input name = 'budget' value = 'Approved' checked = 'checked' type = 'radio'><?php //echo __( 'Approved' ) ?>
<input name = 'budget' value = 'Approval Pending' type = 'radio'><?php //echo __( 'Approval Pending' ) ?> -->
<div class="input-box">
<input name = 'budget' value ='No' checked ='checked' type = 'radio'>&nbsp;<label><?php echo __( 'No' ) ?></label>&nbsp;&nbsp;
<input name = 'budget' value ='Yes' type ='radio'>&nbsp;<label><?php echo __( 'Yes' ) ?></label>
<!-- <input name = 'budget' value = 'Approved' checked = 'checked' type = 'radio'>
<input name = 'budget' value = 'Approval Pending' type = 'radio'> 
<input name="budget" value="Yes" type="radio">&nbsp;<label>Yes</label>&nbsp;&nbsp;
<input name="budget" value="No" type="radio">&nbsp;<label>No</label>-->
</div>
</div>
</div>

<!--
<div class = 'field overview required'>
<label class = 'label' for = 'overview'><span><?php /* @escapeNotVerified */ echo __( 'Brief Overview' ) ?></span></label>
<div class = 'control'>
<textarea name = 'overview' id = 'overview' title = "<?php /* @escapeNotVerified */ echo __('Brief Overview') ?>" class = 'input-text' cols = '5' rows = '3' data-validate = '{required:true}'></textarea>
</div>
</div>

<div class = 'field prd'>
<label for = 'prd'><?php //echo __( 'Upload Document:' ) ?></label>
<div class = 'input-box'>
<input type = 'file' id = 'prd' name = 'prd'>
<br>
<p> <?php //echo __( 'You can upload files with these file extensions only (%1)', $block->getAllowedFileExtensions() ) ?> </p>
</div>
</div>
-->

<div class = 'field'>

<?php if ( $block->isCaptchaEnable() ): ?>
<div class = 'g-recaptcha'  name = 'recaptcha' id = 'recaptcha' data-sitekey = "<?php echo $block->getPublicKey(); ?>"></div>
<div ><p style = "
    cursor: auto;
    /* text-decoration: underline; */
    color: #9b9b9b;
    padding-left: 235px;
    font-family: Roboto,helvetica,arial,sans-serif;
    font-size: 8px;
    font-weight: 400;
    margin-top: -35px;
">by <a style = 'color: #9b9b9b;' rel = 'no-follow' target = '_Blank' href = 'https://www.fmeextensions.com/request-for-quote-magento-2.html'>Fmeextensions</a></p>  </div>
<br>

<?php endif;
?>
</div>

<?php echo $block->getChildHtml( 'form.additional.info' );
?>
</fieldset>
</div>
</div>
<div class = 'actions-toolbar'>
<div class = 'primary'>
<input type = 'hidden' name = 'hideit' id = 'hideit' value = '' />
<button type = 'submit' title = "<?php /* @escapeNotVerified */ echo __('Submit') ?>" class = 'action submit primary'>
<span><?php /* @escapeNotVerified */ echo __( 'Submit' ) ?></span>
</button>
</div>
</div>
</div>
</form>

<script type = 'text/javascript'>

function myFunction2() {
    var exists = document.getElementById( 'g-recaptcha-response' );

    if ( exists == null ) {

    } else {

        var check = document.getElementById( 'g-recaptcha-response' ).value;
        // alert( check );
        if ( check == '' || check == null ) {
            document.getElementById( 'recaptcha' ).style.border = '1px solid #ea0e0e';
            return false;
        } else {
            document.getElementById( 'recaptcha' ).style.border = 'none';
            return true;
        }
    }

}
</script>

<style type = 'text/css'>

#recaptcha {
    display: inline-block;
    position: relative;

}

</style>