<?php

/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_menu = $block->getHtml(-1, 'level-top', 'submenu'); ?>
<div class="mb-navigation vertical-menu d-none  ">

    <div class="title custom-menu-dropdownn"><img alt="imarkplace" src="/media/wysiwyg/menu.svg"><span class="mbi mbi-menuu"></span><span class="d-none d-md-block custom-menu-dropdown-icons"><?= __("Shop all categories") ?>
            <i class="mbi mbi-ios-arrow-down"></i></span></div>
    <div class="navigation" data-action="navigation">
        <ul class="term-list smartmenu magebig-nav prepnt_cat">
            
            <?= /* @escapeNotVerified */ $_menu; ?>
            <?= /* @escapeNotVerified */ $block->getChildHtml(); ?>
        </ul>
        <?php
            echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('c_custom_menu')
            ->toHtml();
        ?>
    </div>
</div>