<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$helper = $this->helper(\Webkul\Marketplace\Helper\Data::class);
$product = $block->getProduct();
$sellerId = '';
$marketplaceProduct = $helper->getSellerProductDataByProductId($product['entity_id']);
foreach ($marketplaceProduct as $value) {
    $sellerId = $value['seller_id'];
}
$flagReasons = $block->getProductFlagReasons();
$cardType = $helper->getDisplayCardType();
?>
<?php if ($sellerId!=""): ?>
    <?php
        $analyticStatus = $helper->getAnalyticStatus();
        if ($analyticStatus) {
            $analyticId = $helper->getSellerAnalyticId($sellerId);
        }
        $captchenable = $helper->getCaptchaEnable();
        $sellerInfo = $helper->getSellerInfo($sellerId);
        $shopTitle = $sellerInfo['shop_title'];
        $shopUrl = $sellerInfo['shop_url'];
        $logo = $sellerInfo['logo_pic'];
        $productCount = $sellerInfo['product_count'];
        $companyLocality = trim($sellerInfo['company_locality']);
        $companyLocality = $escaper->escapeHtml($companyLocality);
    if (!$shopTitle) {
        $shopTitle = $shopUrl;
    }

    if ($productCount > 1) {
        $productLabel = __("%1 Products", $productCount);
    } else {
        $productLabel = __("%1 Product", $productCount);
    }

    if ($logo == "") {
        $logo = "noimage.png";
    }

        $logo = $helper->getMediaUrl().'avatar/'.$logo;
        $shopTitle = $escaper->escapeHtml($shopTitle);
        $feeds = $helper->getFeedTotal($sellerId);
        $rating = $helper->getSelleRating($sellerId);
        $collectionPageUrl = $helper->getRewriteUrl('marketplace/seller/collection/shop/'.$shopUrl);
        $profilePageUrl = $helper->getRewriteUrl('marketplace/seller/profile/shop/'.$shopUrl);
    ?>
    <div class="wk-seller-block wk-block no-display" id="mp-wk-block">
        <div class="wk-seller-card-container wk-card-type<?= $escaper->escapeHtml($cardType); ?>">
            <?php if ($cardType == 2): ?>
                <div class="wk-seller-card-details-block">
                    <div class="wk-seller-card-details-img-block">
                        <a href="<?= $escaper->escapeUrl($profilePageUrl); ?>" title="<?= $escaper->escapeHtml(__('Visit Shop')) ?>" target="_blank" rel="noopener">
                            <img alt="imarkplace" src="<?= $escaper->escapeUrl($logo); ?>">
                        </a>
                    </div>
                    <div class="wk-seller-card-details-content-block">
                        <div class="wk-seller-card-row">
                            <div class="wk-seller-shop-title">
                                <a href="<?= $escaper->escapeUrl($profilePageUrl); ?>" title="<?= $escaper->escapeHtml(__('Visit Shop')) ?>" id="profileconnect" target="_blank" rel="noopener">
                                    <?= $escaper->escapeHtml($shopTitle); ?>
                                </a>
                            </div>
                            <?php if ($rating > 0):?>
                                <div class="wk-seller-rating-block">
                                    <div class="wk-seller-rating-number">
                                        <?= $escaper->escapeHtml(number_format($rating, 1)); ?>
                                    </div>
                                    <div class="wk-seller-rating-summery">
                                        <div class="wk-seller-rating wk-mp-design-inner">
                                            <div class="wk-seller-feedback-title">
                                                <span>
                                                    <?php
                                                    $review_percentage = (($rating*100)/5);
                                                    /* @noEscape */ echo $review_percentage."% ".__('positive feedback')." (".__('%1 ratings', number_format($feeds['feedcount'])).") ";
                                                    ?>
                                                </span>
                                            </div>
                                            <div class="wk-mp-row">
                                                <div class="mpfeedback">
                                                    <div class="price">
                                                        <span class="wk-ordertitle-label"><?= $escaper->escapeHtml(__('Price')) ?> </span><span>:</span>
                                                        <div class="ratingslider-box">
                                                            <div class="rating" style="width:<?= $escaper->escapeHtml(ceil($feeds['price']));?>%;"></div>
                                                        </div>
                                                        <span>&nbsp;(<?= $escaper->escapeHtml(round(($feeds['price']/20), 1, PHP_ROUND_HALF_UP)) ?>/5)</span>
                                                        <div class="clear"></div>
                                                    </div>
                                                    <div class="value">
                                                        <span class="wk-ordertitle-label"><?= $escaper->escapeHtml(__('Value')) ?> </span><span>:</span>
                                                        <div class="ratingslider-box" >
                                                            <div class="rating" style="width:<?= $escaper->escapeHtml(ceil($feeds['value']));?>%;"></div>
                                                        </div>
                                                        <span>&nbsp;(<?= $escaper->escapeHtml(round(($feeds['value']/20), 1, PHP_ROUND_HALF_UP))?>/5)</span>
                                                        <div class="clear"></div>
                                                    </div>
                                                    <div class="quality">
                                                        <span class="wk-ordertitle-label"><?= $escaper->escapeHtml(__('Quality')) ?> </span><span>:</span>
                                                        <div class="ratingslider-box">
                                                            <div class="rating" style="width:<?= $escaper->escapeHtml(ceil($feeds['quality']));?>%;"></div>
                                                        </div>
                                                        <span>&nbsp;(<?= $escaper->escapeHtml(round(($feeds['quality']/20), 1, PHP_ROUND_HALF_UP))?>/5)</span>
                                                        <div class="wk-clear"></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </div>
                        <?php if ($companyLocality != ""): ?>
                            <div class="wk-seller-card-row">
                                <a class="wk-seller-location-link" title="<?= $escaper->escapeHtml(__($companyLocality)); ?>" href="<?= $escaper->escapeUrl($helper->getRewriteUrl('marketplace/seller/location/shop/'.$shopUrl)."?loc=".$companyLocality)?>" target="_blank" rel="noopener">
                                    <?= $escaper->escapeHtml(__($companyLocality)); ?>
                                </a>
                            </div>
                        <?php endif; ?>

                        <div class="wk-seller-card-row">
                            <span class="wk-ask-question-link"><a id="askque1" style="cursor:pointer;"><?= $escaper->escapeHtml(__('Contact Seller')) ?></a></span>
                            <?= $block->getChildHtml();?>
                        </div>
                        <?php if ($helper->getProductFlagStatus() && (
                          ($flagReasons->getSize() && $helper->getProductFlagData('reason')) || $helper->getProductFlagData('other_reason'))
                          ): ?>
                          <div class="wk-seller-card-row">
                              <span class="wk-report-flag-link"><a id="reportflag"><?= $helper->getProductFlagData('product_flag_label') ?></a></span>
                          </div>
                        <?php endif; ?>

                    </div>
                </div>
                <div class="wk-seller-card-product-block">
                    <?php if ($productCount > 0): ?>
                        <div class="wk-seller-card-product-container">
                            <?php $collection = $helper->getSellerProductCollection($sellerId, $product['entity_id'], $productCount); ?>
                            <?php foreach ($collection as $_product): ?>
                                <div class="wk-seller-card-product">
                                    <a href="<?= $escaper->escapeUrl($_product->getProductUrl()); ?>" target="_blank" rel="noopener" title="<?= $escaper->escapeHtml($_product->getName()); ?>">
                                        <img alt="imarkplace" src="<?= $escaper->escapeUrl($helper->getImageUrl($_product)); ?>">
                                    </a>
                                </div>
                            <?php endforeach; ?>
                            <?php if ($productCount > 5): ?>
                                <div class="wk-seller-card-product">
                                    <a href="<?= $escaper->escapeUrl($collectionPageUrl); ?>" target="_blank" rel="noopener">
                                        <span><?= $escaper->escapeHtml(__("View All %1 Products", $productCount)); ?></span>
                                    </a>
                                </div>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>
                </div>
            <?php else: ?>
                <div class="wk-seller-card-row">
                    <span class="wk-block-font-bold-up"><?= $escaper->escapeHtml(__('Sold By'))?></span>
                </div>
                <div class="wk-seller-card-row">
                    <span class="wk-block-title-css">
                        <a href="<?= $escaper->escapeUrl($profilePageUrl); ?>" title="<?= $escaper->escapeHtml(__('Visit Shop')) ?>" id="profileconnect" target="_blank" rel="noopener">
                            <?= $escaper->escapeHtml($shopTitle); ?>
                        </a>
                    </span>
                </div>
                <?php if ($companyLocality != ""): ?>
                    <div class="wk-seller-card-row">
                        <a class="wk-seller-location-link" title="<?= $escaper->escapeHtml(__($companyLocality)); ?>" href="<?= $escaper->escapeUrl($helper->getRewriteUrl('marketplace/seller/location/shop/'.$shopUrl)."?loc=".$companyLocality)?>" target="_blank" rel="noopener">
                            <?= $escaper->escapeHtml(__($companyLocality)); ?>
                        </a>
                    </div>
                <?php endif; ?>
                <div class="wk-seller-card-row">
                    <?php if ($rating > 0):?>
                        <div class="wk-seller-card-col">
                            <div class="wk-seller-rating-block">
                                <div class="wk-seller-rating-number">
                                    <?= $escaper->escapeHtml(number_format($rating, 1)); ?>
                                </div>
                                <div class="wk-seller-rating-summery">
                                    <div class="wk-seller-rating wk-mp-design-inner">
                                        <div class="wk-seller-feedback-title">
                                            <span>
                                                <?php
                                                $review_percentage = (($rating*100)/5);
                                                /* @noEscape */ echo $review_percentage."% ".__('positive feedback')." (".__('%1 ratings', number_format($feeds['feedcount'])).") ";
                                                ?>
                                            </span>
                                        </div>
                                        <div class="wk-mp-row">
                                            <div class="mpfeedback">
                                                <div class="price">
                                                    <span class="wk-ordertitle-label"><?= $escaper->escapeHtml(__('Price')) ?> </span><span>:</span>
                                                    <div class="ratingslider-box">
                                                        <div class="rating" style="width:<?= $escaper->escapeHtml(ceil($feeds['price']));?>%;"></div>
                                                    </div>
                                                    <span>&nbsp;(<?= $escaper->escapeHtml(round(($feeds['price']/20), 1, PHP_ROUND_HALF_UP)) ?>/5)</span>
                                                    <div class="clear"></div>
                                                </div>
                                                <div class="value">
                                                    <span class="wk-ordertitle-label"><?= $escaper->escapeHtml(__('Value')) ?> </span><span>:</span>
                                                    <div class="ratingslider-box" >
                                                        <div class="rating" style="width:<?= $escaper->escapeHtml(ceil($feeds['value']));?>%;"></div>
                                                    </div>
                                                    <span>&nbsp;(<?= $escaper->escapeHtml(round(($feeds['value']/20), 1, PHP_ROUND_HALF_UP))?>/5)</span>
                                                    <div class="clear"></div>
                                                </div>
                                                <div class="quality">
                                                    <span class="wk-ordertitle-label"><?= $escaper->escapeHtml(__('Quality')) ?> </span><span>:</span>
                                                    <div class="ratingslider-box">
                                                        <div class="rating" style="width:<?= $escaper->escapeHtml(ceil($feeds['quality']));?>%;"></div>
                                                    </div>
                                                    <span>&nbsp;(<?= $escaper->escapeHtml(round(($feeds['quality']/20), 1, PHP_ROUND_HALF_UP))?>/5)</span>
                                                    <div class="wk-clear"></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="wk-seller-card-col">
                        <a class="wk-seller-product-count" href="<?= $escaper->escapeUrl($collectionPageUrl); ?>" target="_blank" rel="noopener">
                            <?= $escaper->escapeHtml($productLabel); ?>
                        </a>
                    </div>
                </div>

                <div class="wk-seller-card-row">
                    <span class="wk-ask-question-link"><a id="askque1" style="cursor:pointer;"><?= $escaper->escapeHtml(__('Contact Seller')) ?></a></span>
                    <?= $block->getChildHtml();?>
                </div>
                <?php if ($helper->getProductFlagStatus() && (
                  ($flagReasons->getSize() && $helper->getProductFlagData('reason')) || $helper->getProductFlagData('other_reason'))
                  ): ?>
                  <div class="wk-seller-card-row">
                      <span class="wk-report-flag-link"><a id="reportflag"><?= $helper->getProductFlagData('product_flag_label') ?></a></span>
                  </div>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>
    <div class="ask-que1">
        <div id="wk-mp-ask-data" style="display:none;">
            <div class="wk-mp-modals-wrapper">
                <aside tabindex="0" data-type="popup" data-role="modal" class="modal-popup modal-slide _inner-scroll wk-mp-model-popup">
                    <div tabindex="0" data-role="focusable-start"></div>
                    <div data-role="focusable-scope" class="modal-inner-wrap">
                        <header class="modal-header">
                            <h4 class="modal-title"><?= $escaper->escapeHtml(__('Contact Seller')) ?></h4>
                            <button type="button" data-role="closeBtn" class="action-close wk-close">
                                <span>Close</span>
                            </button>
                            <span  class="wk-clear" ></span>
                        </header>
                        <?php
                        if ($helper->isCustomerLoggedIn()) {
                            $readonly = "readonly='readonly'";
                            $customer = $helper->getCustomerData();
                            $buyerName = $customer->getName();
                                $buyerEmail = $customer->getEmail();
                        } else {
                            $readonly = '';
                            $buyerName = '';
                            $buyerEmail = '';
                        }
                        ?>
                        <form id="ask-form" method="post" action="#" class="fieldset">
                            <div class="modal-body form-list field required">
                                <label class="label"><?= $escaper->escapeHtml(__('Your Name')) ?> :</label>
                                <input type="text" name="name" class="queryemail wk-contact_input_fields required-entry" value="<?= $escaper->escapeHtml($buyerName)?>" <?= /* @noEscape */ $readonly?>/>
                                <label class="label"><?= $escaper->escapeHtml(__('Your Email')) ?> :</label>
                                <input type="text" name="email" class="queryemail required-entry validate-email wk-contact_input_fields" value="<?= $escaper->escapeHtml($buyerEmail)?>" <?= /* @noEscape */ $readonly?>/>
                                <label class="label"><?= $escaper->escapeHtml(__('Subject')) ?> :</label>
                                <input type="text" name="subject" class="wk-contact_input_fields required-entry"/>
                                <label class="label"><?= $escaper->escapeHtml(__('Your Query')) ?> :</label>
                                <textarea  name="ask" class="wk-full-width queryquestion wk-contact_input_fields required-entry"></textarea>
                                <input type="hidden" name="seller-id" value="<?= $escaper->escapeHtml($sellerId);?>"/>
                                <input type="hidden" name="product-id" value="<?= $escaper->escapeHtml($product['entity_id']);?>" />
                                <?php
                                if ($captchenable) {?>
                                    <label class="label"><?= $escaper->escapeHtml(__('Please enter desired result')) ?></label>
                                    <div>
                                        <span>
                                            <label for="wk-mp-captcha"><span id="wk-mp-captchalable1"><?= $escaper->escapeHtml(rand(1, 20))?></span> + <span id="wk-mp-captchalable2"><?= $escaper->escapeHtml(rand(1, 20))?></span> =</label>
                                        </span>
                                        <input type="text" class="required-entry wk-contact_input_fields" name="wk-mp-captcha" id="wk-mp-captcha" />
                                    </div>
                                    <?php
                                }?>
                            </div>
                            <div class="modal-footer">
                                <span class="error"></span>
                                <span class="errormail"></span>
                                <input type="reset" value="<?= $escaper->escapeHtml(__('Reset')) ?>" id="resetbtn" class="wk-btn wk-btn_default"/>
                                <input type="submit" value="<?= $escaper->escapeHtml(__('Submit')) ?>" id="askbtn" class="wk-btn wk-btn-primary clickask"/>
                                <span class="wk-clear"></span>
                            </div>
                        </form>
                    </div>
                    <div tabindex="0" data-role="focusable-end"></div>
                </aside>
            </div>
        </div>
    </div>
    <?php if ($helper->getProductFlagStatus()): ?>
      <div class="product-flag">
          <div id="wk-mp-flag-data">
              <div class="wk-mp-modals-wrapper">
                  <aside tabindex="0" data-type="popup" data-role="modal" class="modal-popup modal-slide _inner-scroll wk-mp-model-flag-popup">
                      <div tabindex="0" data-role="focusable-start"></div>
                      <div data-role="focusable-scope" class="modal-inner-wrap">
                          <header class="modal-header">
                              <h4 class="modal-title"><?= $helper->getProductFlagData('product_flag_label') ?></h4>
                              <button type="button" data-role="closeBtn" class="action-close wk-product-flag-close">
                                  <span><? __('Close')?></span>
                              </button>
                              <span class="wk-product-flag-clear"></span>
                          </header>
                          <?php
                            if ($helper->isCustomerLoggedIn()) {
                                $readonly = "readonly='readonly'";
                                $customer = $helper->getCustomerData();
                                $reporterName = $customer->getName();
                                $reporterEmail = $customer->getEmail();
                            } else {
                                $readonly = '';
                                $reporterName = '';
                                $reporterEmail = '';
                            }
                            ?>
                          <form id="flag-form" method="post" action="#" class="fieldset">
                              <div class="modal-body form-list field wk-flag-form required">
                                  <label class="label"><?= $escaper->escapeHtml(__('Your Name')) ?> :</label>
                                  <input type="text" name="name" class="queryemail wk-contact_input_fields required-entry" value="<?= $escaper->escapeHtml($reporterName)?>" <?= /* @noEscape */ $readonly?>/>
                                  <label class="label"><?= $escaper->escapeHtml(__('Your Email')) ?> :</label>
                                  <input type="text" name="email" class="queryemail required-entry validate-email wk-contact_input_fields" value="<?= $escaper->escapeHtml($reporterEmail)?>" <?= /* @noEscape */ $readonly?>/>
                                  <?php if ($helper->getProductFlagData('reason')):
                                        ?>
                                    <label class="label"><?= $escaper->escapeHtml(__('Choose an appropriate reason to flag')) ?> :</label>
                                        <?php foreach ($flagReasons as $flagReason): ?>
                                      <div class="wk-flagreasons">
                                        <input type="radio" name="reason" id="<?= $flagReason->getId() ?>" class="flag-reason required-entry" value="<?= $flagReason->getReason()?>" >
                                        <label for="<?= $flagReason->getId() ?>"><?= $flagReason->getReason() ?></label>
                                      </div>
                                    <?php endforeach; ?>
                                        <?php if ($helper->getProductFlagData('other_reason')): ?>
                                      <div class="wk-flagreasons">
                                        <input type="radio" name="reason" id="reason_other" class="flag-reason required-entry" value="other_value" checked>
                                        <label for="reason_other"><?= $helper->getProductFlagData('other_reason_label') ?></label>
                                      </div>
                                      <textarea name="flag_other_reason" placeholder="Write a reason to flag this product" class="wk-full-width wk-flag-other-reason required-entry"></textarea>
                                    <?php endif; ?>
                                    <?php endif; ?>
                                  <input type="hidden" name="seller_id" value="<?= $escaper->escapeHtml($sellerId);?>"/>
                                  <input type="hidden" name="product_id" value="<?= $escaper->escapeHtml($product['entity_id']);?>" />
                                  <input type="hidden" name="product_name" value="<?= $escaper->escapeHtml($product->getName());?>" />
                              </div>
                              <div class="modal-footer">
                                  <span class="error"></span>
                                  <span class="errormail"></span>
                                  <input type="reset" value="<?= $escaper->escapeHtml(__('Reset')) ?>" id="resetflagbtn" class="wk-btn wk-btn-product-flag_default"/>
                                  <input type="submit" value="<?= $escaper->escapeHtml(__('Submit')) ?>" id="flagbtn" class="wk-btn wk-btn-product-flag-primary clickflag"/>
                                  <span class="wk-product-flag-clear"></span>
                              </div>
                          </form>
                      </div>
                      <div tabindex="0" data-role="focusable-end"></div>
                  </aside>
              </div>
          </div>
      </div>
      <div class="wk-alert-modal-content">
        <div class="wk-flag-status-content">
          <p><?= $escaper->escapeHtml(__('Thank you.'))?></p>
          <p><?= $escaper->escapeHtml(__('Your report against '))?><b><?= $escaper->escapeHtml($product->getName())?></b><?= $escaper->escapeHtml(__(' has been submitted.'))?></p>
          <p><?= $escaper->escapeHtml(__('We will re-verify the product Information and see if it violates any of our policy or selling guidelines.'))?></p>
        </div>
      </div>
    <?php endif;?>
    <script>
        require([
            "jquery",
            "Magento_Ui/js/modal/alert",
            "mage/mage"
        ], function($, alert) {
            var askDataForm = $('#ask-form');
            var cardType = <?= $escaper->escapeHtml($cardType); ?>;

            askDataForm.mage('validation', {});
            var flagDataForm = $('#flag-form');
            flagDataForm.mage('validation', {});
            if (cardType == 2) {
                $('.product-info-main').before($('#mp-wk-block'));
            } else {
                $('.product-info-main').append($('#mp-wk-block'));
            }
            $('#mp-wk-block').show();

            $('body').append($('#wk-mp-ask-data'));
            $('body').append($('#wk-mp-flag-data'));
            $(".wk-seller-rating-number" ).mouseover(function() {
                  $( ".wk-seller-rating" ).show();
            }).mouseout(function() {
                $( ".wk-seller-rating" ).hide();
              });

            $('#askque').click(function() {
                $('#ask-form input,#ask-form textarea').removeClass('mage-error');
                $('.page-wrapper').css('opacity','0.4');
                $('.wk-mp-model-popup').addClass('_show');
                //$('#wk-mp-ask-data').show();
                $('#wk-supplier-ask-data-b2b').show();
            });
            $('.wk-close-b2b').click(function() {
               
                $('#resetbtn').trigger('click');
                $('.page-wrapper').css('opacity','1');
                //$('#wk-mp-ask-data').hide();
                $('#wk-supplier-ask-data-b2b').hide();
                $('#ask-form .validation-failed').each(function() {
                    $(this).removeClass('validation-failed');
                });
                $('#ask-form .validation-advice').each(function() {
                    $(this).remove();
                });
            });

            $('#askque1').click(function() {
                $('#ask-form input,#ask-form textarea').removeClass('mage-error');
                $('.page-wrapper').css('opacity','0.2');
                $('.wk-mp-model-popup').addClass('_show');
                $('#wk-mp-ask-data').show();
            });
            $('.wk-close').click(function() {
                $('.page-wrapper').css('opacity','1');
                $('#resetbtn').trigger('click');
                $('#wk-mp-ask-data').hide();
                $('#ask-form .validation-failed').each(function() {
                    $(this).removeClass('validation-failed');
                });
                $('#ask-form .validation-advice').each(function() {
                    $(this).remove();
                });
            });

            $('#askbtn').click(function() {
                if (askDataForm.valid()!=false) {
                    var thisthis = $(this);
                    if (thisthis.hasClass("clickask")) {
                        <?php if ($captchenable) { ?>
                            var total = parseInt($('#wk-mp-captchalable1').text()) + parseInt($('#wk-mp-captchalable2').text());
                            var wk_mp_captcha = $('#wk-mp-captcha').val();
                            if (total != wk_mp_captcha) {
                                $('#wk-mp-captchalable1').text(Math.floor((Math.random()*10)+1));
                                $('#wk-mp-captchalable2').text(Math.floor((Math.random()*100)+1));
                                $('#wk-mp-captcha').val('');
                                $('#wk-mp-captcha').addClass('mage-error');
                                $(this).addClass('mage-error');
                                $('#ask_form .errormail').text("<?= $escaper->escapeHtml(__(' Wrong verification number. ')) ?>").slideDown('slow').delay(2000).slideUp('slow');
                            } else {
                                thisthis.removeClass('clickask');
                                $('#wk-mp-ask-data').addClass('mail-procss');
                                $.ajax({
                                    url:'<?= $escaper->escapeUrl($block->getUrl("marketplace/seller/sendmail", ["_secure" => $this->getRequest()->isSecure()])) ?>',
                                    data:$('#ask-form').serialize(),
                                    type:'post',
                                    dataType:'json',
                                    success:function(d) {
                                        thisthis.addClass('clickask');
                                        $('#wk-mp-ask-data').removeClass('mail-procss')
                                        alert({
                                            title: $.mage.__('Success Message'),
                                            content: $.mage.__('Your mail has been sent...'),
                                            actions: {
                                                always: function(){
                                                  $('.wk-close,#resetbtn').trigger('click');
                                                }
                                            },
                                            buttons: [{
                                                text: $.mage.__('Close'),
                                                class: 'action primary close',
                                                click: function () {
                                                    this.closeModal(true);
                                                }
                                            }]
                                        });
                                        $('.wk-close,#resetbtn').trigger('click');
                                    }
                                });
                            }
                        <?php } else { ?>
                            thisthis.removeClass('clickask');
                                $('#wk-mp-ask-data').addClass('mail-procss');
                                $.ajax({
                                    url:'<?= $escaper->escapeUrl($block->getUrl("marketplace/seller/sendmail", ["_secure" => $this->getRequest()->isSecure()])) ?>',
                                    data:$('#ask-form').serialize(),
                                    type:'post',
                                    dataType:'json',
                                    success:function(d) {
                                        thisthis.addClass('clickask');
                                        $('#wk-mp-ask-data').removeClass('mail-procss');
                                        alert({
                                            title: $.mage.__('Success Message'),
                                            content: $.mage.__('Your mail has been sent...'),
                                            actions: {
                                                always: function(){
                                                  $('.wk-close,#resetbtn').trigger('click');
                                                }
                                            },
                                            buttons: [{
                                                text: $.mage.__('Close'),
                                                class: 'action primary close',
                                                click: function () {
                                                    this.closeModal(true);
                                                }
                                            }]
                                        });
                                        $('.wk-close,#resetbtn').trigger('click');
                                    }
                                });
                            <?php
                        } ?>
                    }
                    return false;
                }
            });
            $('#reportflag').click(function() {
                $('#flag-form input,#flag-form textarea').removeClass('mage-error');
                $('.page-wrapper').css('opacity','0.4');
                $('.wk-mp-model-flag-popup').addClass('_show');
                $('#wk-mp-flag-data').show();
            });
            $('.wk-product-flag-close').click(function() {
                $('.page-wrapper').css('opacity','1');
                $('#resetflagbtn').trigger('click');
                $('#wk-mp-flag-data').hide();
                $('#flag-form .validation-failed').each(function() {
                    $(this).removeClass('validation-failed');
                });
                $('#flag-form .validation-advice').each(function() {
                    $(this).remove();
                });
            });
            $('.flag-reason').on('change',function(e) {
                if($(this).val() == "other_value") {
                $('.wk-flag-other-reason').show();
                $('.wk-flag-other-reason').addClass('required-entry');
              } else {
                $('.wk-flag-other-reason').hide();
                $('.wk-flag-other-reason').removeClass('required-entry');
              }
            });
            $('#resetflagbtn').on('click', function(e) {
              $('.wk-flag-other-reason').show();
              $('.wk-flag-other-reason').addClass('required-entry');
            });
            $('#flagbtn').click(function() {
                if (flagDataForm.valid()!=false) {
                    var thisthis = $(this);
                    if (thisthis.hasClass("clickflag")) {
                        thisthis.removeClass('clickflag');
                        $('#wk-mp-flag-data').addClass('mail-procss');
                        $.ajax({
                            url:'<?= $escaper->escapeUrl($block->getUrl("marketplace/product/reportflag", ["_secure" => $this->getRequest()->isSecure()])) ?>',
                            data:$('#flag-form').serialize(),
                            type:'post',
                            dataType:'json',
                            success:function(content) {
                                var messageContent = $('.wk-alert-modal-content').html();
                                thisthis.addClass('clickflag');
                                $('#wk-mp-flag-data').removeClass('mail-procss')
                                  alert({
                                      title: $.mage.__('Report Product'),
                                      content: $('.wk-flag-status-content'),
                                      actions: {
                                          always: function(){
                                            $('.wk-product-flag-close,#resetflagbtn').trigger('click');
                                            $('.wk-flag-other-reason').show();
                                            $('.wk-flag-other-reason').addClass('required-entry');
                                          }
                                      },
                                      buttons: [{
                                          text: $.mage.__('Close'),
                                          class: 'action primary close',
                                          click: function () {
                                              this.closeModal(true);
                                          }
                                      }]
                                  });
                                  $('.wk-alert-modal-content').append(messageContent);
                            }
                        });
                    }
                    return false;
                }
            });
        });
    </script>
    <?php if($analyticStatus && $analyticId) {?>
        <script>
            require([
                'jquery',
                'mage/cookies'
            ], function($) {
                var analyticId = "<?= $analyticId ?>";
                (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                    })(window,document,'script','https://www.google-analytics.com/analytics.js','wkga');

                    wkga('create', analyticId, {'name':'seller'});
                    wkga('seller.send', 'pageview');
            });
        </script>
    <?php }?>
<?php endif; ?>















<?php
$quickOrderBlock =  $block->getLayout()->createBlock(
    \Webkul\B2BMarketplace\Block\Supplier\Profile\QuickOrder::class
);
$helper = $quickOrderBlock->helper(\Webkul\Marketplace\Helper\Data::class);
$product = $block->getProduct();
$sellerId = '';
$marketplaceProduct = $helper->getSellerProductDataByProductId($product['entity_id']);
foreach ($marketplaceProduct as $value) {
    $sellerId = $value['seller_id'];
}
if ($sellerId!="") {
    $b2bHelper = $quickOrderBlock->helper('Webkul\B2BMarketplace\Helper\Data');
    $supplierInfo = $b2bHelper->getSupplierInfoById($sellerId);
    $captchenable = $helper->getCaptchaEnable();
    $rowsocial = $helper->getSellerDataBySellerId($sellerId);
    $shoptitle = '';
    $shopUrl = '';
    $defaultAddressId = '';
    $companyLocality = '';
    foreach ($rowsocial as $value) {
        $shoptitle = $value['shop_title'];
        $shopUrl = $value['shop_url'];
        $defaultAddressId = $value->getDefaultAddressId();
        $companyLocality = $value['company_locality'];
        if (!$shoptitle) {
            $shoptitle = $value->getShopUrl();
        }
    }
    $shoptitle = $block->escapeHtml($shoptitle);
    $feeds = $helper->getFeedTotal($sellerId);
    $defaultAddress = $b2bHelper->getAddressById($defaultAddressId);
    if ($defaultAddress && $defaultAddress->getCountryId()) {
        $locsearch = implode(
            ', ',
            $defaultAddress->getStreet()
        ).", ".
            $defaultAddress->getCity().", ".
            $defaultAddress->getRegion().", ".
            $b2bHelper->getCountryName($defaultAddress->getCountryId()).", ".
            $defaultAddress->getPostcode();
    } else {
        $locsearch = $block->escapeHtml($companyLocality);
    }
    $profileUrl = $helper->getRewriteUrl('marketplace/seller/profile/shop/'.$shopUrl);
    $requestQuoteUrl = $helper->getRewriteUrl(
        'b2bmarketplace/supplier_profile/requestQuote/shop/'.$shopUrl
    )."?product=".$product['entity_id'];
    $quickOrderUrl = $helper->getRewriteUrl(
        'b2bmarketplace/supplier_profile/quickOrder/shop/'.$shopUrl
    );?>






<div class="wk-block no-display wk-supplier-product-block" id="mp-wk-block-b2b">
        <div class="wk-supplier-product-row">
            <div>
            <a class="wk-supplier-title" href="<?= $block->escapeHtml($profileUrl)?>">
                <?= $block->escapeHtml($shoptitle)?>
            </a>
            <?php if ($supplierInfo->getWkIsVerifiedSupplier()) { ?>
                <span class="wk-supplier-verified"></span>
                <?php
            } ?>
            <?php if ($supplierInfo->getWkIsPremiumSupplier()) { ?>
                <span class="wk-supplier-premium"></span>
                <?php
            } ?>
            </div>
            <?php if ($locsearch) { ?>
                <div>
                    <a class="wk-supplier-location" title="<?= $block->escapeHtml(__('Location')) ?>" 
                    href="<?= $block->escapeHtml($helper->getRewriteUrl(
                        'marketplace/seller/location/shop/'.$shopUrl
                    )."?loc=".$locsearch)?>" target="_blank" rel="noopener">
                        <?= $block->escapeHtml(__($locsearch)); ?>
                    </a>
                </div>
            <?php } ?>
        </div>
        <?php
        $rating = $helper->getSelleRating($sellerId);
        if ($rating*1) { ?>
            <div style="position: relative;" class="wk-supplier-product-row">
                <a href="<?= $block->escapeHtml($helper->getRewriteUrl(
                    'marketplace/seller/feedback/shop/'.$shopUrl
                ))?>" title="<?= $block->escapeHtml(__('Make a Review'))?>">
                    <span class="wk-block-rating"><?= $block->escapeHtml($rating)?></span>
                </a>
                <div class="wk-seller-rating wk-mp-design-inner">
                    <div style="padding: 5px 0;">
                        <span>
                            <?=
                            $review_percentage = (($helper->getSelleRating($sellerId)*100)/5);
                            /* @noEscape */ $review_percentage."% ".
                            __('positive feedback')." (".
                            __('%1 ratings', number_format($feeds['feedcount'])).") ";
                            ?>
                        </span>
                    </div>
                    <div class="wk-mp-row">
                        <div class="mpfeedback">
                            <div class="price">
                                <span class="wk-ordertitle-label"><?= $block->escapeHtml(__('Price')) ?> 
                                </span><span>:</span>
                                <div class="ratingslider-box">
                                    <div class="rating" 
                                    style="width:<?= $block->escapeHtml(ceil($feeds['price']));?>%;">
                                </div>
                                </div>
                                <span>&nbsp;
                                (<?= $block->escapeHtml(round(($feeds['price']/20), 1, PHP_ROUND_HALF_UP))?>/5)
                                </span>
                                <div class="clear"></div>
                            </div>
                            <div class="value">
                                <span class="wk-ordertitle-label">
                                <?= $block->escapeHtml(__('Value')) ?> 
                                </span><span>:</span>
                                <div class="ratingslider-box" >
                                    <div class="rating" 
                                    style="width:<?= $block->escapeHtml(ceil($feeds['value']));?>%;">
                                    </div>                                
                                </div>
                                <span>&nbsp;
                                (<?= $block->escapeHtml(round(($feeds['value']/20), 1, PHP_ROUND_HALF_UP))?>/5)
                                </span>
                                <div class="clear"></div>
                            </div>
                            <div class="quality">
                                <span class="wk-ordertitle-label"><?= $block->escapeHtml(__('Quality')) ?> 
                                </span><span>:</span>
                                <div class="ratingslider-box">
                                    <div class="rating" 
                                    style="width:<?= $block->escapeHtml(ceil($feeds['quality']));?>%;"></div>
                                </div>
                                <span>&nbsp;
                                (<?= $block->escapeHtml(round(($feeds['quality']/20), 1, PHP_ROUND_HALF_UP))?>/5)
                                </span>
                                <div class="wk-clear"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <span class="wk-supplier-visit-web">
                    <a href="<?= $block->escapeHtml($profileUrl)?>" 
                    title="<?= $block->escapeHtml(__('Visit Shop')) ?>" id="profileconnect">
                        <?= $block->escapeHtml(__('Visit Website')) ?>
                    </a>
                </span>
            </div>
            <?php
        } ?>
        <div class="wk-supplier-btn-wrapper wk-supplier-product-row">
            <button class="wk-supplier-msg-btn askque" id="askque">
                <span><?= $block->escapeHtml(__('Message Supplier'))?></span>
            </button>
        </div>
        <div class="wk-supplier-dropdown-wrap">
            <span class="action toggle"
                    data-mage-init='{"dropdown":{}}'
                    data-toggle="dropdown"
                    aria-haspopup="true">
                <?= $block->escapeHtml(__('More Information'))?>
            </span>
            <div class="wk-supplier-dropdown">
                <?php
                $responseTime = $supplierInfo->getWkSupplierResponseTime();
                $responseTimeUnit = $supplierInfo->getWkSupplierResponseTimeUnit();
                $responseRate = $b2bHelper->getResponseRate(
                    $sellerId,
                    $responseTime,
                    $responseTimeUnit
                );
                if ($responseRate) { ?>
                    <div class="wk-supplier-product-row">
                        <div class="wk-supplier-response-rate-container">
                            <div class="wk-supplier-info-row wk-supplier-collection-header-txt">
                                <?= $block->escapeHtml(__('Response Rate'))?>
                                <strong> - <?= $block->escapeHtml($responseRate)?>%</strong>
                            </div>
                        </div>
                    </div>
                    <?php
                } ?>
                <?php if ($responseTime = $supplierInfo->getWkSupplierResponseTime()) {
                    if (!$supplierInfo->getWkSupplierResponseTimeUnit()) {
                        $timeUnit = __('Hour(s)');
                    } else {
                        if ($supplierInfo->getWkSupplierResponseTimeUnit() == 'day') {
                            $timeUnit = __('Day(s)');
                        } else {
                            $timeUnit = __('Hour(s)');
                        }
                    }
                    ?>
                    <div class="wk-supplier-product-row">
                        <div class="wk-supplier-response-time-container">
                            <div class="wk-supplier-info-row wk-supplier-collection-header-txt">
                                <?= $block->escapeHtml(__('Response Time'))?>
                                <strong> - <?= $block->escapeHtml($responseTime." ".$timeUnit)?></strong>
                            </div>
                        </div>
                    </div>
                    <?php
                } ?>
                <?= $block->getChildHtml()?>
                <div class="wk-supplier-btn-wrapper wk-supplier-product-row">
                        <button class="action primary" id="quick_order">
                            <span><?= $block->escapeHtml(__('Quick Order'))?></span>
                        </button>
                </div>
                <div class="wk-supplier-btn-wrapper wk-supplier-product-row">
                    <a href="<?= $block->escapeHtml($requestQuoteUrl)?>" 
                        title="<?= $block->escapeHtml(__('Request a Quote'))?>">
                        <button class="action primary">
                            <span><?= $block->escapeHtml(__('Request a Quote'))?></span>
                        </button>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <script>
        require([
            "jquery",
            "mage/mage"
        ], function($) {
            $("#quick_order").on("click", function(){
                $("#product-addtocart-button").trigger("click");
                var form = $("#product_addtocart_form");
                var redirectUrl = this.redirectUrl;
                if (!(form.validation() && form.validation('isValid'))) {
                    return;
                } else {
                    $('body').trigger('processStart');
                    window.location = '<?= /* @noEscape */ $quickOrderUrl ?>';
                }
            });
            var askDataForm = $('#ask-form');
            askDataForm.mage('validation', {});

            $('.product-info-main').append($('#mp-wk-block-b2b'));
            $('#mp-wk-block-b2b').show();

            $('body').append($('#wk-mp-ask-data'));

            $(".wk-block-rating" ).mouseover(function() {
                  $( ".wk-seller-rating" ).show();
            }).mouseout(function() {
                $( ".wk-seller-rating" ).hide();
            });
        });
    </script>



    <?php }?>
    
    








    <?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_B2BMarketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$quickOrderBlock =  $block->getLayout()->createBlock(
    \Webkul\B2BMarketplace\Block\Supplier\Profile\QuickOrder::class
);

$helper = $quickOrderBlock->helper(\Webkul\Marketplace\Helper\Data::class);
$b2bHelper = $quickOrderBlock->helper('Webkul\B2BMarketplace\Helper\Data');
$captchenable = $helper->getCaptchaEnable();
if (!$partner = $block->getProfileDetail()) {
    $product = $block->getProduct();
    $sellerId = '';
    $marketplaceProduct = $helper->getSellerProductDataByProductId($product['entity_id']);
    foreach ($marketplaceProduct as $value) {
        $sellerId = $value['seller_id'];
    }
    $rowsocial = $helper->getSellerDataBySellerId($sellerId);
    foreach ($rowsocial as $value) {
        $partner = $value;
    }
}
if ($sellerId = $partner->getSellerId()) {
    $supplierInfo = $b2bHelper->getSupplierInfoById($sellerId);
    $shopUrl = $block->escapeHtml($partner['shop_url']);
    $shoptitle = $block->escapeHtml($partner->getShopTitle());
    if (!$shoptitle) {
        $shoptitle = $shopUrl;
    }
    ?>
    <div class="ask-que-b2b">
        <div id="wk-supplier-ask-data-b2b">
            <div class="modals-wrapper">
                <aside tabindex="0" data-type="popup" data-role="modal"
                class="modal-popup modal-slide _inner-scroll wk-supplier-model-popup">
                    <div tabindex="0" data-role="focusable-start"></div>
                    <div data-role="focusable-scope" class="modal-inner-wrap">
                        <header class="modal-header">
                            <div class="wk-supplier-container-left">
                                <div>
                                    <a class="wk-supplier-collection-title"
                                    href="<?= $block->escapeHtml($helper
                                    ->getRewriteUrl('marketplace/seller/profile/shop/'.$shopUrl));?>">
                                        <?= $block->escapeHtml($shoptitle)?>
                                    </a>
                                    <?php if ($supplierInfo->getWkIsVerifiedSupplier()) { ?>
                                        <span class="wk-supplier-verified"><?= $block
                                        ->escapeHtml(__('Verified'))?></span>
                                        <?php
                                    } ?>
                                    <?php if ($supplierInfo->getWkIsPremiumSupplier()) { ?>
                                        <span class="wk-supplier-premium"><?= $block
                                        ->escapeHtml(__('Premium Supplier'))?></span>
                                        <?php
                                    } ?>
                                </div>
                                <div class="wk-supplier-rating-summary">
                                    <?php
                                    $feedData = $helper->getFeedTotal($sellerId);
                                    $totalRating = (
                                        $feedData['price'] + $feedData['value'] + $feedData['quality']
                                    ) / 60;
                                    $rating = round($totalRating, 1, PHP_ROUND_HALF_UP);
                                    $ratingPercent = $rating*20;
                                    ?>
                                    <span class="product-reviews-summary short">
                                        <div class="rating-summary">
                                            <div class="rating-result" title="<?= $block
                                            ->escapeHtml($ratingPercent)?>%">
                                                <span style="width:<?= $block
                                                ->escapeHtml($ratingPercent)?>%">
                                                    <span><?= $block
                                                    ->escapeHtml($ratingPercent)?>%</span>
                                                </span>
                                            </div>
                                        </div>
                                    </span>
                                    <a class="wk-supplier-rating-container" href="<?= $block
                                    ->escapeHtml($helper->getRewriteUrl('marketplace/seller/feedback/shop/'.
                                    $shopUrl))?>"
                                    title="<?= $block->escapeHtml(__('Make a Review'))?>">
                                        <span class="wk-supplier-rating-avg"><?= $block
                                        ->escapeHtml($rating); ?> - </span>
                                    </a>
                                    <span class="wk-supplier-rating-total wk-supplier-collection-header-txt">
                                        <?= $block->escapeHtml(__(
                                            '%1 Ratings',
                                            $feedData['feedcount']
                                        ))?>
                                    </span>
                                </div>
                            </div>
                            <div class="wk-supplier-container-right">
                                <div class="wk-supplier-info-wrapper">
                                    <div class="wk-supplier-info-container">
                                        <?php
                                        $responseTime = $supplierInfo
                                        ->getWkSupplierResponseTime();
                                        $responseTimeUnit = $supplierInfo
                                        ->getWkSupplierResponseTimeUnit();
                                        $responseRate = $b2bHelper->getResponseRate(
                                            $sellerId,
                                            $responseTime,
                                            $responseTimeUnit
                                        );
                                        ?>
                                        <?php if ($responseRate) { ?>
                                            <div class="wk-supplier-response-rate-container">
                                                <div class="wk-supplier-info-row wk-supplier-collection-header-txt">
                                                    <?= $block->escapeHtml(__('Response Rate'))?>
                                                </div>
                                                <div><?= $block->escapeHtml($responseRate)?>%</div>
                                            </div>
                                            <?php
                                        } ?>
                                        <?php if ($responseTime) {
                                            if (!$supplierInfo->getWkSupplierResponseTimeUnit()) {
                                                $timeUnit = __('Hours');
                                            } else {
                                                if ($supplierInfo->getWkSupplierResponseTimeUnit() == 'day') {
                                                    $timeUnit = __('Days');
                                                } else {
                                                    $timeUnit = __('Hours');
                                                }
                                            }
                                            ?>
                                            <div class="wk-supplier-response-time-container">
                                                <div class="wk-supplier-info-row wk-supplier-collection-header-txt">
                                                    <?= $block->escapeHtml(__('Response Time'))?>
                                                </div>
                                                <div><?= $block->escapeHtml($responseTime." ".$timeUnit)?></div>
                                            </div>
                                            <?php
                                        } ?>
                                    </div>
                                </div>
                            </div>
                            <button type="button" data-role="closeBtn" class="action-close wk-close-b2b">
                                <span><?= $block->escapeHtml(__('Close')) ?></span>
                            </button>
                            <span  class="wk-clear" ></span>
                        </header>
                        <form id="ask-form-b2b" method="post" action="#" class="fieldset">
                            <div class="modal-body form-list field required">
                                <label class="label"><?= $block->escapeHtml(__('Write a Message')) ?> :</label>
                                <textarea  name="msg" class="queryquestion wk-contact_input_fields required-entry"
                                style="width:100%;" rows="6"></textarea>
                                <input type="hidden" name="seller_id" value="<?= $block
                                ->escapeHtml($sellerId);?>"/>
                                <div class="wk-file-field-b2b-container">
                                    <span class="wk-file-label wk-supplier-primary-btn">
                                        <?= $block->escapeHtml(__('Add Attachment')) ?>
                                        <input type="file" name="files" class="wk-file-field-b2b" id="wk-file-field-b2b"
                                        data-url="<?= $block
                                        ->escapeHtml($block->getUrl('b2bmarketplace/supplier_profile/fileUpload', [
                                            '_secure' => $block->getRequest()->isSecure()])) ?>"
                                            multiple="multiple"/>
                                    </span>
                                </div>
                                <?php if ($captchenable) { ?>
                                    <label class="label"><?= $block
                                    ->escapeHtml(__('Please enter desired result')) ?></label>
                                    <div>
                                        <span>
                                            <label for="wk-supplier-captcha-b2b">
                                            <span id="wk-supplier-captcha-b2blable1"><?= $block
                                            ->escapeHtml(rand(1, 20))?></span> +
                                             <span id="wk-supplier-captcha-b2blable2">
                                             <?= $block->escapeHtml(rand(1, 20))?></span> =</label>
                                        </span>
                                        <input type="text" class="required-entry wk-contact_input_fields"
                                        name="wk-supplier-captcha-b2b" id="wk-supplier-captcha-b2b" />
                                    </div>
                                    <?php
                                }?>
                            </div>
                            <div class="modal-footer wk-supplier-btn-wrapper">
                                <span class="error"></span>
                                <span class="errormail"></span>
                                <button type="reset" id="resetbtn-b2b" class="wk-btn wk-btn_default">
                                    <span><?= $block->escapeHtml(__('Reset')) ?></span>
                                </button>
                                <button type="submit" id="askbtn-b2b" class="wk-btn wk-btn-primary clickask-b2b">
                                    <span><?= $block->escapeHtml(__('Send Message')) ?></span>
                                </button>
                                <span class="wk-clear"></span>
                            </div>
                        </form>
                    </div>
                    <div tabindex="0" data-role="focusable-end"></div>
                </aside>
            </div>
        </div>
    </div>
    <script id="wk-file-field-b2b-template" type="text/x-magento-template">
        <div class="wk-uploaded-file-b2b">
            <span class="wk-uploaded-file-b2b-style wk-supplier-primary-btn">
            <%- data.extension %></span>
            <span class="wk-uploaded-file-b2b-name"><%- data.name %></span>
            <input type="hidden" name="attachments[<%- data.index %>][name]"
            value="<%- data.name %>"/>
            <input type="hidden" name="attachments[<%- data.index %>][file]"
            value="<%- data.file %>"/>
            <span class="wk-uploaded-file-b2b-del"></span>
        </div>
    </script>
    <script id="wk-file-field-b2b-uploader-template" type="text/x-magento-template">
        <div id="<%- data.id %>" class="wk-uploaded-file-b2b-row">
            <img alt="imarkplace" src="<?= $block->escapeHtml($block
            ->getViewFileUrl('Webkul_Marketplace/images/ajax-loader-big.gif'))?>"/>
        </div>
    </script>

    <script>
        require([
            "jquery",
            'Magento_Ui/js/modal/alert',
        ], function($, alert) {
            var askDataForm = $('#ask-form-b2b');
            askDataForm.mage('validation', {});

            $('body').append($('#wk-supplier-ask-data-b2b'));
            $('.askque').click(function() {
                console.log("tets webkul data");
                $('#ask-form-b2b input,#ask-form-b2b textarea').removeClass('mage-error');
                $('.wk-supplier-model-popup').addClass('_show');
                $('#wk-supplier-ask-data-b2b').show();
            });
            $('.wk-close-b2b').click(function() {
                $('.wk-uploaded-file-b2b-del').trigger('click');
                $('#resetbtn-b2b').trigger('click');
                $('#wk-supplier-ask-data-b2b').hide();
                $('#ask-form-b2b .validation-failed').each(function() {
                    $(this).removeClass('validation-failed');
                });
                $('#ask-form-b2b .validation-advice').each(function() {
                    $(this).remove();
                });
            });
            $('.wk-file-field-b2b-container').on("click", ".wk-uploaded-file-b2b-del", function() {
                $(this).parent('.wk-uploaded-file-b2b').remove();
            });

            $('#askbtn-b2b').click(function() {
                if (askDataForm.valid()!=false) {
                    var thisthis = $(this);
                    if (thisthis.hasClass("clickask-b2b")) {
                        <?php if ($captchenable) { ?>
                            var total = parseInt($('#wk-supplier-captcha-b2blable1').text()) +
                            parseInt($('#wk-supplier-captcha-b2blable2').text());
                            var wk_mp_captcha = $('#wk-supplier-captcha-b2b').val();
                            if (total != wk_mp_captcha) {
                                $('#wk-supplier-captcha-b2blable1').text(Math.floor((Math.random()*10)+1));
                                $('#wk-supplier-captcha-b2blable2').text(Math.floor((Math.random()*100)+1));
                                $('#wk-supplier-captcha-b2b').val('');
                                $('#wk-supplier-captcha-b2b').addClass('mage-error');
                                $(this).addClass('mage-error');
                                $('#ask_form .errormail').
                                text("<?= /* @noEscape */ __(' Wrong verification number. ') ?>").
                                slideDown('slow').delay(2000).slideUp('slow');
                            } else {
                                thisthis.removeClass('clickask-b2b');
                                $('#wk-supplier-ask-data-b2b').find('.modal-inner-wrap').addClass('mail-procss');
                                $.ajax({
                                    url:'<?= /* @noEscape */ $block->getUrl("b2bmarketplace/message/post", [
                                        "_secure" => $block->getRequest()->isSecure()]) ?>',
                                    data:$('#ask-form-b2b').serialize(),
                                    type:'post',
                                    dataType:'json',
                                    showLoader: true,
                                    success:function(data) {
                                        $(".modals-overlay").removeClass("wk-modals-overlay");
                                        if (data.error) {
                                            alert({
                                            content: '<?= /* @noEscape */ __("Message is sent successfully.")?>',
                                            actions: {
                                                always: function() {
                                                        location.reload(true);
                                                }
                                            },
                                            // buttons: []
                                            buttons: [{
                                                text: $.mage.__('OK'),
                                                class: 'action-primary action-accept',
                                                click: function () {
                                                    location.reload(true);
                                                }
                                            }]
                                        });
                                            thisthis.addClass('clickask-b2b');
                                            $('#wk-supplier-ask-data-b2b').find('.modal-inner-wrap').
                                            removeClass('mail-procss');
                                            $('.wk-uploaded-file-b2b-del').trigger('click');
                                            $('#resetbtn-b2b').trigger('click');
                                            $('body').removeClass('_has-modal');
                                        } else {
                                            alert({
                                            content: '<?= /* @noEscape */ __("Message is sent successfully.")?>',
                                            actions: {
                                                always: function() {
                                                        location.reload(true);
                                                }
                                            },
                                            // buttons: []
                                            buttons: [{
                                                text: $.mage.__('OK'),
                                                class: 'action-primary action-accept',
                                                click: function () {
                                                    location.reload(true);
                                                }
                                            }]
                                        });
                                            thisthis.addClass('clickask-b2b');
                                            $('#wk-supplier-ask-data-b2b').find('.modal-inner-wrap').
                                            removeClass('mail-procss');
                                            $('.wk-uploaded-file-b2b-del').trigger('click');
                                            $('#resetbtn-b2b').trigger('click');
                                            $('body').removeClass('_has-modal');
                                        }
                                    }
                                });
                            }
                        <?php } else { ?>
                            thisthis.removeClass('clickask-b2b');
                            $('#wk-supplier-ask-data-b2b').find('.modal-inner-wrap').addClass('mail-procss');
                                $.ajax({
                                    url:'<?= /* @noEscape */ $block->getUrl("b2bmarketplace/message/post", [
                                        "_secure" => $block->getRequest()->isSecure()]) ?>',
                                    data:$('#ask-form-b2b').serialize(),
                                    type:'post',
                                    dataType:'json',
                                    showLoader: true,
                                    success:function(data) {
                                        $('.wk-supplier-model-popup').removeClass('_show');
                                        // closeModal();
                                        $(".modals-overlay").removeClass("wk-modals-overlay");
                                        if (data.error) {
                                            alert({
                                                content: data.msg,
                                                clickableOverlay: false
                                            });
                                            thisthis.addClass('clickask-b2b');
                                            $('#wk-supplier-ask-data-b2b').find('.modal-inner-wrap').
                                            removeClass('mail-procss');
                                            $('.wk-uploaded-file-b2b-del').trigger('click');
                                            $('#resetbtn-b2b').trigger('click');
                                            $('body').removeClass('_has-modal');
                                        } else {

                                            alert({
                                            content: '<?= /* @noEscape */ __("Message is sent successfully.")?>',
                                            actions: {
                                                always: function() {
                                                    console.log("testtt");
                                                    // if (data.reload) {
                                                        location.reload(true);
                                                    // }
                                                    // hideLoader();
                                                    // currentItem.closeModal();
                                                }
                                            },
                                            // buttons: []
                                            buttons: [{
                                                text: $.mage.__('OK'),
                                                class: 'action-primary action-accept',
                                                click: function () {
                                                    location.reload(true);
                                                }
                                            }]
                                        });
                                            thisthis.addClass('clickask-b2b');
                                            $('#wk-supplier-ask-data-b2b').find('.modal-inner-wrap').
                                            removeClass('mail-procss');
                                            $('.wk-uploaded-file-b2b-del').trigger('click');
                                            $('#resetbtn-b2b').trigger('click');
                                            $('body').removeClass('_has-modal');
                                        }
                                    }
                                });
                        <?php } ?>
                    }
                    return false;
                }
            });

            // function closeModal()
            // {
            //     $(".modal-inner-wrap").hide();
            // }

            function closePopUp()
            {
                $("#ask-form-b2b textarea").val("");
                $('.wk-supplier-model-popup').removeClass('_show');
                $('#wk-supplier-ask-data-b2b').hide();
                $(".modals-overlay").addClass("wk-modals-overlay");
            }
        });
    </script>
    <script>
        require([
            "jquery",
            'mage/template',
            'Magento_Ui/js/modal/alert',
            "mage/translate",
            "jquery/file-uploader"
        ], function ($, mageTemplate, alert) {
            var attachmentIndex = 0;
            $('#wk-file-field-b2b').fileupload({
                dataType: 'json',
                sequentialUploads: true,
                acceptFileTypes: /(\.|\/)(gif|jpe?g|png|pdf|doc|zip)$/i,
                add: function (e, data) {
                    var progressTmpl = mageTemplate('#wk-file-field-b2b-uploader-template'),
                        tmpl;

                    $.each(data.files, function (index, file) {
                        data.fileId = Math.random().toString(33).substr(2, 18);

                        tmpl = progressTmpl({
                            data: {
                                id: data.fileId
                            }
                        });

                        $(tmpl).appendTo('.wk-file-field-b2b-container');
                    });

                    $(this).fileupload('process', data).done(function () {
                        data.submit();
                    });
                },
                done: function (e, data) {
                    if (data.result && !data.result.error) {
                        attachmentIndex++;
                        var progressTmpl = mageTemplate('#wk-file-field-b2b-template'),
                        tmpl;
                        tmpl = progressTmpl({
                            data: {
                                index: attachmentIndex,
                                name: data.result.name,
                                file: data.result.file,
                                extension: data.result.type
                            }
                        });

                        $(tmpl).appendTo('.wk-file-field-b2b-container');
                    } else {
                        $('#' + data.fileId)
                            .delay(2000)
                            .hide('highlight');
                        alert({
                            content: $.mage.__('We don\'t recognize or support this file extension type.'),
                            buttons: [{
                                text: $.mage.__('Accept'),
                                class: 'action primary accept',
                                click: function () {
                                    this.closeModal(true);
                                    $(".modals-overlay").addClass("wk-modals-overlay");
                                }
                            }]
                        });
                    }
                    $('#' + data.fileId).remove();
                },
                progress: function (e, data) {
                    var progress = parseInt(data.loaded / data.total * 100, 10);
                    var progressSelector = '#' + data.fileId + ' .progressbar-container .progressbar';
                    $(progressSelector).css('width', progress + '%');
                },
                fail: function (e, data) {
                    var progressSelector = '#' + data.fileId;
                    $(progressSelector).removeClass('upload-progress').addClass('upload-failure')
                        .delay(2000)
                        .hide('highlight')
                        .remove();
                }
            });
            $('#wk-file-field-b2b').fileupload('option', {
                process: [{
                    action: 'load',
                    fileTypes: /^image\/(gif|jpeg|png)$/
                }, {
                    action: 'resize',
                    maxWidth: <?= /* @noEscape */ \Magento\Framework\File\Uploader::MAX_IMAGE_WIDTH ?> ,
                    maxHeight: <?= /* @noEscape */ \Magento\Framework\File\Uploader::MAX_IMAGE_HEIGHT ?>
                }, {
                    action: 'save'
                }]
            });
        });
    </script>
    <?php
} ?>
