<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_B2BMarketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

$helper = $block->helper('Webkul\B2BMarketplace\Helper\MpHelper');
$partner = $block->getProfileDetail();
$checkoutUrl = $block->getUrl('checkout/', ['_secure' => $block->getRequest()->isSecure()]);
if ($partner['shop_url']) {
    $sellerId = $partner->getSellerId();
    $rfqProductSku = '';
    $requestProductForQuote = $block->getRequestProductForQuickOrder($sellerId);
    if ($requestProductForQuote && $requestProductForQuote->getId()) {
        $rfqProductSku = $block->escapeHtml($requestProductForQuote->getSku());
    }
    $shopUrl = $block->escapeHtml($partner['shop_url']);
    $shoptitle = $block->escapeHtml($partner->getShopTitle());
    if (!$shoptitle) {
        $shoptitle = $shopUrl;
    }
    $bufferTime = '48';
    /* buffer time in hour in which supplier need to respond to customer,
     else quote will to tranfer to next available supplier*/
    $currentUrl = $helper->getCurrentUrl();
    $searchUrl = $block->getUrl(
        'b2bmarketplace/product/search',
        ['_secure' => $block->getRequest()->isSecure()]
    );
    $productOptionsUrl = $block->getUrl(
        'b2bmarketplace/product/options',
        ['_secure' => $block->getRequest()->isSecure()]
    );
    $addProductToQuoteUrl = $block->getUrl(
        'b2bmarketplace/quickOrder/add',
        ['_secure' => $block->getRequest()->isSecure()]
    );
    $updateItemQtyUrl = $block->getUrl(
        'b2bmarketplace/quickOrder/updateItemQty',
        ['_secure' => $block->getRequest()->isSecure()]
    );
    $removeProductFromQuoteUrl = $block->getUrl(
        'b2bmarketplace/quickOrder/delete',
        ['_secure' => $block->getRequest()->isSecure()]
    );
    if ($helper->getActiveColorPicker()) { ?>
        <style>
            .page-main{
                background-image:none;
                background-color:<?= /* @noEscape */ $block->escapeHtml($partner['background_width']);?>;
            }
        </style>
    <?php } ?>
    <style>
        .wk-supplier-banner {
            display: none;
        }
    </style>
    <div class="wk-supplier-design">
        <?= /* @noEscape */ $block->getChildHtml("marketplace_seller_top_block")?>
        <div class="wk-supplier-collection-container">
            <div id="wk-supplier-quick-order">
                <h2 class="wk-supplier-collection-h2"><?= $block->escapeHtml(__("Quick Order")) ?></h2>
                <form id="wk-quick-order-form"
                    data-bind="scope: 'wk-quick-order-wizard'"
                    name="wk-quick-order-form"
                    method="post"
                    action="<?= $block
                    ->escapeHtml($block
                    ->getUrl('checkout/', [
                        '_secure' => $block->getRequest()->isSecure()])) ?>"
                    class="wk-supplier-products-row-container wk-supplier-collection-header-txt">
                    <input type="hidden" name="form_key" id="wk-qo-form-key" 
                    value="<?= $block->escapeHtml($block->getFormKey())?>" />
                    <table class="wk-quick-order-product-table">
                        <thead>
                            <tr>
                                <th><?= $block->escapeHtml(__('Product Name'))?></th>
                                <th><?= $block->escapeHtml(__('Quantity'))?></th>
                                <th><?= $block->escapeHtml(__('Subtotal'))?></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody class="wk-quick-order-product-table-tbody">
                        </tbody>
                    </table>
                    <script id="wk-quick-order-quote-item-row-template" type="text/x-magento-template">
                        <tr>
                            <td data-th="<?= $block->escapeHtml(__('Product Name'))?>">
                                <input type="text"
                                    name="product[][name]"
                                    data-typeId="<%- data.typeId %>"
                                    data-bind="afterRender: loadJsAfterKoRender"
                                    id="wk_search_box<%- data.index %>"
                                    value="<%- data.name %>"
                                    class="wk-product-search-box"
                                    placeholder="<?= $block->escapeHtml(__('Enter Product Name or SKU Number'))?>"
                                    disabled/>
                                <input type="hidden" name="product[][id]" 
                                value="<%- data.product_id %>" class="wk_product_item"/>
                                <input type="hidden" name="product[][item]" 
                                value="<%- data.item_id %>" class="wk_product_quote_item" 
                                id="wk_quote_item<%- data.item_id %>"/>
                                <input type="hidden" name="product[][price]" 
                                value="<%- data.price %>" class="wk_product_quote_item_price"/>
                                <input type="hidden" name="product[][qty]" 
                                value="<%- data.qty %>" class="wk_product_quote_item_qty"/>
                            </td>
                            <td data-th="<?= $block->escapeHtml(__('Quantity'))?>">
                                <input type="text"
                                    name="product[][qty]"
                                    class="wk-product-qty-box"
                                    value="<%- data.qty %>"
                                    placeholder="<?= $block->escapeHtml(__('Qty #'))?>"
                                    data-bind="event: { change: onChangeProductQty }"
                                    />
                            </td>
                            <td data-th="<?= $block->escapeHtml(__('Subtotal'))?>">
                                <input type="text"
                                    name="product[][sub_total]"
                                    class="wk-product-price-box"
                                    value="<%- data.row_total %>"
                                    placeholder="<?= $block->escapeHtml(__('N/A'))?>"
                                    disabled/>
                            </td>
                            <td>
                                <button type="button"
                                    class="btn button wk-quick-order-product-remove"
                                    data-bind="event: { click: removeProductRow}">
                                    <span><?= $block->escapeHtml(__('Remove')) ?></span>
                                </button>
                            </td>
                        </tr>
                    </script>
                    <script id="wk-quick-order-product-row-template" type="text/x-magento-template">
                        <tr>
                            <td data-th="<?= $block->escapeHtml(__('Product Name'))?>">
                                <input type="text"
                                    data-typeId="<%- data.typeId %>"
                                    data-bind="afterRender: loadJsAfterKoRender,
                                    event: { blur: onBlur, focus: onFocus, keydown: onKeyDown, 
                                    'input propertychange': onPropertyChange }"
                                    name="product[][name]"
                                    id="wk_search_box<%- data.index %>"
                                    data-index="<%- data.index %>"
                                    value=""
                                    class="wk-product-search-box"
                                    placeholder="<?= $block->escapeHtml(__('Enter Product Name or SKU Number'))?>"
                                    role="combobox"
                                    aria-haspopup="false"
                                    aria-autocomplete="both"
                                    autocomplete="off"/>
                                <input type="hidden" name="product[][id]" 
                                value="" class="wk_product_item"/>
                                <input type="hidden" name="product[][item]" 
                                value="" class="wk_product_quote_item"/>
                                <input type="hidden" name="product[][price]" 
                                value="" class="wk_product_quote_item_price"/>
                                <input type="hidden" name="product[][qty]" 
                                value="" class="wk_product_quote_item_qty"/>
                                <div id="wk_search_autocomplete<%- data.index %>" 
                                class="search-autocomplete"></div>
                            </td>
                            <td data-th="<?= $block->escapeHtml(__('Quantity'))?>">
                                <input type="text"
                                    name="product[][qty]"
                                    class="wk-product-qty-box"
                                    value=""
                                    placeholder="<?= $block->escapeHtml(__('Qty #'))?>"
                                    data-bind="event: { change: onChangeProductQty }"
                                    />
                            </td>
                            <td data-th="<?= $block->escapeHtml(__('Subtotal'))?>">
                                <input type="text"
                                    name="product[][sub_total]"
                                    class="wk-product-price-box"
                                    value=""
                                    placeholder="<?= $block->escapeHtml(__('N/A'))?>" disabled/>
                            </td>
                            <td>
                                <button type="button"
                                    class="btn button wk-quick-order-product-remove"
                                    data-bind="event: { click: removeProductRow}">
                                    <span><?= $block->escapeHtml(__('Remove')) ?></span>
                                </button>
                            </td>
                        </tr>
                    </script>
                    <!-- ko if: isAjaxLoader -->
                    <div class="loading-mask" data-bind="visible: isAjaxLoader">
                        <div class="loader">
                            <img src="<?= $block->escapeHtml($block->getViewFileUrl('images/loader-1.gif'))?>"
                                alt="<?= $block->escapeHtml(__('Loading...'))?>"
                                style="position: absolute;">
                        </div>
                    </div>
                    <!-- /ko -->
                    <div>
                        <span class="wk-rfq-add-btn-label wk-supplier-primary-btn" 
                        data-bind="event: { click: addProductRow }">
                            <?= $block->escapeHtml(__('Add Row')) ?>
                        </span>
                    </div>
                    <h3><?= $block->escapeHtml(__("Summary")) ?></h3>
                    <!-- ko if: isQuoteExist -->
                        <div data-block="cartSummary" 
                        data-bind="afterRender:loadJsAfterKoRender1, visible: isQuoteExist">
                            <?= /* @noEscape */ $block->getChildHtml("cart.summary")?>
                        </div>
                    <!-- /ko -->
                    <div class="wk-supplier-btn-wrapper wk-proceed-to-checkout-btn-wrapper">
                        <?= /* @noEscape */ $block->getChildHtml("wk.qo.checkout.cart.button")?>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <?php
    $priceFormat = $block->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($block->getPriceFormat());
    $isQuoteExist = $block->isQuoteExist();
    $cartItems = $block->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($block->getCartItems());
    ?>
    <script>
        require([
            "jquery"
        ], function ($) {
            $('#wk-quick-order-form').on('click', '[aria-controls="block-summary"]', function () {
                $('#block-shipping').toggleClass('active');
            });
            $(document).on("click", ".wk-proceed-to-checkout-btn-wrapper button", function (e) {
                e.preventDefault();
                location.href= "<?= /* @noEscape */$checkoutUrl; ?>";
            });
        });
    </script>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "wk-quick-order-wizard": {
                            "product_sku":"<?= /* @noEscape */ $rfqProductSku; ?>",
                            "component": "productAjaxSearch",
                            "emptyProductReturnLabel": 
                            "<?= /* @noEscape */ __('No record found! Please search for another keyword.')?>",
                            "formSelector": "#wk-quick-order-form",
                            "fieldSelector": ".wk-product-search-box",
                            "destinationSelector": ".search-autocomplete",
                            "priceFormat": <?= /* @noEscape */ $priceFormat?>,
                            "cartItems": <?= /* @noEscape */ $cartItems?>,
                            "isQuoteExistFlag": <?= /* @noEscape */ $isQuoteExist?>,
                            "currentUrl": "<?= /* @noEscape */ $currentUrl?>",
                            "url": "<?= /* @noEscape */ $searchUrl?>",
                            "shop_url": "<?= /* @noEscape */ $shopUrl?>",
                            "productOptionsUrl": "<?= /* @noEscape */ $productOptionsUrl?>",
                            "addProductToQuoteUrl": "<?= /* @noEscape */ $addProductToQuoteUrl?>",
                            "updateItemQtyUrl": "<?= /* @noEscape */ $updateItemQtyUrl?>",
                            "removeProductFromQuoteUrl": "<?= /* @noEscape */ $removeProductFromQuoteUrl?>"
                        }
                    }
                }
            }
        }
    </script>
<?php }  ?>
