<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_B2BMarketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

$helper = $block->helper(\Webkul\Marketplace\Helper\Data::class);
$partner=$block->getProfileDetail();
if ($partner['shop_url']) {
    $sellerId = $partner->getSellerId();
    $rfqProductId = '';
    $rfqProductName = '';
    $requestProductForQuote = $block->getRequestProductForQuote($sellerId);
    if ($requestProductForQuote && $requestProductForQuote->getId()) {
        $rfqProductId = $requestProductForQuote->getId();
        $rfqProductName = $requestProductForQuote->getName();
    }
    $shopUrl = $block->escapeHtml($partner['shop_url']);
    $shoptitle = $block->escapeHtml($partner->getShopTitle());
    if (!$shoptitle) {
        $shoptitle = $shopUrl;
    }
    $submitUrl = $block->getUrl(
        'b2bmarketplace/supplier_profile/requestQuotePost',
        ['_secure' => $block->getRequest()->isSecure()]
    );
    if ($helper->getActiveColorPicker()) { ?> 
        <style>
            .page-main{
                background-image:none;
                background-color:<?= /* @noEscape */ $block->escapeHtml($partner['background_width']);?>;
            }
        </style>
    <?php } ?>
    <style>
        .wk-supplier-banner {
            display: none;
        }
    </style>
    <div class="wk-supplier-design">
        <?= /* @noEscape */ $block->getChildHtml("marketplace_seller_top_block")?>
        <div class="wk-supplier-collection-container">
            <div id="wk-supplier-request-quote">
                <h2 class="wk-supplier-collection-h2"><?= /* @noEscape */ __("Request a Quote") ?></h2>
                <form id="wk-add-rfq-product-form" name="wk-add-rfq-product-form" method="post" action="#">
                    <h3><?= /* @noEscape */ __("Product(s) Information") ?></h3>
                    <table class="wk-rfq-product-table">
                        <thead>
                            <tr>
                                <th><?= /* @noEscape */ __('Product Name')?></th>
                                <th><?= /* @noEscape */ __('Quantity')?></th>
                                <th><?= /* @noEscape */ __('Price')?></th>
                                <th><?= /* @noEscape */ __('Samples')?></th>
                                <th><?= /* @noEscape */ __('Action')?></th>
                            </tr>
                        </thead>
                        <tbody class="wk-rfq-product-table-tbody">
                            <script id="wk-rfq-product-row-template" type="text/x-magento-template">
                                <tr id="<%- data.field_id %>">
                                    <td><%- data.name %></td>
                                    <td><%- data.qty %></td>
                                    <td><%- data.formated_price %><?= /* @noEscape */ __(' per qty')?></td>
                                    <td><%- data.is_sample %></td>
                                    <td>
                                        <span title="<?= /* @noEscape */ __('Remove')?>" 
                                        class="wk-rfq-product-delete wk-row-product-delete"></span>
                                    </td>
                                </tr>
                            </script>
                            <script id="wk-rfq-pro-add-to-form-template" type="text/x-magento-template">
                                <div id="wk-rfq-pro<%- data.field_id %>">
                                    <input type="hidden" name="rfq_product[<%- data.index %>][product_id]" 
                                    value="<%- data.product_id %>"/>
                                    <input type="hidden" name="rfq_product[<%- data.index %>][name]" 
                                    value="<%- data.name %>"/>
                                    <input type="hidden" name="rfq_product[<%- data.index %>][description]" 
                                    value="<%- data.description %>"/>
                                    <input type="hidden" name="rfq_product[<%- data.index %>][qty]" 
                                    value="<%- data.qty %>"/>
                                    <input type="hidden" name="rfq_product[<%- data.index %>][price]" 
                                    value="<%- data.price %>"/>
                                    <input type="hidden" name="rfq_product[<%- data.index %>][is_sample]" 
                                    value="<%- data.is_sample %>"/>
                                </div>
                            </script>
                        </tbody>
                    </table>
                    <div class="wk-supplier-products-row-container">
                        <div class="wk-supplier-collection-header-txt fieldset"
                            data-bind="scope: 'wk-request-quote-product-wizard'">
                            <div class="field required">
                                <label class="label"><?= /* @noEscape */ __('Product Name')?></label>
                                <input type="text" 
                                    data-bind="event: { 
                                        blur: onBlur, focus: onFocus, keydown: onKeyDown, 
                                        'input propertychange': onPropertyChange 
                                        }"
                                    name="name"
                                    id="wk_search_box"
                                    value="<?= /* @noEscape */ $rfqProductName?>"
                                    class="wk-product-search-box input-text required-entry"
                                    placeholder="<?= /* @noEscape */ __('Enter Product Name or SKU Number')?>"
                                    role="combobox"
                                    aria-haspopup="false"
                                    aria-autocomplete="both"
                                    autocomplete="off"/>
                                <input type="hidden" name="product_id" 
                                value="<?= /* @noEscape */ $rfqProductId?>" id="wk_product_id"/>
                                <div id="wk_search_autocomplete" class="search-autocomplete"></div>
                            </div>
                            <div class="field required">
                                <label class="label"><?= /* @noEscape */ __('Product Description')?></label>
                                <textarea  name="description" class="input-tex required-entry" 
                                style="width:100%;" rows="6"></textarea>
                            </div>
                            <div class="field required">
                                <label class="label"><?= /* @noEscape */ __('Product Quantity')?></label>
                                <input type="text" name="qty" 
                                class="required-entry validate-number input-text"/>
                            </div>
                            <div class="field required">
                                <label class="label"><?= /* @noEscape */ __('Expected Price per Quantity')?></label>
                                <input type="text" name="price" 
                                class="required-entry validate-zero-or-greater input-text"/>
                            </div>
                            <!-- ko if: isAjaxLoader -->
                            <div class="loading-mask" data-bind="visible: isAjaxLoader">
                                <div class="loader">
                                    <img src="<?= /* @noEscape */
                                    $block->getViewFileUrl('images/loader-1.gif')?>" 
                                        alt="<?= /* @noEscape */ __('Loading...')?>" 
                                        style="position: absolute;">
                                </div>
                            </div>
                            <!-- /ko -->
                        </div>
                        <div class="wk-supplier-collection-header-txt fieldset">
                            <div class="field required">
                                <label class="label"><?= /* @noEscape */ __('Samples')?></label>
                                <select name="is_sample">
                                    <option value="required">
                                    <?= /* @noEscape */ __('Yes, Sample are required')?></option>
                                    <option value="not required">
                                    <?= /* @noEscape */ __('No, Sample are not required')?></option>
                                </select>
                            </div>
                            <div class="field">
                                <label class="label"><?= /* @noEscape */ __('Sample Product Images')?></label>
                                <div class="wk-supplier-product-images-container">
                                    <div class="wk-supplier-image wk-supplier-image-placeholder">
                                        <div id="wk-supplier-image-uploader" class="uploader">
                                            <div class="wk-supplier-fileinput-button form-buttons">
                                                <span><?= /* @noEscape */ __('Add Image') ?></span>
                                                <input type="file" name="image" 
                                                class="wk-supplier-product-image-field" 
                                                id="wk-supplier-product-image-field" 
                                                data-url="<?= /* @noEscape */
                                                $block->getUrl('b2bmarketplace/supplier_profile/productImageUpload', [
                                                    '_secure' =>
                                                $block
                                                ->getRequest()->isSecure()]) ?>" 
                                                multiple="multiple"/>
                                            </div>
                                            <div class="clear"></div>
                                            <script id="wk-supplier-image-uploader-template" 
                                            type="text/x-magento-template">
                                                <div id="<%- data.id %>" class="file-row">
                                                    <span class="file-info"><%- data.name %> (<%- data.size %>)</span>
                                                    <div class="progressbar-container">
                                                        <div class="progressbar upload-progress" style="width: 0%;">
                                                        </div>
                                                    </div>
                                                    <div class="clear"></div>
                                                </div>
                                            </script>
                                            <img alt="imarkplace" class="spacer" src="<?= /* @noEscape */
                                            $block->getViewFileUrl('images/spacer.gif')?>">
                                            <p class="wk-supplier-image-placeholder-text">
                                                <?= /* @noEscape */ __('Add Sample Images.')?>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <span class="wk-supplier-separate-line"></span>
                    <div>
                        <span class="wk-rfq-add-btn-label wk-supplier-primary-btn" id="wk-rfq-add-product">
                            <?= /* @noEscape */ __('Add Product') ?>
                        </span>
                    </div>
                </form>
                <form id="wk-supplier-rfq-form" name="wk-supplier-rfq-form" 
                method="post" action="<?= /* @noEscape */ $submitUrl?>">
                    <?= /* @noEscape */ $block->getBlockHtml('formkey')?>
                    <div id="wk-rfq-quote-container">
                        <h3><?= /* @noEscape */ __("Quote Information") ?></h3>
                        <div class="wk-supplier-collection-header-txt fieldset">
                            <div class="field required">
                                <label class="label"><?= /* @noEscape */ __('Quote Title')?></label>
                                <input type="text" name="quote_title" class="input-text required-entry"/>
                            </div>
                            <div class="field required">
                                <label class="label"><?= /* @noEscape */ __('Quote Brief')?></label>
                                <textarea  name="quote_description" class="input-tex required-entry" 
                                style="width:100%;" rows="6"></textarea>
                            </div>
                            <div class="wk-rfq-file-field-container">
                                <label class="label wk-file-label wk-supplier-primary-btn">
                                    <?= /* @noEscape */ __('Add Attachment') ?>
                                    <input type="file" name="files" class="wk-file-field" 
                                    id="wk-rfq-file-field" data-url="<?= /* @noEscape */
                                    $block->getUrl('b2bmarketplace/supplier_profile/fileUpload', [
                                        '_secure' => $block->getRequest()->isSecure()]) ?>" 
                                    multiple="multiple"/>
                                </label>
                            </div>
                            <input type="hidden" name="shop_url" value="<?= /* @noEscape */ $shopUrl?>"/>
                            <input type="hidden" name="supplier_id" value="<?= /* @noEscape */ $sellerId?>"/>
                            <script id="wk-rfq-file-field-template" type="text/x-magento-template">
                                <div class="wk-uploaded-file">
                                    <span class="wk-uploaded-file-style wk-supplier-primary-btn">
                                    <%- data.extension %></span>
                                    <span class="wk-uploaded-file-name"><%- data.name %></span>
                                    <input type="hidden" name="quote_attachments[<%- data.index %>][name]" 
                                    value="<%- data.name %>"/>
                                    <input type="hidden" name="quote_attachments[<%- data.index %>][file]" 
                                    value="<%- data.file %>"/>
                                    <span class="wk-uploaded-file-del"></span>
                                </div>
                            </script>
                            <script id="wk-rfq-file-field-uploader-template" type="text/x-magento-template">
                                <div id="<%- data.id %>" class="wk-uploaded-file-row">
                                    <img alt="imarkplace" src="<?= /* @noEscape */
                                    $block->getViewFileUrl('Webkul_Marketplace/images/ajax-loader-big.gif')?>"/>
                                </div>
                            </script>
                        </div>
                    </div>
                    <div id="wk-rfq-contact-container">
                        <h3><?= /* @noEscape */ __("Contact Information") ?></h3>
                        <div class="wk-supplier-collection-header-txt fieldset">
                            <div class="field required">
                                <label class="label"><?= /* @noEscape */ __('Name')?></label>
                                <input type="text" name="customer_name" class="input-text required-entry"/>
                            </div>
                            <div class="field required">
                                <label class="label"><?= /* @noEscape */ __('Company Name')?></label>
                                <input type="text" name="customer_company_name" class="input-text required-entry"/>
                            </div>
                            <div class="field required">
                                <label class="label"><?= /* @noEscape */ __('Address')?></label>
                                <textarea  name="customer_address" class="input-tex required-entry" 
                                style="width:100%;" rows="6"></textarea>
                            </div>
                            <div class="field required">
                                <label class="label"><?= /* @noEscape */ __('Contact Number')?></label>
                                <input type="text" name="customer_contact_no" class="input-text required-entry"/>
                            </div>
                        </div>
                    </div>
                    <span class="wk-supplier-separate-line"></span>
                    <div class="wk-supplier-btn-wrapper">
                        <button type="reset" class="wk-btn wk-btn_default">
                            <span><?= /* @noEscape */ __('Reset') ?></span>
                        </button>
                        <button type="submit" class="wk-btn wk-btn-primary" id="wk-rfq-submit-btn">
                            <span><?= /* @noEscape */ __('Request for Quote') ?></span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script id="wk-supplier-images-field-template" type="text/x-magento-template">
        <div class="wk-supplier-image item <% if (data.disabled == 1) { %>hidden-for-front<% } %>"
            data-role="image">
            <input type="hidden" 
                    name="sample_image[<%- data.index %>][name]" 
                    value="<%- data.name %>"
                    data-path="<%- data.file %>"
                    class="wk-rfq-sample-image"/>
            <input type="hidden" 
                    name="sample_image[<%- data.index %>][file]" 
                    value="<%- data.file %>"/>
            <img alt="imarkplace" class="spacer" src="<?= /* @noEscape */ $block->getViewFileUrl('images/spacer.gif')?>">
            <img alt="imarkplace" class="product-image" src="<%- data.url %>" alt="<%- data.label %>"/>
            <div class="actions" >
                <button type="button"
                        class="action-delete wk-supplier-image-delete"
                        data-role="delete-button"
                        title="<?= /* @noEscape */ __('Delete image')?>">
                    <span>
                        <?= /* @noEscape */ __('Delete image')?>
                    </span >
                </button>
            </div >
        </div>
    </script>
    <?php
    $priceFormat = $block->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($block->getPriceFormat());
    $searchUrl = $block->getUrl(
        'b2bmarketplace/product/search',
        ['_secure' => $block->getRequest()->isSecure()]
    );
    ?>
    <script>
        require([
            "jquery",
            'mage/template',
            'Magento_Ui/js/modal/alert',
            'priceUtils',
            "mage/translate",
            "jquery/file-uploader"
        ], function ($, mageTemplate, alert, utils) {
            var addProductForm = $('#wk-add-rfq-product-form');
            addProductForm.mage('validation', {});
            var submitRfqForm = $('#wk-supplier-rfq-form');
            submitRfqForm.mage('validation', {});

            $('#wk-rfq-submit-btn').click(function (e) {
                if ($("#wk-supplier-rfq-form").valid()!==false) {
                    $('body').trigger('processStart');
                }
            });

            var index = 0;
            $('#wk-rfq-add-product').click(function (e) {
                if ($("#wk-add-rfq-product-form").valid()!==false) {
                    if ($('select[name=is_sample]').val() == 'required') {
                        
                    }
                    var obj = '';
                    index = index+1;
                    var proIndex = 0;
                    $('.wk-rfq-sample-image').each(function () {
                        var imageName = $(this).val();
                        var imagePath = $(this).attr('data-path');
                        proIndex++;
                        obj = obj+'<input type="hidden" name="rfq_product['+
                        index+'][product_sample_images]['+proIndex+'][name]" value="'+
                        imageName+'"/><input type="hidden" name="rfq_product['+index+'][product_sample_images]['+
                        proIndex+'][file]" value="'+imagePath+'"/>';
                    });
                    var fieldId = Math.random().toString(33).substr(2, 18);
                    var dataTemp = {
                        field_id: fieldId,
                        index: index,
                        product_id: $('#wk_product_id').val(),
                        name: $('input[name=name]').val(),
                        description: $('textarea[name=description]').val(),
                        qty: $('input[name=qty]').val(),
                        price: $('input[name=price]').val(),
                        formated_price: utils.formatPrice(
                            $('input[name=price]').val(),
                            <?= /* @noEscape */ $priceFormat?>
                        ),
                        is_sample: $('select[name=is_sample]').val()
                    };
                    var progressTmpl = mageTemplate('#wk-rfq-product-row-template'),
                        tmpl;
                    tmpl = progressTmpl({
                        data: dataTemp
                    });
                    $(tmpl).appendTo('.wk-rfq-product-table-tbody');

                    $('#'+fieldId).append(obj);
                    $('#wk-add-rfq-product-form')[0].reset();
                    $('.wk-supplier-image-delete').trigger('click');

                    // append request for quote prodct data rfq form

                    var progressTmpl = mageTemplate('#wk-rfq-pro-add-to-form-template'),
                        tmpl;
                    tmpl = progressTmpl({
                        data: dataTemp
                    });
                    $(tmpl).appendTo('#wk-supplier-rfq-form');
                    $('#wk-rfq-pro'+fieldId).append(obj);
                    return false;
                }
            });
            $('.wk-supplier-product-images-container').on("click", ".wk-supplier-image-delete", function() {
                $(this).parents('.wk-supplier-image').remove();
            });
            $('#wk-add-rfq-product-form').on("click", ".wk-rfq-product-delete", function() {
                var fieldId = $(this).parents('tr').attr('id');
                $(this).parents('tr').remove();
                $('#wk-rfq-pro'+fieldId).remove();
            });
            var productSampleIndex = 0;
            $('#wk-supplier-product-image-field').fileupload({
                dataType: 'json',
                sequentialUploads: true,
                acceptFileTypes: /(\.|\/)(gif|jpe?g|png|pdf|doc|zip)$/i,
                add: function (e, data) {
                    var progressTmpl = mageTemplate('#wk-supplier-image-uploader-template'),
                        tmpl;

                    $.each(data.files, function (index, file) {
                        data.fileId = Math.random().toString(33).substr(2, 18);

                        tmpl = progressTmpl({
                            data: {
                                id: data.fileId
                            }
                        });

                        $(tmpl).appendTo('#wk-supplier-image-uploader');
                    });

                    $(this).fileupload('process', data).done(function () {
                        data.submit();
                    });
                },
                done: function (e, data) {
                    if (data.result && !data.result.error) {
                        productSampleIndex++;
                        var progressTmpl = mageTemplate('#wk-supplier-images-field-template'),
                        tmpl;
                        tmpl = progressTmpl({
                            data: {
                                disabled: data.result.disabled ? data.result.disabled : 0,
                                index: productSampleIndex,
                                name: data.result.name,
                                file: data.result.file,
                                url: data.result.url,
                                extension: data.result.type
                            }
                        });

                        $(tmpl).prependTo('.wk-supplier-product-images-container');
                    } else {
                        $('#' + data.fileId)
                            .delay(2000)
                            .hide('highlight');
                        alert({
                            content: $.mage.__('We don\'t recognize or support this file extension type.')
                        });
                    }
                    $('#' + data.fileId).remove();
                },
                progress: function (e, data) {
                    var progress = parseInt(data.loaded / data.total * 100, 10);
                    var progressSelector = '#' + data.fileId + ' .progressbar-container .progressbar';
                    $(progressSelector).css('width', progress + '%');
                },
                fail: function (e, data) {
                    var progressSelector = '#' + data.fileId;
                    $(progressSelector).removeClass('upload-progress').addClass('upload-failure')
                        .delay(2000)
                        .hide('highlight')
                        .remove();
                }
            });
            $('#wk-supplier-product-image-field').fileupload('option', {
                process: [{
                    action: 'load',
                    fileTypes: /^image\/(gif|jpeg|png)$/
                }, {
                    action: 'resize',
                    maxWidth: <?= /* @noEscape */ \Magento\Framework\File\Uploader::MAX_IMAGE_WIDTH ?> ,
                    maxHeight: <?= /* @noEscape */ \Magento\Framework\File\Uploader::MAX_IMAGE_HEIGHT ?>
                }, {
                    action: 'save'
                }]
            });
            $('.wk-rfq-file-field-container').on("click", ".wk-uploaded-file-del", function() {
                $(this).parent('.wk-uploaded-file').remove();
            });
            var attachmentIndex = 0;
            $('#wk-rfq-file-field').fileupload({
                dataType: 'json',
                sequentialUploads: true,
                acceptFileTypes: /(\.|\/)(gif|jpe?g|png|pdf|doc|zip)$/i,
                add: function (e, data) {
                    var progressTmpl = mageTemplate('#wk-rfq-file-field-uploader-template'),
                        tmpl;

                    $.each(data.files, function (index, file) {
                        data.fileId = Math.random().toString(33).substr(2, 18);

                        tmpl = progressTmpl({
                            data: {
                                id: data.fileId
                            }
                        });

                        $(tmpl).appendTo('.wk-rfq-file-field-container');
                    });

                    $(this).fileupload('process', data).done(function () {
                        data.submit();
                    });
                },
                done: function (e, data) {
                    if (data.result && !data.result.error) {
                        attachmentIndex++;
                        var progressTmpl = mageTemplate('#wk-rfq-file-field-template'),
                        tmpl;
                        tmpl = progressTmpl({
                            data: {
                                index: attachmentIndex,
                                name: data.result.name,
                                file: data.result.file,
                                extension: data.result.type
                            }
                        });

                        $(tmpl).appendTo('.wk-rfq-file-field-container');
                    } else {
                        $('#' + data.fileId)
                            .delay(2000)
                            .hide('highlight');
                        alert({
                            content: $.mage.__('We don\'t recognize or support this file extension type.')
                        });
                    }
                    $('#' + data.fileId).remove();
                },
                progress: function (e, data) {
                    var progress = parseInt(data.loaded / data.total * 100, 10);
                    var progressSelector = '#' + data.fileId + ' .progressbar-container .progressbar';
                    $(progressSelector).css('width', progress + '%');
                },
                fail: function (e, data) {
                    var progressSelector = '#' + data.fileId;
                    $(progressSelector).removeClass('upload-progress').addClass('upload-failure')
                        .delay(2000)
                        .hide('highlight')
                        .remove();
                }
            });
            $('#wk-rfq-file-field').fileupload('option', {
                process: [{
                    action: 'load',
                    fileTypes: /^image\/(gif|jpeg|png)$/
                }, {
                    action: 'resize',
                    maxWidth: <?= /* @noEscape */ \Magento\Framework\File\Uploader::MAX_IMAGE_WIDTH ?> ,
                    maxHeight: <?= /* @noEscape */ \Magento\Framework\File\Uploader::MAX_IMAGE_HEIGHT ?>
                }, {
                    action: 'save'
                }]
            });
        });
    </script>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "wk-request-quote-product-wizard": {
                            "component": "requestQuoteProduct",
                            "emptyProductReturnLabel": "<?= /* @noEscape */
                            __('No record found! Please search for another keyword.')?>",
                            "fieldSelector": ".wk-product-search-box",
                            "destinationSelector": "#wk_search_autocomplete",
                            "priceFormat": <?= /* @noEscape */ $priceFormat?>,
                            "shop_url": "<?= /* @noEscape */ $shopUrl?>",
                            "url": "<?= /* @noEscape */ $searchUrl?>"
                        }
                    }
                }
            }
        }
    </script>
<?php }  ?>
