<?php
$_mbHelper = $this->helper('MageBig\MbFrame\Helper\Data');
$productLayout = $_mbHelper->getConfig('mbconfig/product_view/product_layout');
$social = $_mbHelper->getConfig('mbconfig/product_view/share_social');
?>
<div class="product-info-main-top product-info-main">
    <?php if ($social): ?>
        <div class="row align-items-center">
            <div class="col-12 col-lg-8 col-xl-9">

                <div class="info-after-title">
                    <?= $this->getChildHtml('product.info.review') ?>
                </div>
            </div>
            <!-- Moving Social Icons Div From Here to Stars Place -->
            <!-- <div class="col-12 col-lg-4 col-xl-3">
                <?php // = $this->getChildHtml('product.info.social.share')  ?>
            </div> -->
         
        </div>
    <?php else: ?>
        <?= $this->getChildHtml('page.main.title') ?>
        <div class="info-after-title">
            <?= $this->getChildHtml('product.info.review') ?>
            <?= $this->getChildHtml('product.info.sku') ?>
        </div>
    <?php endif ?>
</div>
<?php if ($productLayout): ?>
    <div class="product-info-main-content">
        <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6">
                <?= $this->getChildHtml('product.info.media') ?>
            </div>
            <div class="col-12 col-md-12 col-lg-6 col-xl-6">

                <?= $this->getChildHtml('page.main.title') ?>
        
                 <div class="icon-parent-div">
                 <?= $this->getChildHtml('product.info.social.share')  ?>
                 </div>

                <!--
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span> -->


                <?= $this->getChildHtml('product.info.sku') ?>
                <?= $this->getChildHtml('product.info.main') ?>
                <?= $_mbHelper->getCategoryStore($block->getProduct()); ?>
            </div>
            <div class="col-12 col-xl-0">
                <div class="sidebar-product-wrap">
                    <?php //= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sidebar-product')->toHtml(); ?>
                </div>
            </div>
        </div>
    </div>
<?php else: ?>
    <div class="product-info-main-content">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-5">
                <?= $this->getChildHtml('product.info.media') ?>
            </div>
            <div class="col-12 col-md-6 col-lg-7">
                <?= $this->getChildHtml('product.info.main') ?>
                <?= $_mbHelper->getCategoryStore($block->getProduct()); ?>
            </div>
        </div>
    </div>
<?php endif ?>