<?php
namespace AALogics\Cform\Setup;

use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\ModuleDataSetupInterface;
use Magento\Integration\Model\ConfigBasedIntegrationManager;
use Magento\Framework\Setup\InstallDataInterface;

class InstallData implements InstallDataInterface
{

	/**
	 * @param ConfigBasedIntegrationManager $integrationManager
	 */

	public function __construct()
	{

	}

	/**
	 * {@inheritdoc}
	 */

	public function install(ModuleDataSetupInterface $setup, ModuleContextInterface $context)
	{
		$setup->startSetup();
		$regions = [
					['country_id' => 'PK', 'code' => 'PK-GB', 'default_name' => 'Gilgit - Baltist'],
					['country_id' => 'PK', 'code' => 'PK-AK', 'default_name' => 'Azad Kashmir'],
					['country_id' => 'PK', 'code' => 'PK-FC', 'default_name' => 'Federally Administered Tribal Areas'],
					['country_id' => 'PK', 'code' => 'PK-BN', 'default_name' => 'Balochistan'],
					['country_id' => 'PK', 'code' => 'PK-KA', 'default_name' => 'Khyber Pakhtunkhwa'],
					['country_id' => 'PK', 'code' => 'PK-PB', 'default_name' => 'Punjab'],
					['country_id' => 'PK', 'code' => 'PK-SH', 'default_name' => 'Sindh'],
					];
		foreach ($regions as $region ) {
			$setup->getConnection()
			->insertArray($setup->getTable('directory_country_region'), ['country_id', 'code', 'default_name'], array($region));
		}

		$cities_query = "INSERT INTO `pakistan_cities` (`city_id`, `code`, `area`, `default_name`) VALUES
		(1, 'TAL', 'RWP', 'TALL'),
		(2, 'TDJ', 'HDD', 'TANDO JAM'),
		(3, 'TOP', 'RWP', 'TOPI'),
		(4, 'PSN', 'KHI', 'PASNI'),
		(5, 'NPI', 'UET', 'PISHIN'),
		(6, 'PJG', 'KHI', 'PANJGOOR'),
		(7, 'MTG', 'UET', 'MASTUNG'),
		(8, 'KLT', 'UET', 'KALAT'),
		(9, 'KLA', 'MUX', 'KAMALIA'),
		(10, 'HRN', 'MUX', 'HAROONABAD'),
		(11, 'RNI', 'SKZ', 'RANIPUR'),
		(12, 'RTD', 'SKZ', 'RATTO DERO'),
		(13, 'GMO', 'FSD', 'GARH MOR'),
		(14, 'PAN', 'FSD', 'PAINSRA'),
		(15, 'QDS', 'GUJ', 'QILA DEDAR SING'),
		(16, 'SAK', 'HDD', 'SAKRAND'),
		(17, 'SBI', 'UET', 'SIBI'),
		(18, 'SKT', 'FSD', 'SHAHKOT'),
		(19, 'TDM', 'HDD', 'TANDO ADAM'),
		(20, 'RDU', 'RWP', 'SAKARDU'),
		(21, 'DMJ', 'SKZ', 'DERAMURAD JAMAL'),
		(22, 'KHM', 'SKZ', 'KASHMORE'),
		(23, 'LKI', 'FSD', 'LAKI MARWAT'),
		(24, 'MRP', 'SKZ', 'MEHRAB PUR'),
		(25, 'NKS', 'LHE', 'NANKANA SAHIB'),
		(26, 'CKL', 'RWP', 'CHAKWAL'),
		(27, 'BRW', 'MUX', 'BUREWALA'),
		(28, 'BNP', 'RWP', 'BANNU'),
		(29, 'BHV', 'MUX', 'BAHAWALPUR'),
		(30, 'ATT', 'RWP', 'ATTOCK'),
		(31, 'MUX', 'MUX', 'MULTAN'),
		(32, 'QPR', 'MUX', 'QADIRPUR RAWAN'),
		(33, 'NWV', 'GUJ', 'NOWSHERA VIRKA'),
		(34, 'DKT', 'MUX', 'DAKOTA'),
		(35, 'DNG', 'GUJ', 'DINGA'),
		(36, 'TSP', 'MUX', 'TIBBA SULTAN'),
		(37, 'QBL', 'MUX', 'QABOOLA'),
		(38, 'GAD', 'MUX', 'GHAZI ABAD'),
		(39, 'KSW', 'MUX', 'KASOWAL'),
		(40, 'ING', 'MUX', 'IQBAL NAGAR'),
		(41, 'NOP', 'MUX', 'NOORPUR'),
		(42, 'KTL', 'GUJ', 'KOTLA'),
		(43, 'MLK', 'GUJ', 'MALAK WAL'),
		(44, 'CKR', 'GUJ', 'CHAK SAWARI'),
		(45, 'FZP', 'MUX', 'FAZIL PUR'),
		(46, 'GHK', 'GUJ', 'GHAKAR '),
		(47, 'PHL', 'GUJ', 'PHALIA '),
		(48, 'JLJ', 'GUJ', 'JALALPUR JATTAN'),
		(49, 'ZFW', 'GUJ', 'ZAFARWAL'),
		(50, 'VDR', 'PEW', 'VARI DIR'),
		(51, 'UPD', 'PEW', 'UPPER DIR'),
		(52, 'BJR', 'PEW', 'BAJWAR '),
		(53, 'TBI', 'PEW', 'TAKHAT BAI '),
		(54, 'BUR', 'PEW', 'BUNAIR'),
		(55, 'JRI', 'PEW', 'JHANGIRA'),
		(56, 'MSO', 'HDD', 'MIRPUR SAKRO '),
		(57, 'GRO', 'KHI', 'GHARO'),
		(58, 'WDR', 'KHI', 'WINDER'),
		(59, 'BLA', 'KHI', 'BELA'),
		(60, 'UTL', 'KHI', 'UTHAL'),
		(61, 'MHD', 'MUX', 'MINCHANABAD'),
		(62, 'HSM', 'MUX', 'HUJRA SHAMUQEEM'),
		(63, 'OKC', 'MUX', 'OKARA CANTT'),
		(64, 'APS', 'FSD', 'AHMED PUR SIAL '),
		(65, 'BWA', 'FSD', 'BHAWANA'),
		(66, 'BRA', 'FSD', 'BHERA'),
		(67, 'SNL', 'FSD', 'SILANWALI '),
		(68, 'CJS', 'FSD', 'CHAK JHUMRA'),
		(69, 'KMN', 'FSD', 'KOT MOMIN '),
		(70, 'SUA', 'LHE', 'SUNDAR ADDA'),
		(71, 'ELA', 'LHE', 'ELLAH ABAD'),
		(72, 'FWA', 'LHE', 'FEROZ WATOWAN'),
		(73, 'FAD', 'LHE', 'FARROQABAD'),
		(74, 'KNU', 'LHE', 'KANA NAU'),
		(75, 'SQR', 'LHE', 'SHARAQPUR'),
		(76, 'DKL', 'FSD', 'DAUD KHEL'),
		(77, 'KNI', 'HDD', 'KUNRI'),
		(78, 'KPR', 'HDD', 'KHIPRO'),
		(79, 'MRI', 'HDD', 'MITYARI'),
		(80, 'DIG', 'HDD', 'DIGRI'),
		(81, 'BRD', 'HDD', 'BHIRIA ROAD'),
		(82, 'LLI', 'FSD', 'LALIAN'),
		(83, 'RLK', 'MUX', 'RENALA KHURD'),
		(84, 'CSS', 'MUX', 'SARWAR SHAHEED'),
		(85, 'FPR', 'MUX', 'FATEHPUR'),
		(86, 'DWA', 'MUX', 'DAHRANWALA'),
		(87, 'JTI', 'MUX', 'JATOI'),
		(88, 'KDC', 'LHE', 'KOT RADHA KISHA'),
		(89, 'SKZ', 'SKZ', 'SUKKUR'),
		(90, 'RWP', 'RWP', 'RAWALPINDI'),
		(91, 'KHI', 'KHI', 'KARACHI'),
		(92, 'SHL', 'FSD', 'SANGLA HILL'),
		(93, 'JCB', 'SKZ', 'JACOBABAD'),
		(94, 'ISB', 'RWP', 'ISLAMABAD'),
		(95, 'HDD', 'HDD', 'HYDERABAD'),
		(96, 'HRI', 'RWP', 'HARIPUR'),
		(97, 'HZD', 'GUJ', 'HAFIZABAD'),
		(98, 'GJT', 'GUJ', 'GUJRAT'),
		(99, 'GUJ', 'GUJ', 'GUJRANWALA'),
		(100, 'FSD', 'FSD', 'FAISALABAD'),
		(101, 'DIN', 'GUJ', 'DINA'),
		(102, 'DKA', 'GUJ', 'DASKA'),
		(103, 'DGK', 'MUX', 'DERA GHAZI KHAN'),
		(104, 'NFZ', 'HDD', 'NOSHERO FEROZ'),
		(105, 'HAJ', 'RWP', 'HAJIRA'),
		(106, 'UET', 'UET', 'QUETTA'),
		(107, 'PEW', 'PEW', 'PESHAWAR'),
		(108, 'SLT', 'GUJ', 'SIALKOT'),
		(109, 'PRR', 'GUJ', 'PASROOR'),
		(110, 'TTS', 'FSD', 'TOBATEK-SINGH'),
		(111, 'JWA', 'FSD', 'JARANWALA'),
		(112, 'PNQ', 'SKZ', 'PANNU AKIL'),
		(113, 'DKI', 'SKZ', 'DAHARKI'),
		(114, 'MPM', 'SKZ', 'MIRPUR MATHELO'),
		(115, 'KKK', 'SKZ', 'KANDH KOT'),
		(116, 'SHH', 'SKZ', 'SHAHDAD KOT'),
		(117, 'GTI', 'SKZ', 'GHOTKI'),
		(118, 'TAN', 'FSD', 'TANK'),
		(119, 'HSN', 'RWP', 'HASSAN ABDAL'),
		(120, 'SIT', 'HDD', 'SITA ROAD'),
		(121, 'NJT', 'HDD', 'NEW JATOI'),
		(122, 'RDN', 'SKZ', 'RADHAN STATION'),
		(123, 'TSA', 'HDD', 'THARO SHAH'),
		(124, 'KGM', 'HDD', 'KOT GHULAM MUHD'),
		(125, 'KRC', 'GUJ', 'KHARIAN CANTT'),
		(126, 'SAG', 'GUJ', 'SRAI ALAMGEER'),
		(127, 'SQD', 'PEW', 'SHABQADAR'),
		(128, 'IKD', 'FSD', 'ISKANDARABAD'),
		(129, 'TRL', 'RWP', 'TERNOL'),
		(130, 'HNZ', 'RWP', 'HUNZA'),
		(131, 'MIT', 'HDD', 'MITHI'),
		(132, 'IMK', 'HDD', 'ISLAMKOT'),
		(133, 'AMO', 'HDD', 'SAMARO'),
		(134, 'MGR', 'HDD', 'MIRWAH GORCHANI'),
		(135, 'KPL', 'RWP', 'KHAPLU'),
		(136, 'NBD', 'SKZ', 'NASIRABAD'),
		(137, 'ZPR', 'SKZ', 'ZAHIRPEER'),
		(138, 'JDW', 'SKZ', 'JAMALDIN WALI'),
		(139, 'GBT', 'SKZ', 'GAMBAT'),
		(140, 'MGT', 'SKZ', 'MACHI GOTH'),
		(141, 'GMD', 'MUX', 'GAGGO MANDI'),
		(142, 'KAR', 'MUX', 'KAROR LALESAN'),
		(143, 'AWR', 'KHI', 'AWARAN'),
		(144, 'QAZ', 'HDD', 'QAZI AHMED'),
		(145, 'SES', 'HDD', 'SEHWAN'),
		(146, 'CDS', 'RWP', 'CHOA SYDEN SHAH'),
		(147, 'KTA', 'RWP', 'KAHOTA'),
		(148, 'CHT', 'MUX', 'CHISHTIAN'),
		(149, 'MWI', 'FSD', 'MIANWALI'),
		(150, 'CSD', 'PEW', 'CHARSADDA'),
		(151, 'SGD', 'FSD', 'SARGODAH'),
		(152, 'JLM', 'GUJ', 'JHELUM'),
		(153, 'JHG', 'FSD', 'JHANG'),
		(154, 'LAR', 'SKZ', 'LARKANA'),
		(155, 'LLM', 'GUJ', 'LALAMUSA'),
		(156, 'KOT', 'MUX', 'KOT ADDU'),
		(157, 'OHT', 'RWP', 'KOHAT'),
		(158, 'KRN', 'GUJ', 'KHARIAN'),
		(159, 'NPR', 'SKZ', 'KHANPUR'),
		(160, 'KHP', 'SKZ', 'KHAIRPUR'),
		(161, 'KSR', 'LHE', 'KASUR'),
		(162, 'KMK', 'GUJ', 'KAMOKE'),
		(163, 'MRY', 'LHE', 'MURIDKEY'),
		(164, 'MPK', 'HDD', 'MIRPUR KHAS'),
		(165, 'QML', 'GUJ', 'MIRPUR A.K.'),
		(166, 'SWT', 'PEW', 'MINGORA (SWAT)'),
		(167, 'MDN', 'PEW', 'MARDAN'),
		(168, 'MGL', 'GUJ', 'MANGLA'),
		(169, 'MBD', 'GUJ', 'MANDI BAHAUDDIN'),
		(170, 'MCN', 'MUX', 'MIAN CHANOO'),
		(171, 'FRZ', 'SKZ', 'FEROZA'),
		(172, 'BTK', 'PEW', 'BATKHELA'),
		(173, 'BSH', 'KHI', 'BHIT SHAH'),
		(174, 'DAH', 'FSD', 'DARY KHAN'),
		(175, 'KQS', 'MUX', 'KHANQA SHARIF'),
		(176, 'KHT', 'MUX', 'KOT CHUTTA'),
		(177, 'PAC', 'SKZ', 'PANU AQIL CANTT'),
		(178, 'APC', 'GUJ', 'ALI PUR CHATTA'),
		(179, 'DLT', 'GUJ', 'DOLAT NAGAR'),
		(180, 'DLW', 'FSD', 'DULLE WALA'),
		(181, 'JLA', 'FSD', 'JAND WALA'),
		(182, 'PBN', 'FSD', 'PINDI BHATIAN'),
		(183, 'KBL', 'SKZ', 'KHAN BELA'),
		(184, 'GKN', 'RWP', 'GUJARKHAN'),
		(185, 'WZD', 'GUJ', 'WAZIRABAD'),
		(186, 'APE', 'MUX', 'AHMED PUR EAST'),
		(187, 'LYY', 'MUX', 'LAYYAH'),
		(188, 'LOD', 'MUX', 'LODHRAN'),
		(189, 'MNA', 'RWP', 'MANSHERA'),
		(190, 'AFA', 'MUX', 'ARIF WALA'),
		(191, 'HUB', 'KHI', 'HUB'),
		(192, 'HLA', 'HDD', 'HALA'),
		(193, 'SHJ', 'MUX', 'SHUJAABAD'),
		(194, 'ABT', 'RWP', 'ABBOTABAD'),
		(195, 'SAB', 'FSD', 'KHUSHAB'),
		(196, 'MKT', 'MUX', 'MEHMOODKOT'),
		(197, 'JRD', 'FSD', 'JOUHARABAD'),
		(198, 'TRB', 'RWP', 'TARBELA'),
		(199, 'SPR', 'HDD', 'SHAHDADPUR'),
		(200, 'SAN', 'HDD', 'SANGHAR'),
		(201, 'HSL', 'MUX', 'HASILPUR'),
		(202, 'RND', 'LHE', 'RAIWAND'),
		(203, 'BPR', 'LHE', 'BHAI PHARU'),
		(204, 'CMN', 'UET', 'CHAMAN'),
		(205, 'MRO', 'HDD', 'MORO'),
		(206, 'TWL', 'FSD', 'TANDLIANWALA'),
		(207, 'SAL', 'GUJ', 'SUMBRIAL'),
		(208, 'BWL', 'FSD', 'BHALWAL'),
		(209, 'RKT', 'RWP', 'RAWALAKOT'),
		(210, 'NRL', 'GUJ', 'NAROWAL'),
		(211, 'REE', 'RWP', 'MURREE'),
		(212, 'GDU', 'SKZ', 'GUDDU'),
		(213, 'RRA', 'FSD', 'GOJRA'),
		(214, 'CCW', 'MUX', 'CHICHAWATNI'),
		(215, 'NGR', 'MUX', 'BAHAWALNAGAR'),
		(216, 'BDN', 'HDD', 'BADIN'),
		(217, 'RJP', 'MUX', 'RAJANPUR'),
		(218, 'JMP', 'MUX', 'JAMPUR'),
		(219, 'AIP', 'MUX', 'ALIPUR'),
		(220, 'LRI', 'UET', 'LORA LAI'),
		(221, 'MHR', 'SKZ', 'MEHAR'),
		(222, 'USM', 'SKZ', 'USTA MOHAMMAD'),
		(223, 'AAA', 'KHI', ' UNKNOWN'),
		(224, 'UKT', 'HDD', 'UMERKOT'),
		(225, 'KRK', 'RWP', 'KARAK'),
		(226, 'BGH', 'RWP', 'BAGH'),
		(227, 'YZM', 'MUX', 'YAZMAN MANDI'),
		(228, 'CAZ', 'MUX', 'CHOWK AZAM'),
		(229, 'HTR', 'RWP', 'HATTER'),
		(230, 'TMK', 'HDD', 'TANDO MOHD KHAN'),
		(231, 'FTG', 'RWP', 'FATEH JANG'),
		(232, 'DDK', 'PEW', 'DARA ADM KHEL'),
		(233, 'GWR', 'KHI', 'GAWADAR'),
		(234, 'KWL', 'MUX', 'KHANEWAL'),
		(235, 'MCD', 'MUX', 'MINCHANABAD'),
		(236, 'DOK', 'MUX', 'DHODHAK'),
		(237, 'KNS', 'SKZ', 'KHAIRPUR NATHAN'),
		(238, 'IKL', 'FSD', 'ISSA KHEL'),
		(239, 'JPT', 'SKZ', 'JHAT PAT'),
		(240, 'KAK', 'SKZ', 'KAMBAR ALI KHAN'),
		(241, 'THL', 'SKZ', 'THULL'),
		(242, 'NDR', 'SKZ', 'NAUDERO'),
		(243, 'PJT', 'SKZ', 'PIRYALO'),
		(244, 'DRG', 'PEW', 'DARGAI'),
		(245, 'KLY', 'RWP', 'KOTLI-A.KASHMIR'),
		(246, 'ZOB', 'UET', 'ZHOB'),
		(247, 'NOK', 'UET', 'NOSHKI'),
		(248, 'GKR', 'SKZ', 'GARI KHAIRO'),
		(249, 'FAB', 'MUX', 'FORTE ABBAS'),
		(250, 'TMG', 'PEW', 'TEMARGARAH'),
		(251, 'HMK', 'ISB', 'HUMAK'),
		(252, 'JHN', 'MUX', 'JHANIAN'),
		(253, 'AHT', 'MUX', 'ABDUL HAKIM'),
		(254, 'DPA', 'MUX', 'DEPAL PUR'),
		(255, 'MLT', 'MUX', 'MAILSI'),
		(256, 'SQT', 'FSD', 'SHORKOT'),
		(257, 'DDU', 'HDD', 'DADU'),
		(258, 'GDN', 'RWP', 'GADOON AMAZAI'),
		(259, 'PDK', 'RWP', 'KHEWRA DANDOT'),
		(260, 'KPC', 'MUX', 'KAROR PAKKA'),
		(261, 'TUK', 'KHI', 'TURBAT'),
		(262, 'UDR', 'UET', 'KHUZDAR'),
		(263, 'CWD', 'GUJ', 'CHAWINDA'),
		(264, 'HVL', 'RWP', 'HAVELLIAN'),
		(265, 'KKU', 'LHE', 'KALA SHAH KAKU'),
		(266, 'LQR', 'SKZ', 'LIAQUATPUR'),
		(267, 'SGR', 'GUJ', 'SHAKAR GARH'),
		(268, 'PTI', 'LHE', 'PATOKI'),
		(269, 'PPS', 'MUX', 'PAK PATTAN SHARIF'),
		(270, 'SAM', 'FSD', 'SAMANDRI'),
		(271, 'GIL', 'RWP', 'GILGIT'),
		(272, 'BKK', 'FSD', 'BHAKKAR'),
		(273, 'TDA', 'HDD', 'TANDO ALLAYAR'),
		(274, 'AWH', 'FSD', 'CHENAB NAGAR'),
		(275, 'IOT', 'FSD', 'CHINIOT'),
		(276, 'THT', 'HDD', 'THATTA'),
		(277, 'CTL', 'PEW', 'CHITRAL'),
		(278, 'KBB', 'MUX', 'KABIR WALA'),
		(279, 'LHE', 'LHE', 'LAHORE'),
		(280, 'MUH', 'UET', 'MUCH'),
		(281, 'BKH', 'UET', 'BARKHAN'),
		(282, 'OKH', 'KHI', 'OLE KHI'),
		(283, 'OLH', 'LHE', 'OLE LHE'),
		(284, 'ORW', 'RWP', 'OLE RWP'),
		(285, 'SUI', 'SKZ', 'SUI'),
		(286, 'KHR', 'UET', 'KHARAN'),
		(287, 'SWA', 'RWP', 'SWABI'),
		(288, 'OKR', 'MUX', 'OKARA'),
		(289, 'NOW', 'PEW', 'NOWSHERA'),
		(290, 'WNS', 'HDD', 'NAWABSHAH'),
		(291, 'MZG', 'MUX', 'MUZAFFARGARH'),
		(292, 'MAK', 'RWP', 'MUZAFFARABAD AK'),
		(293, 'VRI', 'MUX', 'VEHARI'),
		(294, 'TXL', 'RWP', 'TAXILA'),
		(295, 'WAH', 'RWP', 'WAH'),
		(296, 'TLG', 'RWP', 'TALAGANG'),
		(297, 'SRA', 'LHE', 'SHEIKHUPURA'),
		(298, 'SIP', 'SKZ', 'SHIKARPUR'),
		(299, 'SWL', 'MUX', 'SAHIWAL'),
		(300, 'SDA', 'SKZ', 'SADIQABAD'),
		(301, 'RYK', 'SKZ', 'RAHIMYARKHAN'),
		(302, 'UCH', 'MUX', 'UCH SHARIF'),
		(303, 'AMB', 'FSD', 'AMINPUR BANGLOW'),
		(304, 'ERA', 'FSD', 'NAUSHERA'),
		(305, 'BBA', 'MUX', 'ADDA BUN BOSAN'),
		(306, 'RAJ', 'FSD', 'RAJANA'),
		(307, 'DIJ', 'FSD', 'DIJKOT'),
		(308, 'ALR', 'MUX', 'ADDA LAR'),
		(309, 'SNW', 'MUX', 'SANAWAN'),
		(310, 'SUJ', 'HDD', 'SUJAWAL'),
		(311, 'BRC', 'HDD', 'BHIRIA CITY'),
		(312, 'KND', 'HDD', 'KANDYARO'),
		(313, 'CHO', 'HDD', 'CHACHRO'),
		(314, 'HNG', 'RWP', 'HANGU'),
		(315, 'SNK', 'RWP', 'SHINKIARI'),
		(316, 'OGI', 'RWP', 'OGHI'),
		(317, 'LNK', 'PEW', 'LANDIKOTAL'),
		(318, 'APL', 'SKZ', 'AHMED PUR LAMMA'),
		(319, 'DUN', 'MUX', 'DUNYA PUR'),
		(320, 'BRK', 'RWP', 'BARA KAHU'),
		(321, 'AZR', 'FSD', '18 HAZARI'),
		(322, 'KTW', 'MUX', 'KHAIPUR TAMEWAL'),
		(323, 'QAL', 'RWP', 'QALANDRABAD'),
		(324, 'PUL', 'RWP', 'PALANDRI'),
		(325, 'GYS', 'SKZ', 'GARI YASIN'),
		(326, 'ORI', 'SKZ', 'DOKRI'),
		(327, 'WRH', 'SKZ', 'WARAH'),
		(328, 'KSB', 'SKZ', 'KOT SAMABAH'),
		(329, 'BSR', 'MUX', 'BASIR PUR'),
		(330, 'GPR', 'SKZ', 'GHOUS PUR'),
		(331, 'URO', 'SKZ', 'UBARO'),
		(332, 'KDW', 'FSD', 'KHIDDER WALA'),
		(333, 'PLN', 'FSD', 'PIPLAN'),
		(334, 'SMA', 'FSD', 'CHASHMA'),
		(335, 'SFD', 'FSD', 'SAHIWAL - FSD'),
		(336, 'NLB', 'FSD', 'NARWALA BANGLA'),
		(337, 'WBC', 'FSD', 'WAN BACHRAN'),
		(338, 'KDI', 'HDD', 'KANDIARI'),
		(339, 'JAR', 'SKZ', 'JARWAR'),
		(340, 'ADZ', 'MUX', 'ADDA ZAKHEERA'),
		(341, 'KZK', 'PEW', 'KHAZAKHELA'),
		(342, 'RVT', 'RWP', 'RAWAT'),
		(343, 'PGB', 'RWP', 'PINDI GHEB'),
		(344, 'MDA', 'MUX', 'MAKHDOOM AALI'),
		(345, 'GOG', 'MUX', 'BANGLOW GOGERA'),
		(346, 'GOL', 'HDD', 'GOLARCHI'),
		(347, 'KTM', 'MUX', 'KOT MITTHAN'),
		(348, 'DNT', 'MUX', 'DHANOT'),
		(349, 'MMP', 'MUX', 'MUBARAK PUR'),
		(350, 'JVR', 'FSD', 'JAWARIAN'),
		(351, 'IAA', 'FSD', 'MURID WALA'),
		(352, 'MKN', 'FSD', 'MAMUN KANJAN'),
		(353, 'KMI', 'FSD', 'KAMER MOSHANI'),
		(354, 'KBH', 'FSD', 'KALA BAGH'),
		(355, 'HNL', 'FSD', 'HARNOULI'),
		(356, 'OOR', 'FSD', 'KALOOR KOT'),
		(357, 'BRN', 'FSD', 'BARNALA'),
		(358, 'PHP', 'FSD', 'PAHAR PUR'),
		(359, 'SBN', 'FSD', 'SATIANA BANGLA'),
		(360, 'NPT', 'FSD', 'NURPUR THAL'),
		(361, 'KLG', 'PEW', 'KATLANG'),
		(362, 'KLK', 'RWP', 'KALAR KAHAR'),
		(363, 'SJO', 'HDD', 'SINJHORO'),
		(364, 'JPP', 'MUX', 'JALALPURPIRWALA'),
		(365, 'BCM', 'FSD', 'BUCHIANA MANDI'),
		(366, 'MVL', 'GUJ', 'MANGOWAL'),
		(367, 'HOO', 'RWP', 'HAZRO'),
		(368, 'BST', 'MUX', 'BUDHLA SANT'),
		(369, 'KOO', 'MUX', 'KACHA KHO'),
		(370, 'COC', 'HDD', 'CHOR CANTT'),
		(371, 'DOR', 'HDD', 'DOUR'),
		(372, 'LMB', 'UET', 'MUSLIM BAGH'),
		(373, 'DIK', 'FSD', 'DERA ISMAIL KHAN'),
		(374, 'DLB', 'UET', 'DALBANDIN'),
		(375, 'SWT', 'PEW', 'SWAT'),
		(376, 'PTI', 'LHE', 'CHUNIAN'),
		(377, 'BDN', 'HDD', 'TANDO BAGHO'),
		(378, 'SWT', 'PEW', 'SAIDU SHARIF'),
		(379, 'SKZ', 'SKZ', 'ROHRI'),
		(380, 'HLA', 'HDD', 'NEW SAEEDABAD'),
		(381, 'BMR', 'GUJ', 'BHIMBER'),
		(382, 'UKI', 'UET', 'DUKKI'),
		(383, 'TDM', 'HDD', 'NAUABAD'),
		(384, 'RND', 'LHE', 'RAIWAND'),
		(385, 'BPR', 'LHE', 'MANGA MANDI'),
		(386, 'AMO', 'HDD', 'SAMARO'),
		(387, 'MRI', 'HDD', 'MATIARI'),
		(388, 'HDD', 'HDD', 'JAMSHORO'),
		(389, 'HDD', 'HDD', 'KOTRI'),
		(390, 'HDD', 'HDD', 'PETARO'),
		(391, 'KOT', 'MUX', 'TAUNSA SHARIF'),
		(392, 'PDK', 'RWP', 'PIND DADAN KHAN'),
		(393, 'SNG', 'RWP', 'SERAI NAURANG'),
		(394, 'WNS', 'HDD', 'DAULATPUR'),
		(395, 'HZD', 'GUJ', 'JALAL PUR BHATTIAN'),
		(396, 'MTI', 'HDD', 'MATLI'),
		(397, 'CSS', 'MUX', 'CHOWK SARWER SHAHEED'),
		(398, 'BKK', 'FSD', 'MANKERA'),
		(399, 'MNA', 'RWP', 'BATTGRAM'),
		(400, 'MWI', 'FSD', 'KUNDIAN'),
		(401, 'PBI', 'PEW', 'PABBI'),
		(402, 'DAY', 'SKZ', 'DERA ALLAHYAR'),
		(403, 'JRD', 'FSD', 'QUAIDABAD'),
		(404, 'RSP', 'PEW', 'RISALPUR'),
		(405, 'SRA', 'LHE', 'MANDI FAIZ ABAD'),
		(406, 'SAL', 'GUJ', 'SAMBRIAL'),
		(407, 'DRG', 'PEW', 'MALAKAND'),
		(408, 'SWT', 'SWT', 'SHANGLA'),
		(417, 'THT', 'KHI', 'CHOHAR JAMALI'),
		(418, 'KTW', 'MUX', 'KHAIR PUR TAMIANWALI'),
		(419, 'CKL', 'RWP', 'DHUDIAL'),
		(420, 'PML', 'FSD', 'PIR MAHAL'),
		(421, 'HNI', 'UET', 'HARNAI'),
		(422, 'LHE', 'LHE', 'SHAHDARA'),
		(423, 'LHE', 'LHE', 'KOT ABDUL MALIK'),
		(424, 'DRG', 'PEW', 'Lower DIR'),
		(425, 'BKT', 'RWP', 'BALAKOT'),
		(426, 'FTG', 'RWP', 'JAND'),
		(427, 'MKR', 'FSD', 'MANKERA'),
		(430, 'DYL', 'RWP', 'DADYAL (A.K)');";
		$setup->getConnection()->query($cities_query);
		
		$setup->endSetup();
	}
}