<?php $mbHelper = $this->helper('MageBig\MbFrame\Helper\Data');
$logoSticky = $mbHelper->getConfig('mbconfig/header/logo_sticky');
$pathLogo = $mbHelper->getBaseMediaUrl() . 'wysiwyg/magebig/logo/';
$blockLogo = $block->getLayout()->createBlock('Magento\Theme\Block\Html\Header\Logo');
$blockWelcome = $block->getLayout()->createBlock('Magento\Theme\Block\Html\Header');
$blockCustomer = $block->getLayout()->createBlock('Magento\Customer\Block\Account\Customer');
//$wishlistHelper = $this->helper('Magento\Wishlist\Helper\Data');
$menuLayout = $mbHelper->getConfig('mbconfig/header/menu_layout');
$topMenuBtn = $mbHelper->getConfig('mbconfig/mobile_view/btn_menu');
$bottomMenu = $mbHelper->getConfig('mbconfig/mobile_view/bottom_menu');
?>
<div class="container-fluid gradient-background maximum-width mx-xl-auto">
  <div class="row">
    <div class="col-xl-4  col-lg-4 col-sm-12 col-md-4 " id="flex-display">
      <p class="welcome text-center">Welcome to Imarkplace!</p>
    </div>
    <div class="col-xl-4  col-lg-4 col-sm-12 col-md-4">
      <div class="bismillah">
        <img alt="imarkplace" src="/media/wysiwyg/logo.png" height="50" class="toplogo" />
        <img alt="imarkplace" src="/media/wysiwyg/bismillah.png" width="200" height="50" class="bismillahimg" />
      </div>
    </div>
    <div class="col-xl-4  col-lg-4 col-sm-12 col-md-4 " id="flex-display">
      <p class="headtagline text-center ">Become a seller | Help & Support</p>
    </div>
  </div>
</div>



<div class="header-main-content sticky-menu">
  <div class="container-fluid">
    <!-- <div class="header-main-inner <= if ($menuLayout == 'horizontal'): ?>header-horizontal<= endif; ?>">-->
    <section class="screen-above-1100 mx-xl-auto maximum-width w-38 unique-display-none">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-3 col-xl-3 col-sm-12 col-md-3 flex-display1">
            <div class="logo">
              <?= $this->getChildHtml('logo') ?>
              <!--<img alt="imarkplace" src="/media/wysiwyg/logo.png" height="50" class="imarklogo" />-->
            </div>
          </div>
          <div class="col-lg-6 col-xl-6 col-sm-6 col-md-6 d-flex align-items-center flex-display3">
            <!--its html write under the custom/MageBig_AjaxSearch/templates/form.mini.phtml-->
            <div class="top-search-wrap mfp-with-anim">
              <?= $this->getChildHtml('topSearch') ?>
            </div>
          </div>
          <div class="col-lg-3 col-xl-3 col-sm-3 col-md-3 d-flex align-items-center flex-display3">
            <div class="icon-container">
              <?= $this->getChildHtml('wishlist_icon') ?>
              <!--<div class="col col-minicart minicart-action">
                <a class="action showcart" href="<x= $block->getUrl('checkout/cart') ?>"
                  data-bind="scope: 'minicart_content'">
                  <i class="mbi mbi-cart"></i>
                  <span class="counter qty empty"
                    data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
                    <span class="counter-number"
                      data-bind="html: getCartParam('summary_count') > 9 ? '&nbsp;9<sup>+</sup>' : getCartParam('summary_count')"></span>
                  </span>
                </a>
              </div>-->
              <?= $this->getChildHtml('minicart') ?>
              <div class="user-icon-mobile user-topbar col col-user">
                <i class="mbi mbi-user"></i>
                <?= $this->getChildHtml('header.links') ?>
              </div>
            </div>
          </div>
        </div>
      </div>

    </section>

    <br class="hideonmobile">

    <!-- <div class="row align-items-center header-maininner-row">
        <div class="col-12 col-md-3 col-lg-3 col-logo">
          <div class="menu-logo">
            <= if ($topMenuBtn): ?>
              <div class="btn-nav-mobile-top d-table-cell d-md-none"><button type="button"
                  class="btn-nav mb-toggle-switch mb-toggle-switch__htx" aria-label="menu"><span></span></button></div>
            <= endif ?>
            <div class="logo-top d-table-cell <= if ($topMenuBtn)
              echo 'has-btn' ?>">
                <--<=$this->getChildHtml('logo') ?>->
              </div>
              <div class="icon-top-mobile">
                <--<= $this->getChildHtml('wishlist_icon') ?>
              <div class="minicart-action">
                <a class="action showcart" href="<= $block->getUrl('checkout/cart') ?>"
                  data-bind="scope: 'minicart_content'">
                  <i class="mbi mbi-cart"></i>
                  <span class="counter qty empty"
                    data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
                    <span class="counter-number"
                      data-bind="html: getCartParam('summary_count') > 9 ? '&nbsp;9<sup>+</sup>' : getCartParam('summary_count')"></span>
                  </span>
                </a>
              </div>->
              <div class="user-icon-mobile user-topbar"><i class="mbi mbi-user"></i></div>
            </div>
          </div>
         
        </div>
        <div class="col-md-5 col-lg-5 col-xl-6 col-search">
          <div class="top-search-wrap mfp-with-anim">
            <--<= $this->getChildHtml('topSearch') ?>->
          </div>
        </div>
        <div class="col-btn-actions-desktop d-none d-md-block">
          <div class="hellosignin">
            <div class="accandlists"><a href="https://imarkplace.com/customer/account/login/">User Sign in</a></div>
          </div>
          <div class="sellsignup">
            <div class="sellersignup">
              <a href="https://imarkplace.com/b2bmarketplace/supplier/create/"> Become a seller
              </a>
            </div>
          </div>
          <div class="header-content-action row no-gutters test">
            <= $this->getChildHtml('wishlist_icon') ?>
            <= $this->getChildHtml('minicart') ?>
          </div>
        </div>
      </div>-->


    <!--</div>-->

  </div>

</div>



<nav
  class="navbar navbar-expand-lg navbar-dark  mx-xl-auto maximum-width w-38 d-flex justify-content-center align-items-center">
  <div class="header-main-inner <?php if ($menuLayout == 'horizontal'): ?>header-horizontal<?php endif; ?>">
  <?= $this->getChildHtml('smartmenu.topnav') ?>
</div>
  <div class="header-menu-content d-none d-md-block">
    <div class="container">
      <div class="menu-container">
        <?php if ($menuLayout == 'vertical'): ?>
          <div class="row align-items-center w-full">
            <div class="col-9 col-md-9 col-lg-6 d-none d-md-block">
              <!--<= $this->getChildHtml('smartmenu.topnav') ?>-->

              <div class="collapse navbar-collapse" id="navbarNav">
                
                  <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('horizontal-menu')->toHtml(); ?>
               
              </div>

            </div>
            <!--<div class="col-12 col-md-3 d-none d-lg-block website-switcher">
            <div class=""></div>
            <= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('hotline')->toHtml(); ?>
          </div>-->
          </div>
        <?php else: ?>
          <div class="row align-items-center">
            <div class="col-12">
              <?= $this->getChildHtml('smartmenu.topnav-hori') ?>
            </div>
          </div>
        <?php endif; ?>
      </div>
    </div>
  </div>
</nav>


<?php if ($bottomMenu): ?>
  <div class="d-block d-md-none col-btn-actions">
    <div class="header-content-action row no-gutters">
      <div class="btn-nav-mobile col">
        <button type="button" class="btn-nav mb-toggle-switch mb-toggle-switch__htx"
          aria-label="menu"><span></span></button>
        <div class="menu-btn-text">
          <?= $block->escapeHtml(__('Menu')) ?>
        </div>
      </div>
      <div class="btn-search-mobile col">
        <i class="mbi mbi-magnifier"></i>
        <div class="menu-btn-text">
          <?= __('Search') ?>
        </div>
      </div>
      <div class="col col-home">
        <a href="<?= $block->getBaseUrl() ?>" class="go-home"><i class="mbi mbi-home3"></i></a>
        <div class="menu-btn-text">
          <?= $block->escapeHtml(__('Home')) ?>
        </div>
      </div>

      <div class="col col-cart">
        <div class="minicart-action">
          <a class="action showcart" href="<?= $block->getUrl('checkout/cart') ?>" data-bind="scope: 'minicart_content'">
            <i class="mbi mbi-cart"></i>
            <span class="counter qty empty"
              data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
              <span class="counter-number"
                data-bind="html: getCartParam('summary_count') > 9 ? '&nbsp;9<sup>+</sup>' : getCartParam('summary_count')"></span>
            </span>
          </a>
        </div>
        <div class="menu-btn-text">
          <?= $block->escapeHtml(__('My Cart')) ?>
        </div>
      </div>

      <div class="user-topbar col">
        <i class="mbi mbi-user"></i>
        <div class="menu-btn-text">
          <?= $block->escapeHtml(__('Me')) ?>
        </div>
      </div>
    </div>
  </div>
<?php endif ?>