<?php
/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<style>
/* remove the below css from here when you uncomment the below code */
#C footer.page-footer .footer.content .custom-footer-top .footer-top-center {
    background: transparent;
    border: 1px solid lightgray;
    border-radius: 5px;
    padding: 40px 0;
    display: none;
}
</style>
<!--
<div class="main-newsletter">
    <div class="main-newsletter-inner">
        <div class="subscribe">
            <form
                novalidate
                action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
                method="post"
                data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                id="newsletter-validate-detail-footer">
                <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
                <div class="block-content">
                    <div class="input-box">
                        <input name="email" type="email" id="newsletter"
                               placeholder="<?= __('Enter your email here...') ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}"/>
                        <button class="hover-effect07"
                                title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                                type="submit">
                            <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#newsletter-validate-detail": {
            "MageBig_NewsPopup/js/ajax-newsletter": {}
        }
    }
</script>
-->
