<?php
use Magento\Framework\App\Action\Action;

$i = 0;

?>
<?php if (!$carousel): ?>
    <div class="product-items row">
    <?php endif ?>
    <?php foreach ($collection as $_product): ?>
        <?php if ($carousel == 1 && $row > 1 && $i == 0): ?>
            <div class="owl-carousel owl-theme">
            <?php endif ?>
            <?php if (($i % $column == 0 || ($row > 1 && $i % $row == 0)) && $carousel): ?>
                <div class="category-products  maximum-width mx-xl-auto">
                    <div
                        class="product-items  <?= $type; ?> <?= $carousel && $row == 1 ? ' owl-carousel owl-theme' : '' ?> <?= !$carousel ? ' row' : '' ?>">
                    <?php endif ?>
                    <?php $i++ ?>
                    <div class="product-item <?= !$carousel ? ' col-6 col-sm-4 col-md-3' : '' ?>">
                        <div class="product-item-info test123">
                            <div class="product-show wasif-test123">
                            <div class="card product-card h-97 ">
                                <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo">
                                    <p>
                                            <?php
                                            if ($labelHelper->getDiscountPercent($_product)): ?>
                                                <span
                                                    class="discount-percent"><?= $labelHelper->getDiscountPercent($_product); ?></span>
                                            <?php endif; ?>
                                    </p>
                                    <?php $productImage = $block->getImage($_product, $image); ?>
                                    <?= $productImage->toHtml(); ?>
                                    <div class="card-body">
                                        <h5 class="card-title"> <?= $block->escapeHtml($_product->getName()) ?></h5>
                                        <div class="star-rating">
                                            <span class="fa fa-star"></span>
                                            <span class="fa fa-star"></span>
                                            <span class="fa fa-star"></span>
                                            <span class="fa fa-star" id="black"></span>
                                            <span class="fa fa-star" id="black"></span>
                                        </div>
                                        <p class="price"><?= /* @escapeNotVerified */ $block->getProductPriceHtml(
                                            $_product,
                                            \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE,
                                            \Magento\Framework\Pricing\Render::ZONE_ITEM_LIST,
                                            ['price_id_suffix' => '-' . $pricePrefixId]
                                        ) ?></p>
                                    </div>
                                </a>
                            </div>
                             <?php if ($block->getData('product_style') != 4): ?>
                                    <div class="product-btn wasif-test">
                                        <div class="row no-gutters text-center">
                                            <div class="col-2 btn-qiuk-view" <?php if (!$showQuickview): ?>style="display: none;" <?php endif; ?>>
                                                <?= $this->helper('MageBig\QuickView\Helper\Data')->getQuickViewButton($_product, 'mb-tooltip'); ?>
                                            </div>
                                            <?php if ($showAddCart): ?>
                                                <?php if ($_product->isSaleable()): ?>
                                                    <div class="col-8 btn-add-to-cart">
                                                        <?php $url = $block->getAddToCartUrl($_product); ?>
                                                        <form data-role="tocart-form" action="<?= /* @escapeNotVerified */ $url; ?>"
                                                            method="post">
                                                            <input type="hidden" name="product"
                                                                value="<?= /* @escapeNotVerified */ $_product->getEntityId(); ?>">
                                                            <input type="hidden"
                                                                name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED; ?>"
                                                                value="<?= /* @escapeNotVerified */ $urlHelper->getEncodedUrl($url) ?>">
                                                            <?= $block->getBlockHtml('formkey') ?>
                                                            <button type="submit" title="<?= $block->escapeHtml(__('Add to Cart')); ?>"
                                                                class="action tocart mb-tooltip">
                                                                <span class="bag-img-icon">
                                                                    Add to cart
                                                                </span>
                                                            </button>
                                                        </form>
                                                    </div>
                                                <?php else: ?>
                                                    <div class="col ">
                                                        <?php if ($_product->getIsSalable()): ?>
                                                            <div class="stock available">
                                                                <span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable">
                                                                <span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                <div class="col-2 btn-wishlist">
                                                    <button type="button"
                                                        data-post='<?= /* @escapeNotVerified */ $block->getAddToWishlistParams($_product); ?>'
                                                        class="action towishlist mb-tooltip" data-action="add-to-wishlist"
                                                        title="<?= /* @escapeNotVerified */ __('Add to Wishlist') ?>"><i
                                                            class="mbi mbi-heart"></i></button>
                                                </div>
                                            <?php endif; ?>
                                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                <div class="col btn-compare">
                                                    <button type="button" class="action tocompare mb-tooltip"
                                                        data-post='<?= /* @escapeNotVerified */ $compareHelper->getPostDataParams($_product); ?>'
                                                        title="<?= /* @escapeNotVerified */ __('Add to Compare') ?>"><i
                                                            class="mbi mbi-chart-bars"></i></button>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                            <?php endif; ?>
                            </div>
                        </div>
                    </div>
                    <?php if (($i == $count || $i % $column == 0 || ($row > 1 && $i % $row == 0)) && $carousel): ?>
                    </div>
                </div>
            <?php endif ?>
            <?php if ($carousel && $row > 1 && $i == $count): ?>
            </div>
        <?php endif ?>
    <?php endforeach ?>
    <?php if (!$carousel): ?>
    </div>
<?php endif ?>