<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_B2BMarketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

/** @var $block \Webkul\Marketplace\Block\Account\Dashboard */

$getTopSaleProducts = $block->getTopSaleProducts();
$totalOrders = $block->getTotalOrders();
$approvedOrders = $block->getPendingOrders();
$processOrders = $block->getProcessingOrders();
$completeOrders = $block->getCompletedOrders();
if ($totalOrders) {
    $approve = ($approvedOrders*100)/$totalOrders;
    $process = ($processOrders*100)/$totalOrders;
    $complete = ($completeOrders*100)/$totalOrders;
} else {
    $approve = 0;
    $process = 0;
    $complete = 0;
}
$totalOrdersK = $totalOrders / 1000;
if ((int)$totalOrdersK) {
    $totalOrdersToDisplay = $totalOrdersK."K";
} else {
    $totalOrdersToDisplay = $totalOrders;
}
$approvedOrdersK = $approvedOrders / 1000;
if ((int)$approvedOrdersK) {
    $approvedOrdersToDisplay = $approvedOrdersK."K";
} else {
    $approvedOrdersToDisplay = $approvedOrders;
}
$processOrdersK = $processOrders / 1000;
if ((int)$processOrdersK) {
    $processOrdersToDisplay = $processOrdersK."K";
} else {
    $processOrdersToDisplay = $processOrders;
}
$completeOrdersK = $completeOrders / 1000;
if ((int)$completeOrdersK) {
    $completeOrdersToDisplay = $completeOrdersK."K";
} else {
    $completeOrdersToDisplay = $completeOrders;
}
$totalProducts = $block->getTotalProducts();
$totalProductsK = $totalProducts / 1000;
if ((int)$totalProductsK) {
    $totalProductToDisplay = $totalProductsK."K";
} else {
    $totalProductToDisplay = $totalProducts;
}
$totalCustomers = $block->getTotalCustomers();
$totalCustomersK = $totalCustomers / 1000;
if ((int)$totalCustomersK) {
    $totalCustomersToDisplay = $totalCustomersK."K";
} else {
    $totalCustomersToDisplay = $totalCustomers;
}
$currentMonthCustomers = $block->getTotalCustomersCurrentMonth();
$currentMonthCustomersK = $currentMonthCustomers / 1000;
if ((int)$currentMonthCustomersK) {
    $currentMonthCustomersToDisplay = $currentMonthCustomersK."K";
} else {
    $currentMonthCustomersToDisplay = $currentMonthCustomers;
}
$lastMonthCustomers = $block->getTotalCustomersLastMonth();
$lastMonthCustomersK = $lastMonthCustomers / 1000;
if ((int)$lastMonthCustomersK) {
    $lastMonthCustomersToDisplay = $lastMonthCustomersK."K";
} else {
    $lastMonthCustomersToDisplay = $lastMonthCustomers;
}?>
<div class="wk-mp-dashboard-total-container">
    <div class="wk-mp-dashboard-total wk-mp-dashboard-total-order wk-mp-first-column">
        <div class="wk-mp-dashboard-border">
            <div class="wk-mp-dashboard-total-left">
                <div class="wk-dashboard-sales-value wk-dashboard-sales-font">
                    <?= $block->escapeHtml($totalOrdersToDisplay) ?>
                </div>
                <div class="wk-dashboard-total-left-bottom">
                    <?= $block->escapeHtml(__('Order(s)')) ?>
                </div>
            </div>
            <div class="wk-mp-dashboard-total-right">
                <div class="wk-mp-dashboard-total-progress-bar">
                    <small>
                        <span class="wk-mp-float-left">
                            <?= $block->escapeHtml(__('Pending')) ?>
                        </span>
                        <span class="wk-mp-float-right">
                            <?= $block->escapeHtml($approvedOrdersToDisplay) ?>
                        </span>
                        <span
                            class="wk-mp-progress-color-bar wk-mp-approve-color-bar"
                            style="width:<?= $block->escapeHtml($approve); ?>%"></span>
                    </small>
                </div>
                <div class="wk-mp-dashboard-total-progress-bar">
                    <small>
                        <span class="wk-mp-float-left">
                            <?= $block->escapeHtml(__('Process')) ?>
                        </span>
                        <span class="wk-mp-float-right">
                            <?= $block->escapeHtml($processOrdersToDisplay) ?>
                        </span>
                        <span
                            class="wk-mp-progress-color-bar wk-mp-process-color-bar"
                            style="width:<?= $block->escapeHtml($process); ?>%"></span>
                    </small>
                </div>
                <div class="wk-mp-dashboard-total-progress-bar">
                    <small>
                        <span class="wk-mp-float-left">
                            <?= $block->escapeHtml(__('Complete')) ?>
                        </span>
                        <span class="wk-mp-float-right">
                            <?= $block->escapeHtml($completeOrdersToDisplay) ?>
                        </span>
                        <span
                            class="wk-mp-progress-color-bar wk-mp-complete-color-bar"
                            style="width:<?= $block->escapeHtml($complete); ?>%"></span>
                    </small>
                </div>
            </div>
        </div>
    </div>
    <div class="wk-mp-dashboard-total wk-mp-dashboard-total-product">
        <div class="wk-mp-dashboard-border">
            <div class="wk-mp-dashboard-total-left">
                <strong class="wk-dashboard-sales-value wk-dashboard-sales-font">
                    <span class="price">
                        <?= $block->escapeHtml($totalProductToDisplay) ?>
                    </span>
                </strong>
                <span class="wk-dashboard-total-left-bottom">
                    <?= $block->escapeHtml(__('Product(s)')) ?>
                </span>
            </div>
            <div class="wk-mp-dashboard-total-right">
                <div class="wk-dashboard-products-top wk-dashboard-sales-value">
                    <small><?= $block->escapeHtml(__('Top Selling Products')) ?></small>
                </div>
                <small class="wk-mp-products-bottom">
                    <ul>
                        <?php foreach ($getTopSaleProducts as $key => $value) { ?>
                            <li>
                                <span class="wk-mp-float-left">
                                    <a href="<?= $block->escapeHtml($value['url'])?>">
                                    <?= $block->escapeHtml($value['name'])?></a>
                                </span>
                                <span class="wk-mp-float-right">
                                    <?= $block->escapeHtml(__('%1 Sales', $value['qty'])) ?>
                                </span>
                            </li>
                        <?php } ?>
                    </ul>
                </small>
            </div>
        </div>
    </div>
    <div class="wk-mp-dashboard-total wk-mp-dashboard-total-customer wk-mp-last-column">
        <div class="wk-mp-dashboard-border">
            <div class="wk-mp-dashboard-total-left">
                <strong class="wk-dashboard-sales-value wk-dashboard-sales-font">
                    <span class="price">
                        <?= $block->escapeHtml($totalCustomersToDisplay); ?>
                    </span>
                </strong>
                <span class="wk-dashboard-total-left-bottom">
                    <?= $block->escapeHtml(__('Customer(s)')) ?>
                </span>
            </div>
            <div class="wk-mp-dashboard-total-right">
                <div class="wk-mp-dashboard-customers-top">
                    <small>
                        <?= $block->escapeHtml(__('This month customer count')) ?>
                            : <strong><?= $block->escapeHtml($currentMonthCustomersToDisplay); ?></strong>
                    </small>
                </div>
                <div class="wk-mp-dashboard-customers-bottom">
                    <small>
                        <?= $block->escapeHtml(__('Last month customer count')) ?>
                        : <strong><?= $block->escapeHtml($lastMonthCustomersToDisplay); ?></strong>
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>