<?php
	
//	$authToken = $block->getData('authToken');
//	$live = $block->getConfig('payment/payprocheckout/live');
//	$magentoUpdateStatusUrl = $block->getStatusUrl();
//    $payproConfirmationUrl = "";
//
//	if ($live == 1) {
//		$payproConfirmationUrl = 'http://localhost/payproredirect/magento.php';
//	} else {
//		$payproConfirmationUrl = 'http://localhost/payproredirect/magento.php';
//
//	}

?>

<!--<form name="payproconfirmform" method="post" action="--><?php //echo $payproConfirmationUrl; ?><!--">-->
<!--    <input name="auth_token" value="--><?php //echo $authToken; ?><!--" hidden = "true"/>-->
<!--    <input name="postBackURL" value="--><?php //echo $magentoUpdateStatusUrl; ?><!--" hidden = "true"/>-->
<!--</form>-->

<!--<script type="text/javascript">-->
<!--     document.payproconfirmform.submit();-->
<!--</script>-->
