<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<button type="submit"
    data-role="proceed-to-checkout"
    title="<?= $block->escapeHtml(__('Proceed to Checkout')) ?>"
    data-mage-init='{"Magento_Checkout/js/proceed-to-checkout":{"checkoutUrl":"<?= $block
    ->escapeHtml($block->getCheckoutUrl()) ?>"}}'
    class="wk-btn wk-btn-primary checkout<?= ($block->isDisabled()) ? ' disabled' : '' ?>"
    <?php if ($block->isDisabled()):?>disabled="disabled"<?php endif; ?>>
    <span><?= $block->escapeHtml(__('Proceed to Checkout')) ?></span>
</button>
