<?php
/**
 * Webkul Affiliate User Navigation.
 *
 * @category  Webkul
 * @package   Webkul_Affiliate
 * @author    Webkul
 * @license   https://store.webkul.com/license.html
 */
$isAffiliate = $block->isAffiliate();
$config = $block->getAffiliateConfig();
if (($isAffiliate || $config['registration']) && $config['enable']) { ?>
<div class="block account-nav block-collapsible-nav wk-affiliate-main">
    <div class="title block-collapsible-nav-title"
        data-mage-init='{
            "toggleAdvanced": {
                "toggleContainers": "#block-collapsible-nav-affiliate",
                "selectorsToggleClass": "active"
            }
        }'>
        <strong><?= /* @noEscape */ __('Affiliate'); ?></strong>
    </div>
    <div class="content block-collapsible-nav-content" id="block-collapsible-nav-affiliate">
        <nav class="account-nav">
            <ul class="nav items">
            <?php
            if ($isAffiliate && $isAffiliate['status']==1) { ?>
                <li class="nav item <?= /* @noEscape */  $block->getNavSelectClass('mpaffiliate/user/summary'); ?>">
                    <?php if ($block->getNavSelectClass('mpaffiliate/user/summary')) { ?>
                        <strong><?= /* @noEscape */  __('Summary') ?></strong>
                    <?php } else { ?>
                        <a href="<?= /* @noEscape */  $block->getNavUrl('mpaffiliate/user/summary'); ?>">
                            <?= /* @noEscape */  __('Summary') ?>
                        </a>
                    <?php } ?>
                </li>
                <li class="nav item <?= /* @noEscape */  $block->getNavSelectClass('mpaffiliate/user/commission'); ?>">
                    <?php if ($block->getNavSelectClass('mpaffiliate/user/commission')) { ?>
                        <strong><?= /* @noEscape */  __('Commission Rate') ?></strong>
                    <?php } else { ?>
                        <a href="<?= /* @noEscape */  $block->getNavUrl('mpaffiliate/user/commission'); ?>">
                            <?= /* @noEscape */  __('Commission Rate') ?>
                        </a>
                    <?php } ?>
                </li>
                <?php
                    $navSelectClass = $block->getNavSelectClass('mpaffiliate/user/banner')
                                                    .$block->getNavSelectClass('mpaffiliate/user/ads');
                ?>
                <li class="nav item <?= /* @noEscape */  $navSelectClass; ?>">
                    <?php if ($navSelectClass) { ?>
                        <strong><?= /* @noEscape */  __('Banner & Ads') ?></strong>
                    <?php } else { ?>
                        <a href="<?= /* @noEscape */  $block->getNavUrl('mpaffiliate/user/banner'); ?>">
                            <?= /* @noEscape */  __('Banner & Ads') ?>
                        </a>
                    <?php } ?>
                </li>
                <li class="nav item <?= /* @noEscape */  $block->getNavSelectClass('mpaffiliate/user/campaign'); ?>">
                    <?php if ($block->getNavSelectClass('mpaffiliate/user/campaign')) { ?>
                        <strong><?= /* @noEscape */  __('E-mail Campaign') ?></strong>
                    <?php } else { ?>
                        <a href="<?= /* @noEscape */  $block->getNavUrl('mpaffiliate/user/campaign'); ?>">
                            <?= /* @noEscape */  __('E-mail Campaign') ?>
                        </a>
                    <?php } ?>
                </li>
                <li class="nav item <?= /* @noEscape */  $block->getNavSelectClass('mpaffiliate/user/traffic'); ?>">
                    <?php if ($block->getNavSelectClass('mpaffiliate/user/traffic')) { ?>
                        <strong><?= /* @noEscape */  __('Traffic') ?></strong>
                    <?php } else { ?>
                        <a href="<?= /* @noEscape */  $block->getNavUrl('mpaffiliate/user/traffic'); ?>">
                            <?= /* @noEscape */  __('Traffic') ?>
                        </a>
                    <?php } ?>
                </li>
                <li class="nav item <?= /* @noEscape */  $block->getNavSelectClass('mpaffiliate/user/sales'); ?>">
                    <?php if ($block->getNavSelectClass('mpaffiliate/user/sales')) { ?>
                        <strong><?= /* @noEscape */  __('Sales') ?></strong>
                    <?php } else { ?>
                        <a href="<?= /* @noEscape */  $block->getNavUrl('mpaffiliate/user/sales'); ?>">
                            <?= /* @noEscape */  __('Sales') ?>
                        </a>
                    <?php } ?>
                </li>
                <li class="nav item <?= /* @noEscape */  $block->getNavSelectClass('mpaffiliate/user/payments'); ?>">
                    <?php if ($block->getNavSelectClass('mpaffiliate/user/payments')) { ?>
                        <strong><?= /* @noEscape */  __('Payment Records') ?></strong>
                    <?php } else { ?>
                        <a href="<?= /* @noEscape */  $block->getNavUrl('mpaffiliate/user/payments'); ?>">
                            <?= /* @noEscape */  __('Payment Records') ?>
                        </a>
                    <?php } ?>
                </li>
                <li class="nav item <?= /* @noEscape */  $block->getNavSelectClass('mpaffiliate/user/statistics'); ?>">
                    <?php if ($block->getNavSelectClass('mpaffiliate/user/statistics')) { ?>
                        <strong><?= /* @noEscape */  __('Statistics') ?></strong>
                    <?php } else { ?>
                        <a href="<?= /* @noEscape */  $block->getNavUrl('mpaffiliate/user/statistics'); ?>">
                            <?= /* @noEscape */  __('Statistics') ?>
                        </a>
                    <?php } ?>
                </li>
                <li
                class="nav item <?= /* @noEscape */  $block->getNavSelectClass('mpaffiliate/user/requesttoseller'); ?>">
                    <?php if ($block->getNavSelectClass('mpaffiliate/user/requesttoseller')) { ?>
                            <strong><?= /* @noEscape */  __('Request To Seller') ?></strong>
                    <?php } else { ?>
                        <a href="<?= /* @noEscape */  $block->getNavUrl('mpaffiliate/user/requesttoseller'); ?>">
                            <?= /* @noEscape */  __('Request To Seller') ?>
                        </a>
                    <?php } ?>
                </li>
                <li
                class="nav item <?= /* @noEscape */  $block->getNavSelectClass('mpaffiliate/user/preferences'); ?>">
                    <?php if ($block->getNavSelectClass('mpaffiliate/user/preferences')) { ?>
                        <strong><?= /* @noEscape */  __('Payment Preference') ?></strong>
                    <?php } else { ?>
                        <a href="<?= /* @noEscape */  $block->getNavUrl('mpaffiliate/user/preferences'); ?>">
                            <?= /* @noEscape */  __('Payment Preference') ?>
                        </a>
                    <?php } ?>
                </li>
                <li class="nav item <?= /* @noEscape */  $block->getNavSelectClass('mpaffiliate/user/status'); ?>">
                    <?php if ($block->getNavSelectClass('mpaffiliate/user/status')) { ?>
                            <strong><?= /* @noEscape */  __('Blog Url') ?></strong>
                    <?php } else { ?>
                        <a href="<?= /* @noEscape */  $block->getNavUrl('mpaffiliate/user/status'); ?>">
                            <?= /* @noEscape */  __('Blog Url') ?>
                        </a>
                    <?php } ?>
                </li>
                <?= /* @noEscape */  $block->getChildHtml();
            } elseif ($config['registration']) { ?>
                <?= /* @noEscape */  $block->getChildHtml();?>
                <li
                class="nav item <?= /* @noEscape */  $block->getNavSelectClass('mpaffiliate/user/becomeaffiliate') ?>">
                    <?php if ($block->getNavSelectClass('mpaffiliate/user/becomeaffiliate')) { ?>
                        <strong><?= /* @noEscape */  __('Become Affiliate User') ?></strong>
                    <?php } else { ?>
                        <a href="<?= /* @noEscape */  $block->getNavUrl('mpaffiliate/user/becomeaffiliate'); ?>">
                            <?= /* @noEscape */  __('Become Affiliate User') ?>
                        </a>
                    <?php } ?>
                </li>
            <?php } ?>
            </ul>
        </nav>
    </div>
</div>
<?php }
?>
