<?php
/**
 * Webkul MpAffiliate User Summary template.
 * @category  Webkul
 * @package   Webkul_MpAffiliate
 * @author    Webkul
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
$viewModel = $block->getViewModel();
$isAffiliate=$block->isAffiliate();
$priceHelper = $viewModel->getPricingHelper();
if ($isAffiliate) {
    ?>
<div class="fieldset wk_fieldset">
    <div class="grid">
        <div class="hor-scroll">
            <form action="" method="get">
                <table cellspacing="0" class="border wk-mp-list-table">
                    <thead>
                        <tr id="wk-mp-tr-heading">
                            <th><span><?= /* @noEscape */ __('Order Id#') ?></span></th>
                            <th><span>&nbsp;</span></th>
                        </tr>
                    </thead>
                    <tbody class="wk-mp-body">
                        <tr>
                            <td>
                                <span class="">
                                    <input type="text" name="aff_order" id="aff_order"
                                    class="input-text"
                                    value="<?= /* @noEscape */ $block->getRequest()->getParam('aff_order')?>"
                                    placeholder="<?= /* @noEscape */ __('Search By Order Id'); ?>"/>
                                </span>
                            </td>
                            <td>
                                <button class="button" title="Save" type="submit">
                                    <span><span><span><?= /* @noEscape */ __('Submit') ?></span></span></span>
                                </button>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </form>
            <table cellspacing="0" class="border wk-mp-list-table wk-mp-list-container-table">
                <thead>
                    <tr class="wk-content">
                        <th>
                            <span class="label"><?= /* @noEscape */ __('Seller Name')?></span>
                        </th>
                        <th class="">
                            <span class="label"><?= /* @noEscape */ __('# Order ID')?></span>
                        </th>
                        <th>
                            <span class="label"><?= /* @noEscape */ __('Commission')?></span>
                        </th>
                        <th>
                            <span class="label"><?= /* @noEscape */ __('Status')?></span>
                        </th>
                        <th>
                            <span class="label"><?= /* @noEscape */ __('Date')?></span>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($block->getSaleAff() as $key => $val) { ?>
                        <tr class="wk_row_view">
                            <td class="wk_first_td_th">
                            <span class="label"><?= /* @noEscape */ $block->getSellerName($val['seller_id']); ?></span>
                            </td>
                            <td class="">
                            <span title="Pro1" class="label"><?= /* @noEscape */ $val['order_increment_id'] ?></span>
                            </td>
                            <td>
                            <span title="Pro1" class="label">
                            <?= /* @noEscape */ $priceHelper->currency($val['commission'], true, false) ?>
                            </span>
                            </td>
                            <td>
                            <span title="Pro1" class="label"><?= /* @noEscape */ $val['order_status']?></span>
                            </td>
                            <td>
                            <span title="Pro1" class="label">
                                <?php $date = date_create($val['created_at']) ?>
                                <?= /* @noEscape */ date_format($date, 'd/m/y') ?>
                            </span>
                            </td>
                        </tr>
                        <div class="wk_clear"></div>
                    <?php } ?>
                </tbody>
            </table>
            <?= /* @noEscape */ $block->getPagerHtml();?>
            <?php if (count($block->getSaleAff()) <= 0) { ?>
                <div class="fieldset wk_mp_fieldset">
                    <div class="wk_emptymsg" style="text-align:center;">
                        <?= /* @noEscape */ __('No Sales History Available') ?>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
</div>
<?php } ?>
<div class="buttons-set">
    <p class="back-link">
        <a href="javascript:;" onclick="javascript: window.history.back();" class="left">
            &laquo; <?= /* @noEscape */ __('Back') ?>
        </a>
    </p>
</div>
