<?php
/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<style>

.main-container .columns .sidebar-wrap { display: none; }
#product-container-wrap .products.wrapper.grid.products-grid,
#product-container-wrap .toolbar-products {display: none}


.main-container .row .col-lg-8,
.main-container .row .col-xl-9{flex: 0 0 100%; max-width: 100%;}

.custom_design_plp .main_body_service_plp{display: flex; justify-content: space-between;}
.custom_design_plp .main_body_service_plp .main_body_products{padding: 20px 50px 0 0 ;   width: 75%;}


.custom_design_plp .main_body_service_plp .main_body_contact{padding: 20px 0 20px 0 }
.custom_design_plp .main_body_service_plp .main_body_contact .get_in_touch{background-color: #fff; padding: 50px 30px}
.custom_design_plp .main_body_service_plp .main_body_contact .get_in_touch form input{display:block; width: 100%; margin: 20px 0; padding: 8px 10px; border: 1px solid #888; border-radius: 10px;}
.custom_design_plp .main_body_service_plp .main_body_contact .get_in_touch form textarea{display:block; width: 100%; margin: 20px 0; padding: 8px 10px; resize: none; border: 1px solid #888; border-radius: 10px; }
.custom_design_plp .main_body_service_plp .main_body_contact .get_in_touch form Button{display:block; width: 100%; margin: 20px 0; padding: 8px 10px; resize: none; border: none; border-radius: 10px; background: linear-gradient(180deg, #EB2291 0%, #FF1A00 100%); color: #fff; }


.custom_design_plp .main_body_service_plp .main_body_contact .get_in_touch .touch_address {
    margin-top: 20px;
}

.custom_design_plp .main_body_service_plp .main_body_contact .get_in_touch .touch_address h4{
	margin-bottom: 20px;
}

.custom_design_plp .main_body_service_plp .main_body_products .single_product {
    background: #fff;
    padding: 20px;
    display: flex;
    justify-content: space-between;
    gap: 20px;
    border-radius: 12px;
}

.custom_design_plp .main_body_service_plp .main_body_products .img-wrap { 
    background-size: cover !important;
    width: 100%;
    background-position: center !important;
}

.custom_design_plp .main_body_service_plp .main_body_products .single_product{margin-bottom: 25px;}
.custom_design_plp .main_body_service_plp .main_body_products .details_wrap .heading h4{font-weight: 500; font-size: 24px; color: #000000;}
.custom_design_plp .main_body_service_plp .main_body_products .details_wrap .author{display: flex;}
.custom_design_plp .main_body_service_plp .main_body_products .details_wrap .author img{border-radius: 50%; width:25px; height: 25px; margin-right: 6px;}
.custom_design_plp .main_body_service_plp .main_body_products .details_wrap .author p{font-size: 16px; font-weight: 400;}
.custom_design_plp .main_body_service_plp .main_body_products .details_wrap .rating{}
.custom_design_plp .main_body_service_plp .main_body_products .details_wrap .description p{font-weight: 400; font-size: 16px; text-transform: capitalize; color: #363636; margin-bottom: 16px;}
.custom_design_plp .main_body_service_plp .main_body_products .details_wrap .price p{margin-bottom: 0; font-weight: 400; font-size: 12px;text-transform: uppercase; color: #A6A6A6;}
.custom_design_plp .main_body_service_plp .main_body_products .details_wrap .price h2{font-weight: 700; font-size: 18px;text-transform: capitalize; color: #000;}

.custom_design_plp .main_body_service_plp .main_body_products .single_product:hover {color:#fff; background: linear-gradient(180deg, #EB2291 0%, #FF1A00 100%); box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.25);}
.custom_design_plp .main_body_service_plp .main_body_products .single_product:hover .heading h4{color:#fff !important; }
.custom_design_plp .main_body_service_plp .main_body_products .single_product:hover .description p{color:#fff !important; }
.custom_design_plp .main_body_service_plp .main_body_products .single_product:hover .author p{color:#fff !important; }
.custom_design_plp .main_body_service_plp .main_body_products .single_product:hover .price p{color:#fff !important; }
.custom_design_plp .main_body_service_plp .main_body_products .single_product:hover .price h2{color:#fff !important; }

.custom_design_plp .owl-carousel.owl-theme.owl-loaded.owl-drag .item-slider {
    background: #fff;
    padding: 20px;
    border-radius: 22px;
    text-align: center;
    width: 180px;
}
.custom_design_plp .owl-carousel.owl-theme.owl-loaded.owl-drag .item-slider .img_wrap_cat img{
	width: 100%; height: auto;
}


.custom_design_plp .cat_heeading h3 {
    font-weight: 700;
    font-size: 24px;
    text-transform: capitalize;
    color: #000000;
    margin: 40px 0 20px 0;
}

.main_body_contact .get_in_touch .touch_address div {
    margin: 20px 0;
}

.custom_design_plp .main_body_service_plp {
    margin-top: 50px;
}


</style>



<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$mbHelper = $this->helper('MageBig\MbFrame\Helper\Data');
$labelHelper = $this->helper('MageBig\WidgetPlus\Helper\Config');

$showAddCart = $mbHelper->getConfig('mbconfig/category_view/show_addcart');
$showCompare = $mbHelper->getConfig('mbconfig/category_view/show_compare');
$showWishlist = $mbHelper->getConfig('mbconfig/category_view/show_wishlist');
$showRating = $mbHelper->getConfig('mbconfig/category_view/show_rating');
$showQuickview = $mbHelper->getConfig('mbconfig/category_view/show_quickview');
$isHover = $mbHelper->getConfig('mbconfig/category_view/product_image_hover');
?>
<?= $block->getChildHtml('category.product.filter.mobile'); ?>

    <!--
    <div class="custom_design_plp">
        <div class="cat_heeading"><h3>Our Education Services</h3></div>
        <div class="owl-carousel owl-theme">
            <div class="item-slider">
                <div class="img_wrap_cat"><img alt="imarkplace" src="/media/avatar/7-4.jpg" alt="Cat Img"></div>
                <div class="text_wrap_cat"><p>Amet Minim Mollit</p></div>
            </div>
            <div class="item-slider">
                <div class="img_wrap_cat"><img alt="imarkplace" src="/media/avatar/7-4.jpg" alt="Cat Img"></div>
                <div class="text_wrap_cat"><p>Amet Minim Mollit</p></div>
            </div>
            <div class="item-slider">
                <div class="img_wrap_cat"><img alt="imarkplace" src="/media/avatar/7-4.jpg" alt="Cat Img"></div>
                <div class="text_wrap_cat"><p>Hira foundation school</p></div>
            </div>
            <div class="item-slider">
                <div class="img_wrap_cat"><img alt="imarkplace" src="/media/avatar/7-4.jpg" alt="Cat Img"></div>
                <div class="text_wrap_cat"><p>Amet Minim Mollit</p></div>
            </div>
            <div class="item-slider">
                <div class="img_wrap_cat"><img alt="imarkplace" src="/media/wysiwyg/shopping_bag.svg" alt="Cat Img"></div>
                <div class="text_wrap_cat"><p>Amet Minim Mollit</p></div>
            </div>
            <div class="item-slider">
                <div class="img_wrap_cat"><img alt="imarkplace" src="/media/wysiwyg/shopping_bag.svg" alt="Cat Img"></div>
                <div class="text_wrap_cat"><p>Amet Minim Mollit</p></div>
            </div>
            <div class="item-slider">
                <div class="img_wrap_cat"><img alt="imarkplace" src="/media/wysiwyg/shopping_bag.svg" alt="Cat Img"></div>
                <div class="text_wrap_cat"><p>Amet Minim Mollit</p></div>
            </div>
            <div class="item-slider">
                <div class="img_wrap_cat"><img alt="imarkplace" src="/media/wysiwyg/shopping_bag.svg" alt="Cat Img"></div>
                <div class="text_wrap_cat"><p>Amet Minim Mollit</p></div>
            </div>
            <div class="item-slider">
                <div class="img_wrap_cat"><img alt="imarkplace" src="/media/wysiwyg/shopping_bag.svg" alt="Cat Img"></div>
                <div class="text_wrap_cat"><p>Amet Minim Mollit</p></div>
            </div>
            <div class="item-slider">
                <div class="img_wrap_cat"><img alt="imarkplace" src="/media/wysiwyg/shopping_bag.svg" alt="Cat Img"></div>
                <div class="text_wrap_cat"><p>Amet Minim Mollit</p></div>
            </div>
        </div>
        <div class="main_body_service_plp">
            <div class="main_body_products">
                <div class="single_product">
                    <div class="img-wrap" style="background-image: url(/media/magefan_blog/brooke-cagle-241296.jpg)">
                    </div>
                    <div class="details_wrap">
                        <div class="heading">
                            <h4>IELTS Preparation Course (Essential)</h4>
                        </div>
                        <div class="author">
                            <img alt="imarkplace" src="/media/magefan_blog/brooke-cagle-241296.jpg" >
                            <p>Jenny Wilson</p>
                        </div>
                        <div class="rating">
                            ***** (1)
                        </div>
                        <div class="description">
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, a explicabo voluptatem repudiandae similique tempore at, reiciendis dolor debitis hic laudantium distinctio sapiente quis, consequatur soluta in nihil.</p>
                        </div>
                        <div class="price">
                            <p>Starting at</p>
                            <h2>PKR 17,000</h2>
                        </div>
                    </div>
                </div>
                <div class="single_product">
                    <div class="img-wrap" style="background-image: url(/media/magefan_blog/brooke-cagle-241296.jpg)">
                    </div>
                    <div class="details_wrap">
                        <div class="heading">
                            <h4>IELTS Preparation Course (Essential)</h4>
                        </div>
                        <div class="author">
                            <img alt="imarkplace" src="/media/magefan_blog/brooke-cagle-241296.jpg" >
                            <p>Jenny Wilson</p>
                        </div>
                        <div class="rating">
                            ***** (1)
                        </div>
                        <div class="description">
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, a explicabo voluptatem repudiandae similique tempore at, reiciendis dolor debitis hic laudantium distinctio sapiente quis, consequatur soluta in nihil.</p>
                        </div>
                        <div class="price">
                            <p>Starting at</p>
                            <h2>PKR 17,000</h2>
                        </div>
                    </div>
                </div>
                <div class="single_product">
                    <div class="img-wrap" style="background-image: url(/media/magefan_blog/brooke-cagle-241296.jpg)">
                    </div>
                    <div class="details_wrap">
                        <div class="heading">
                            <h4>IELTS Preparation Course (Essential)</h4>
                        </div>
                        <div class="author">
                            <img alt="imarkplace" src="/media/magefan_blog/brooke-cagle-241296.jpg" >
                            <p>Jenny Wilson</p>
                        </div>
                        <div class="rating">
                            ***** (1)
                        </div>
                        <div class="description">
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, a explicabo voluptatem repudiandae similique tempore at, reiciendis dolor debitis hic laudantium distinctio sapiente quis, consequatur soluta in nihil.</p>
                        </div>
                        <div class="price">
                            <p>Starting at</p>
                            <h2>PKR 17,000</h2>
                        </div>
                    </div>
                </div>
            </div>
            <div class="main_body_contact">
                <div class="get_in_touch">
                    <form action="">
                        <h4>Get In Touch</h4>
                        <input type="text" name="" placeholder="Name" id="">
                        <input type="text" name="" placeholder="Email" id="">
                        <textarea name="" id="" placeholder="Message" cols="30" rows="3"></textarea>
                        <Button>Get In Touch</Button>
                    </form>
                    <div class="touch_address">
                        <h4>Get In Touch</h4>
                        <div class="address">
                            <p>2478, Gulshan Karachi</p>
                        </div>
                        <div class="email">
                            <p>Info@example.com</p>
                        </div>
                        <div class="phone">
                            <p>0147-2014786</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    -->



<?php if (!$_productCollection->count()): ?>
   <!-- <div class="message info empty"><div><? //= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>-->
     <div class="comingsoon" style="height: 500px; justify-content: center; align-items: center; color: rgb(233, 20, 49); font-size: 40px; text-align: center; padding-top: 25px; margin-bottom: 0px;">
            Coming Soon!
            <div style="justify-content: center; align-items: center; color: rgba(0, 0, 0, 0.87); font-size: 18px; width: 90%; text-align: center; margin: auto;">
                <br><p>We are gearing ourselves up to provide you with the best digital experience.</p>
            </div>
    </div>
<?php else: ?>
    <?php
    $toolbar = $block->getToolbarHtml();
    echo $toolbar;
    ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        $class = $mbHelper->getPageColumn();
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        $class = 'col-12';
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>

   
    <?php if ($viewMode == 'grid') : ?>
        <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode; ?> products-<?= /* @escapeNotVerified */ $viewMode; ?>">
            <?php $iterator = 1; ?>
            <ol class="products list items product-items row">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item product product-item <?= $class ?>">
                        <div class="product-item-info test99 adeel" data-container="product-grid">
                            <div class="product-show">
                                <?php $productImage = $block->getImage($_product, $image); ?>
                                <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo">
                                    <span class="main-photo"><?= $productImage->toHtml(); ?></span>
                                    <?php if ($isHover) : ?>
                                        <?php $hoverImg = $block->getImage($_product, 'product_grid_hover'); ?>
                                        <?php if (!strpos($hoverImg->getImageUrl(), 'mb_hover_img')) : ?>
                                            <span class="hover-photo"><?= $hoverImg->toHtml(); ?></span>
                                        <?php endif ?>
                                    <?php endif ?>
                                    <?php if ($labelHelper->getDiscountPercent($_product)) : ?>
                                        <span class="discount-percent"><?= $labelHelper->getDiscountPercent($_product); ?></span>
                                    <?php endif;?>
                                </a>
                                <div class="product details product-item-details">
                                    <?php if ($_product->getTypeId() == 'configurable') : ?>
                                        <div class="swatches-list">
                                            <?= $block->getProductDetailsHtml($_product); ?>
                                        </div>
                                    <?php else : ?>
                                        <?= $block->getProductDetailsHtml($_product); ?>
                                    <?php endif; ?>
                                    <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                    ?>
                                    <h2 class="product name product-item-name">
                                        <a class="product-item-link"
                                        href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>"
                                        title="<?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>">
                                            <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </a>
                                    </h2>
                                    <?php if ($showRating) : ?>
                                        <?= $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                    <?php endif; ?>
                                    <?= /* @escapeNotVerified */ $block->getProductPriceHtml(
                                        $_product,
                                        \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE,
                                        \Magento\Framework\Pricing\Render::ZONE_ITEM_LIST
                                    ) ?>
                                </div>
                                <div class="product-btn">
                                    <div class="row no-gutters text-center">
                                        

                                        <div class="col-2 btn-qiuk-view" <?php if (!$showQuickview) : ?>style="display: none;"<?php endif; ?>>
                                            <?= $this->helper('MageBig\QuickView\Helper\Data')->getQuickViewButton($_product, 'mb-tooltip'); ?>
                                        </div>
                                        <?php if ($showAddCart) : ?>
                                            <?php if ($_product->isSaleable()): ?>
                                                <div class="col-8 btn-add-to-cart">
                                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                    <form data-role="tocart-form" data-product-sku="<?=  /* @NoEscape */ $_product->getSku() ?>" action="<?= /* @escapeNotVerified */ $postParams['action'] ?>" method="post">
                                                        <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $_product->getEntityId() ?>">
                                                        <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED; ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                        <?= $block->getBlockHtml('formkey') ?>
                                                        <button type="submit"
                                                            title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                            class="action tocart mb-tooltip">
                                                            <!-- <i class="mbi mbi-bag2" ><span>Add to cart </span></i> -->
                                                            <span class="bag-img-icon"><img alt="imarkplace" src="/media/wysiwyg/shopping_bag.svg">Add to cart </span>
                                                        </button>
                                                    </form>
                                                </div>
                                            <?php else: ?>
                                                <div class="col-2">
                                                    <?php if ($_product->getIsSalable()): ?>
                                                        <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                            <div class="col-2 btn-wishlist">
                                                <button type="button"
                                                        data-post='<?= /* @escapeNotVerified */ $block->getAddToWishlistParams($_product); ?>'
                                                        class="action towishlist mb-tooltip" data-action="add-to-wishlist"
                                                        title="<?= /* @escapeNotVerified */ __('Add to Wishlist') ?>"><i aria-hidden="true" class="mbi mbi-heart"></i></button>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                            <div class="col btn-compare">
                                                <button type="button" class="action tocompare mb-tooltip"
                                                        data-post='<?= /* @escapeNotVerified */ $compareHelper->getPostDataParams($_product);?>'
                                                        title="<?= /* @escapeNotVerified */ __('Add to Compare') ?>"><i aria-hidden="true" class="mbi mbi-chart-bars"></i></button>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    <?php else : ?>
        <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode; ?> products-<?= /* @escapeNotVerified */ $viewMode; ?>">
            <?php $iterator = 1; ?>
            <ol class="products list items product-items row">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item product product-item <?= $class ?>">
                        <div class="product-item-info" data-container="product-grid">
                            <?php
                            $productImage = $block->getImage($_product, $image);
                            ?>
                            <div class="row product details product-item-details">
                                <div class="col-12 col-sm-3">
                                    <div class="product-show">
                                        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                            <span class="main-photo"><?= $productImage->toHtml(); ?></span>
                                            <?php if ($isHover) : ?>
                                                <?php $hoverImg = $block->getImage($_product, 'product_grid_hover'); ?>
                                                <?php if (!strpos($hoverImg->getImageUrl(), 'mb_hover_img')) : ?>
                                                    <span class="hover-photo"><?= $hoverImg->toHtml(); ?></span>
                                                <?php endif ?>
                                            <?php endif ?>
                                            <?php if ($labelHelper->getDiscountPercent($_product)) : ?>
                                                <span class="discount-percent"><?= $labelHelper->getDiscountPercent($_product); ?></span>
                                            <?php endif;?>
                                        </a>
                                        <?= $this->helper('MageBig\QuickView\Helper\Data')->getQuickViewButton($_product, 'mb-tooltip'); ?>
                                        <?php if ($_product->getTypeId() == 'configurable') : ?>
                                            <div class="swatches-list">
                                                <?= $block->getProductDetailsHtml($_product); ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-9">
                                    <div class="row">
                                        <div class="col-12 col-sm-8">
                                            <div class="product-list-details">
                                                <?php
                                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                                ?>
                                                <h2 class="product name product-item-name">
                                                    <a class="product-item-link"
                                                       href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>"
                                                       title="<?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>">
                                                        <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                                    </a>
                                                </h2>
                                                <?php if ($showRating) : ?>
                                                    <?= $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                                <?php endif; ?>

                                                <div class="product-item-inner">
                                                    <?php if ($showDescription):?>
                                                        <div class="product description product-item-description">
                                                            <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                                        </div>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-12 col-sm-4">
                                            <div class="product-btn-info">
                                                <?= /* @escapeNotVerified */ $block->getProductPriceHtml(
                                                    $_product,
                                                    \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE,
                                                    \Magento\Framework\Pricing\Render::ZONE_ITEM_LIST
                                                ) ?>
                                                <?php if ($showAddCart) : ?>
                                                    <?php if ($_product->isSaleable()): ?>
                                                        <div class="price-block">
                                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                            <form data-role="tocart-form" data-product-sku="<?=  /* @NoEscape */ $_product->getSku() ?>" action="<?= /* @escapeNotVerified */ $postParams['action'] ?>" method="post">
                                                                <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $_product->getEntityId() ?>">
                                                                <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                                <?= $block->getBlockHtml('formkey')?>
                                                                <button type="submit"
                                                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                        class="action tocart primary"><span><?= $block->escapeHtml(__('Add to Cart')) ?></span></button>
                                                            </form>
                                                        </div>
                                                    <?php else: ?>
                                                        <div class="price-block">
                                                            <?php if ($_product->getIsSalable()): ?>
                                                                <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                                            <?php else: ?>
                                                                <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>
                                                <?php endif; ?>

                                                <?php if ($showWishlist || $showCompare): ?>
                                                    <div class="row no-gutters">
                                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                            <div class="col btn-wishlist">
                                                                <button type="button"
                                                                        data-post='<?= /* @escapeNotVerified */ $block->getAddToWishlistParams($_product); ?>'
                                                                        class="action towishlist" data-action="add-to-wishlist"
                                                                        title="<?= /* @escapeNotVerified */ __('Add to Wishlist') ?>"><i aria-hidden="true" class="mbi mbi-heart"></i> <span><?= /* @escapeNotVerified */ __('Wishlist') ?></span></button>
                                                            </div>
                                                        <?php endif; ?>
                                                        <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                            <div class="col btn-compare">
                                                                <button type="button" class="action tocompare"
                                                                        data-post='<?= /* @escapeNotVerified */ $compareHelper->getPostDataParams($_product);?>'
                                                                        title="<?= /* @escapeNotVerified */ __('Add to Compare') ?>"><i aria-hidden="true" class="mbi mbi-chart-bars"></i> <span><?= /* @escapeNotVerified */ __('Compare') ?></span></button>
                                                            </div>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    <?php endif; ?>


    <?= $toolbar ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>


<script>
    require(['jquery', 'owlWidget'], function($) {
        $(function() {
            $('.custom_design_plp').owlWidget({
                // items: 7,
                dots: false,
                nav: true,
                loop: false,
                margin: 15,
                responsive: {
                    "0": {
                        "items": 1
                    },
                    "576": {
                        "items": 1
                    },
                    "768": {
                        "items": 1
                    },
                    "992": {
                        "items": 6
                    },
                    "1200": {
                        "items": 6
                    }
                }
            });
        });
    });
</script>
