<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_B2BMarketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
/** @var $block \Webkul\Marketplace\Block\Page\Notofications */
?>
<ul class="wk-mp__action-dropdown-menu wk-mp-dashboard-notifications-menu">
    <?php foreach ($block->getAllNotification() as $notification) { ?>
        <?= /* @noEscape */ $block->getNotificationInfo($notification); ?>
    <?php } ?>
    <li>
        <small>
            <a href="<?= /* @noEscape */ $block->getUrl('marketplace/account/notification')?>">
                <?= /* @noEscape */ __("View All")?>
            </a>
        </small>
    </li>
</ul>