<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_B2BMarketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

?>
<img 
    src="<?= $block->escapeHtml($block->getSellerStatisticsGraphUrl('feed_value')) ?>" 
    alt="<?= $block->escapeHtml(__('Value Reviews'))?>" 
    title="<?= $block->escapeHtml(__('Value Reviews'))?>" />